// Confetti Outing Category System v2
// Universal taxonomy: 150+ outing categories across 12 groups with metadata
// that drives vibe mapping, venue filtering, safety rules, and city logic.

export type WaterfrontRelevance = "none" | "optional" | "preferred" | "required";
export type Intensity = "low" | "medium" | "high";

export type CategoryGroupId =
  | "social"
  | "nightlife"
  | "chill"
  | "food"
  | "culture"
  | "adventure"
  | "action"
  | "luxury"
  | "wellness"
  | "shopping"
  | "local"
  | "custom";

export type OutingCategory = {
  id: string;
  name: string;
  group: CategoryGroupId;
  description: string;
  defaultVibes: string[];
  compatibleVibes: string[];
  venueTypes: string[];
  activityTypes: string[];
  budgetTiers: (1 | 2 | 3 | 4)[];
  idealGroupSize: [number, number];
  waterfront: WaterfrontRelevance;
  familySafe: boolean;
  adultOnly: boolean;
  nightlifeIntensity: Intensity;
  conversationFriendly: boolean;
  weatherSensitive: boolean;
  seasonal: boolean;
  /** Hard guardrails: enforced filters when this category is in the request. */
  safetyFilters: string[];
  /** Venue types that must NEVER appear with this category. */
  avoidVenueTypes: string[];
  /** Slot blueprint hints for the planner (e.g. "Pre", "Main", "Late"). */
  suggestedSlots: string[];
};

export const CATEGORY_GROUPS: { id: CategoryGroupId; label: string; emoji: string }[] = [
  { id: "social", label: "Social", emoji: "👯" },
  { id: "nightlife", label: "Nightlife", emoji: "🍾" },
  { id: "chill", label: "Chill", emoji: "🌙" },
  { id: "food", label: "Food", emoji: "🍽️" },
  { id: "culture", label: "Culture", emoji: "🎭" },
  { id: "adventure", label: "Adventure", emoji: "🏞️" },
  { id: "action", label: "Action", emoji: "🎯" },
  { id: "luxury", label: "Luxury", emoji: "🥂" },
  { id: "wellness", label: "Wellness", emoji: "🧖" },
  { id: "shopping", label: "Shopping", emoji: "🛍️" },
  { id: "local", label: "Local", emoji: "📍" },
  { id: "custom", label: "Custom", emoji: "✨" },
];

// ── Defaults to keep entries compact ──────────────────────────────
const DEFAULTS = {
  budgetTiers: [1, 2, 3] as (1 | 2 | 3 | 4)[],
  idealGroupSize: [2, 8] as [number, number],
  waterfront: "optional" as WaterfrontRelevance,
  familySafe: true,
  adultOnly: false,
  nightlifeIntensity: "medium" as Intensity,
  conversationFriendly: true,
  weatherSensitive: false,
  seasonal: false,
  safetyFilters: [],
  avoidVenueTypes: [],
  suggestedSlots: ["Pre", "Main", "Late"],
};

function cat(
  input: Partial<OutingCategory> &
    Pick<OutingCategory, "id" | "name" | "group" | "description" | "defaultVibes" | "venueTypes">,
): OutingCategory {
  return {
    ...DEFAULTS,
    compatibleVibes: input.defaultVibes,
    activityTypes: input.activityTypes ?? input.venueTypes,
    ...input,
  } as OutingCategory;
}

// Reusable filter constants
const FAMILY_SAFE_FILTERS = [
  "no_strip_clubs",
  "no_clubs",
  "no_heavy_drinking",
  "no_adult_entertainment",
];
const CONVERSATION_FILTERS = ["no_loud_clubs", "no_dive_bars", "quiet_enough_to_talk"];
const ADULT_ONLY_FILTERS = ["age_21_plus", "no_minors"];
const AVOID_PARTY = ["nightclub", "strip_club", "rave"];

// ── Categories ────────────────────────────────────────────────────
export const OUTING_CATEGORIES: OutingCategory[] = [
  // 1. SOCIAL ─────────────────────────────────────────────────────
  cat({
    id: "girls_night",
    name: "Girls Night",
    group: "social",
    description: "Classic GNO — dinner, drinks, dancing.",
    defaultVibes: ["turn_up", "instagrammy"],
    venueTypes: ["cocktail_bar", "rooftop", "restaurant", "lounge", "dance_club"],
    idealGroupSize: [3, 8],
    familySafe: false,
    adultOnly: true,
    nightlifeIntensity: "high",
    safetyFilters: ADULT_ONLY_FILTERS,
  }),
  cat({
    id: "guys_night",
    name: "Guys Night",
    group: "social",
    description: "Bro time — sports, whiskey, big food.",
    defaultVibes: ["grown_man", "live_music"],
    venueTypes: ["sports_bar", "whiskey_bar", "steakhouse", "brewery"],
    idealGroupSize: [3, 10],
    familySafe: false,
    adultOnly: true,
    nightlifeIntensity: "medium",
    safetyFilters: ADULT_ONLY_FILTERS,
  }),
  cat({
    id: "couples_night",
    name: "Couples Night",
    group: "social",
    description: "Intimate date night for two.",
    defaultVibes: ["romantic", "soft_life"],
    venueTypes: ["fine_dining", "wine_bar", "rooftop"],
    idealGroupSize: [2, 2],
    nightlifeIntensity: "low",
  }),
  cat({
    id: "double_date",
    name: "Double Date",
    group: "social",
    description: "Two couples, conversation-friendly venues.",
    defaultVibes: ["romantic", "classy"],
    venueTypes: ["restaurant", "wine_bar", "lounge"],
    idealGroupSize: [4, 4],
    conversationFriendly: true,
    safetyFilters: CONVERSATION_FILTERS,
  }),
  cat({
    id: "group_night",
    name: "Group Night Out",
    group: "social",
    description: "Big crew, easy logistics.",
    defaultVibes: ["turn_up", "social"],
    venueTypes: ["brewery", "beer_garden", "rooftop", "karaoke"],
    idealGroupSize: [6, 20],
  }),
  cat({
    id: "solo_night",
    name: "Solo Night Out",
    group: "social",
    description: "Solo-friendly counters and walks.",
    defaultVibes: ["chill", "instagrammy"],
    venueTypes: ["counter_seat", "jazz_club", "wine_bar", "bookstore"],
    idealGroupSize: [1, 1],
  }),
  cat({
    id: "in_laws_night",
    name: "In-Laws Night",
    group: "social",
    description: "Impress without overdoing it.",
    defaultVibes: ["classy", "soft_life"],
    venueTypes: ["fine_dining", "wine_bar", "scenic_restaurant"],
    conversationFriendly: true,
    nightlifeIntensity: "low",
    safetyFilters: [...CONVERSATION_FILTERS, ...FAMILY_SAFE_FILTERS],
    avoidVenueTypes: [...AVOID_PARTY, "dive_bar", "loud_lounge"],
  }),
  cat({
    id: "family_night",
    name: "Family Night",
    group: "social",
    description: "Kid-friendly dinner & activity.",
    defaultVibes: ["family_friendly", "chill"],
    venueTypes: ["family_restaurant", "ice_cream", "mini_golf", "arcade"],
    idealGroupSize: [3, 8],
    familySafe: true,
    nightlifeIntensity: "low",
    safetyFilters: FAMILY_SAFE_FILTERS,
    avoidVenueTypes: AVOID_PARTY,
  }),
  cat({
    id: "coworker_night",
    name: "Coworker Night",
    group: "social",
    description: "Work-appropriate, conversation-friendly.",
    defaultVibes: ["classy", "social"],
    venueTypes: ["wine_bar", "restaurant", "rooftop"],
    conversationFriendly: true,
    safetyFilters: [...CONVERSATION_FILTERS, ...FAMILY_SAFE_FILTERS],
    avoidVenueTypes: AVOID_PARTY,
  }),
  cat({
    id: "best_friends_night",
    name: "Best Friends Night",
    group: "social",
    description: "Inside-joke energy.",
    defaultVibes: ["turn_up", "instagrammy"],
    venueTypes: ["cocktail_bar", "karaoke", "rooftop"],
    idealGroupSize: [2, 6],
  }),
  cat({
    id: "reunion_night",
    name: "Reunion Night",
    group: "social",
    description: "Catch up over a long table.",
    defaultVibes: ["classy", "social"],
    venueTypes: ["restaurant", "private_room", "brewery"],
    idealGroupSize: [4, 16],
    conversationFriendly: true,
  }),
  cat({
    id: "birthday_night",
    name: "Birthday Night",
    group: "social",
    description: "Birthday energy — dinner → drinks → dance.",
    defaultVibes: ["turn_up", "instagrammy"],
    venueTypes: ["restaurant", "lounge", "rooftop", "dance_club"],
    idealGroupSize: [4, 12],
    nightlifeIntensity: "high",
  }),
  cat({
    id: "anniversary_night",
    name: "Anniversary Night",
    group: "social",
    description: "Romantic, memorable, unhurried.",
    defaultVibes: ["romantic", "soft_life"],
    venueTypes: ["fine_dining", "tasting_menu", "rooftop"],
    idealGroupSize: [2, 2],
    budgetTiers: [3, 4],
  }),
  cat({
    id: "bachelorette",
    name: "Bachelorette Party",
    group: "social",
    description: "Bride squad turn-up.",
    defaultVibes: ["turn_up", "instagrammy", "wild"],
    venueTypes: ["brunch_spot", "rooftop", "dance_club", "yacht", "spa"],
    idealGroupSize: [4, 16],
    familySafe: false,
    adultOnly: true,
    nightlifeIntensity: "high",
    safetyFilters: ADULT_ONLY_FILTERS,
  }),
  cat({
    id: "bachelor",
    name: "Bachelor Party",
    group: "social",
    description: "Last-night-out energy.",
    defaultVibes: ["wild", "turn_up", "yacht"],
    venueTypes: ["steakhouse", "whiskey_bar", "yacht", "casino", "dance_club"],
    idealGroupSize: [4, 16],
    familySafe: false,
    adultOnly: true,
    nightlifeIntensity: "high",
    safetyFilters: ADULT_ONLY_FILTERS,
  }),
  cat({
    id: "graduation_night",
    name: "Graduation Night",
    group: "social",
    description: "Toast the milestone.",
    defaultVibes: ["turn_up", "classy"],
    venueTypes: ["restaurant", "rooftop", "lounge"],
    idealGroupSize: [4, 20],
  }),
  cat({
    id: "going_away",
    name: "Going-Away Night",
    group: "social",
    description: "Send-off with greatest hits.",
    defaultVibes: ["social", "turn_up"],
    venueTypes: ["restaurant", "bar", "rooftop"],
  }),
  cat({
    id: "welcome_back",
    name: "Welcome-Back Night",
    group: "social",
    description: "Reentry party.",
    defaultVibes: ["social", "chill"],
    venueTypes: ["restaurant", "bar", "rooftop"],
  }),
  cat({
    id: "meet_parents",
    name: "Meet-the-Parents Night",
    group: "social",
    description: "Make a first impression.",
    defaultVibes: ["classy", "soft_life"],
    venueTypes: ["fine_dining", "wine_bar"],
    conversationFriendly: true,
    nightlifeIntensity: "low",
    safetyFilters: [...CONVERSATION_FILTERS, ...FAMILY_SAFE_FILTERS],
    avoidVenueTypes: AVOID_PARTY,
  }),
  cat({
    id: "new_friends",
    name: "New Friends Night",
    group: "social",
    description: "Easy icebreaker venues.",
    defaultVibes: ["social", "chill"],
    venueTypes: ["brewery", "arcade_bar", "karaoke", "bowling"],
    conversationFriendly: true,
  }),

  // 2. NIGHTLIFE ──────────────────────────────────────────────────
  cat({
    id: "turn_up",
    name: "Turn-Up Night",
    group: "nightlife",
    description: "High-energy bars + dance floor.",
    defaultVibes: ["turn_up", "wild"],
    venueTypes: ["cocktail_bar", "dance_club", "rooftop"],
    familySafe: false,
    adultOnly: true,
    nightlifeIntensity: "high",
    safetyFilters: ADULT_ONLY_FILTERS,
  }),
  cat({
    id: "club_night",
    name: "Club Night",
    group: "nightlife",
    description: "Main-room DJs, late.",
    defaultVibes: ["turn_up", "wild"],
    venueTypes: ["dance_club", "lounge"],
    familySafe: false,
    adultOnly: true,
    nightlifeIntensity: "high",
    safetyFilters: ADULT_ONLY_FILTERS,
    suggestedSlots: ["Pre", "Main"],
  }),
  cat({
    id: "lounge_night",
    name: "Lounge Night",
    group: "nightlife",
    description: "Lower-BPM, dress to vibe.",
    defaultVibes: ["classy", "soft_life"],
    venueTypes: ["lounge", "hotel_bar"],
    familySafe: false,
    adultOnly: true,
    nightlifeIntensity: "medium",
    safetyFilters: ADULT_ONLY_FILTERS,
  }),
  cat({
    id: "rooftop_night",
    name: "Rooftop Night",
    group: "nightlife",
    description: "Skyline + cocktails.",
    defaultVibes: ["instagrammy", "classy"],
    venueTypes: ["rooftop", "hotel_bar"],
    waterfront: "optional",
    weatherSensitive: true,
    familySafe: false,
    adultOnly: true,
    safetyFilters: ADULT_ONLY_FILTERS,
  }),
  cat({
    id: "bar_hop",
    name: "Bar Hop",
    group: "nightlife",
    description: "3+ bars in a walkable district.",
    defaultVibes: ["turn_up", "social"],
    venueTypes: ["dive_bar", "cocktail_bar", "beer_bar"],
    familySafe: false,
    adultOnly: true,
    nightlifeIntensity: "high",
    safetyFilters: ADULT_ONLY_FILTERS,
  }),
  cat({
    id: "dive_bar_crawl",
    name: "Dive Bar Crawl",
    group: "nightlife",
    description: "Cheap shots, jukebox, no pretense.",
    defaultVibes: ["wild", "social"],
    venueTypes: ["dive_bar"],
    familySafe: false,
    adultOnly: true,
    nightlifeIntensity: "high",
    safetyFilters: ADULT_ONLY_FILTERS,
    budgetTiers: [1, 2],
  }),
  cat({
    id: "day_party",
    name: "Day Party",
    group: "nightlife",
    description: "Sun + speakers + drinks.",
    defaultVibes: ["day_party", "instagrammy"],
    venueTypes: ["rooftop", "pool_club", "outdoor_bar"],
    weatherSensitive: true,
    familySafe: false,
    adultOnly: true,
    nightlifeIntensity: "high",
    safetyFilters: ADULT_ONLY_FILTERS,
  }),
  cat({
    id: "pool_party",
    name: "Pool Party",
    group: "nightlife",
    description: "Cabanas + DJ.",
    defaultVibes: ["day_party", "wild"],
    venueTypes: ["pool_club", "hotel_pool"],
    weatherSensitive: true,
    seasonal: true,
    familySafe: false,
    adultOnly: true,
    safetyFilters: ADULT_ONLY_FILTERS,
  }),
  cat({
    id: "yacht_day_party",
    name: "Yacht Day Party",
    group: "nightlife",
    description: "Boat + crew + cocktails.",
    defaultVibes: ["yacht", "wild", "instagrammy"],
    venueTypes: ["yacht_charter"],
    waterfront: "required",
    weatherSensitive: true,
    familySafe: false,
    adultOnly: true,
    budgetTiers: [3, 4],
    safetyFilters: ADULT_ONLY_FILTERS,
  }),
  cat({
    id: "sunset_yacht",
    name: "Sunset Yacht Cruise",
    group: "nightlife",
    description: "Slower, golden-hour boat ride.",
    defaultVibes: ["romantic", "soft_life"],
    venueTypes: ["yacht_charter", "dinner_cruise"],
    waterfront: "required",
    weatherSensitive: true,
    budgetTiers: [3, 4],
  }),
  cat({
    id: "casino_night",
    name: "Casino Night",
    group: "nightlife",
    description: "Tables + show + late dinner.",
    defaultVibes: ["wild", "classy"],
    venueTypes: ["casino", "steakhouse"],
    familySafe: false,
    adultOnly: true,
    nightlifeIntensity: "high",
    safetyFilters: [...ADULT_ONLY_FILTERS, "responsible_gambling_copy"],
    budgetTiers: [2, 3, 4],
  }),
  cat({
    id: "strip_club_night",
    name: "Strip Club Night",
    group: "nightlife",
    description: "Adult entertainment.",
    defaultVibes: ["wild"],
    venueTypes: ["strip_club"],
    familySafe: false,
    adultOnly: true,
    nightlifeIntensity: "high",
    safetyFilters: [...ADULT_ONLY_FILTERS, "explicit_opt_in_required"],
  }),
  cat({
    id: "bottle_service",
    name: "Bottle Service Night",
    group: "nightlife",
    description: "Table + bottles + section.",
    defaultVibes: ["wild", "instagrammy"],
    venueTypes: ["dance_club", "lounge"],
    familySafe: false,
    adultOnly: true,
    budgetTiers: [3, 4],
    safetyFilters: ADULT_ONLY_FILTERS,
  }),
  cat({
    id: "after_hours",
    name: "After-Hours Night",
    group: "nightlife",
    description: "Post-2am rooms.",
    defaultVibes: ["wild", "late_night"],
    venueTypes: ["after_hours_club", "underground"],
    familySafe: false,
    adultOnly: true,
    nightlifeIntensity: "high",
    safetyFilters: ADULT_ONLY_FILTERS,
  }),
  cat({
    id: "latin_night",
    name: "Latin Night",
    group: "nightlife",
    description: "Salsa, bachata, reggaetón.",
    defaultVibes: ["turn_up", "live_music"],
    venueTypes: ["latin_club", "salsa_bar"],
    familySafe: false,
    adultOnly: true,
    safetyFilters: ADULT_ONLY_FILTERS,
  }),
  cat({
    id: "edm_night",
    name: "EDM Night",
    group: "nightlife",
    description: "Open format DJs.",
    defaultVibes: ["wild", "turn_up"],
    venueTypes: ["dance_club", "warehouse"],
    familySafe: false,
    adultOnly: true,
    safetyFilters: ADULT_ONLY_FILTERS,
  }),
  cat({
    id: "hiphop_night",
    name: "Hip-Hop Night",
    group: "nightlife",
    description: "Bottle-section vibe or open dance floor.",
    defaultVibes: ["turn_up", "wild"],
    venueTypes: ["dance_club", "lounge"],
    familySafe: false,
    adultOnly: true,
    safetyFilters: ADULT_ONLY_FILTERS,
  }),
  cat({
    id: "karaoke_night",
    name: "Karaoke Night",
    group: "nightlife",
    description: "Private rooms or main stage.",
    defaultVibes: ["social", "wild"],
    venueTypes: ["karaoke", "kbbq_karaoke"],
    idealGroupSize: [4, 12],
  }),

  // 3. CHILL ──────────────────────────────────────────────────────
  cat({
    id: "chill_night",
    name: "Chill Night",
    group: "chill",
    description: "Low-key, no pressure.",
    defaultVibes: ["chill", "soft_life"],
    venueTypes: ["wine_bar", "cafe", "cozy_lounge"],
    nightlifeIntensity: "low",
  }),
  cat({
    id: "wine_night",
    name: "Wine Night",
    group: "chill",
    description: "Bottles + small plates.",
    defaultVibes: ["soft_life", "classy"],
    venueTypes: ["wine_bar", "wine_shop"],
    conversationFriendly: true,
  }),
  cat({
    id: "brewery_night",
    name: "Brewery Night",
    group: "chill",
    description: "Flights + games + food truck.",
    defaultVibes: ["chill", "social"],
    venueTypes: ["brewery", "beer_garden"],
    idealGroupSize: [2, 10],
  }),
  cat({
    id: "coffee_night",
    name: "Coffee Night",
    group: "chill",
    description: "Late-open specialty coffee.",
    defaultVibes: ["chill"],
    venueTypes: ["specialty_coffee", "cafe"],
    nightlifeIntensity: "low",
    budgetTiers: [1, 2],
  }),
  cat({
    id: "dessert_night",
    name: "Dessert Night",
    group: "chill",
    description: "Patisseries + ice cream.",
    defaultVibes: ["soft_life", "chill"],
    venueTypes: ["patisserie", "ice_cream", "gelato"],
    familySafe: true,
    nightlifeIntensity: "low",
    budgetTiers: [1, 2],
  }),
  cat({
    id: "picnic_night",
    name: "Picnic Night",
    group: "chill",
    description: "Park or waterfront blanket.",
    defaultVibes: ["soft_life", "romantic"],
    venueTypes: ["park", "waterfront"],
    waterfront: "preferred",
    weatherSensitive: true,
    seasonal: true,
    familySafe: true,
    budgetTiers: [1, 2],
  }),
  cat({
    id: "movie_night",
    name: "Movie Night",
    group: "chill",
    description: "Boutique cinema or drive-in.",
    defaultVibes: ["chill"],
    venueTypes: ["cinema", "drive_in", "alamo_drafthouse"],
    familySafe: true,
    nightlifeIntensity: "low",
  }),
  cat({
    id: "board_game_night",
    name: "Board Game Night",
    group: "chill",
    description: "Cafe-style game nights.",
    defaultVibes: ["chill", "social"],
    venueTypes: ["board_game_cafe"],
    familySafe: true,
    nightlifeIntensity: "low",
  }),
  cat({
    id: "scenic_walk",
    name: "Scenic Walk Night",
    group: "chill",
    description: "Stroll + dessert.",
    defaultVibes: ["romantic", "chill"],
    venueTypes: ["waterfront", "park", "boardwalk"],
    waterfront: "preferred",
    weatherSensitive: true,
    familySafe: true,
    nightlifeIntensity: "low",
    budgetTiers: [1, 2],
  }),
  cat({
    id: "sunset_night",
    name: "Sunset Night",
    group: "chill",
    description: "Catch the sky from somewhere good.",
    defaultVibes: ["romantic", "instagrammy"],
    venueTypes: ["rooftop", "overlook", "waterfront"],
    waterfront: "preferred",
    weatherSensitive: true,
  }),
  cat({
    id: "waterfront_chill",
    name: "Waterfront Chill Night",
    group: "chill",
    description: "Dockside everything.",
    defaultVibes: ["soft_life", "chill"],
    venueTypes: ["waterfront_bar", "marina_restaurant"],
    waterfront: "required",
    weatherSensitive: true,
  }),
  cat({
    id: "bookstore_night",
    name: "Bookstore Night",
    group: "chill",
    description: "Browse + cafe.",
    defaultVibes: ["chill"],
    venueTypes: ["bookstore", "cafe"],
    familySafe: true,
    nightlifeIntensity: "low",
    budgetTiers: [1, 2],
  }),
  cat({
    id: "cozy_night",
    name: "Cozy Night",
    group: "chill",
    description: "Fireplaces, leather booths.",
    defaultVibes: ["romantic", "soft_life"],
    venueTypes: ["whiskey_bar", "cozy_restaurant", "speakeasy"],
    conversationFriendly: true,
  }),

  // 4. FOOD ───────────────────────────────────────────────────────
  cat({
    id: "dinner_night",
    name: "Dinner Night",
    group: "food",
    description: "Sit-down dinner anchor.",
    defaultVibes: ["classy", "social"],
    venueTypes: ["restaurant"],
    conversationFriendly: true,
  }),
  cat({
    id: "tapas_night",
    name: "Tapas Night",
    group: "food",
    description: "Small plates, shared.",
    defaultVibes: ["social", "classy"],
    venueTypes: ["tapas_bar", "spanish_restaurant"],
  }),
  cat({
    id: "brunch",
    name: "Brunch",
    group: "food",
    description: "Late breakfast + drinks.",
    defaultVibes: ["soft_life", "instagrammy"],
    venueTypes: ["brunch_spot", "bistro"],
    familySafe: true,
  }),
  cat({
    id: "brunch_baddies",
    name: "Brunch Baddies",
    group: "food",
    description:
      "Cute fits, mimosas, rooftop energy, aesthetic plates, IG photo walls, daytime music.",
    defaultVibes: ["brunch_baddies", "instagrammy", "soft_life", "mimosas", "rooftop"],
    venueTypes: [
      "rooftop_brunch",
      "brunch_spot",
      "waterfront_brunch",
      "aesthetic_cafe",
      "dessert_cafe",
      "flower_wall",
      "mural",
      "boutique",
      "rooftop_lounge_day",
      "day_party",
    ],
    activityTypes: [
      "rooftop_brunch",
      "waterfront_brunch",
      "bottomless_mimosas",
      "brunch_photo_wall",
      "flower_wall_stop",
      "cute_coffee_shop",
      "boutique_shopping",
      "rooftop_lounge_day",
      "day_party_optional",
      "dessert_cafe_pretty",
      "mural_photo_walk",
    ],
    idealGroupSize: [2, 10],
    budgetTiers: [1, 2, 3],
    waterfront: "preferred",
    familySafe: false,
    adultOnly: false,
    nightlifeIntensity: "low",
    conversationFriendly: true,
    avoidVenueTypes: ["dance_club", "dive_bar", "after_hours", "strip_club"],
    suggestedSlots: ["Brunch", "Photo", "Lounge", "Day Party (optional)"],
  }),
    name: "Breakfast Outing",
    group: "food",
    description: "Early-bird favorites.",
    defaultVibes: ["chill"],
    venueTypes: ["breakfast_spot", "diner", "cafe"],
    familySafe: true,
    nightlifeIntensity: "low",
    budgetTiers: [1, 2],
  }),
  cat({
    id: "food_truck",
    name: "Food Truck Night",
    group: "food",
    description: "Truck park or pod.",
    defaultVibes: ["social", "chill"],
    venueTypes: ["food_truck_park"],
    familySafe: true,
    weatherSensitive: true,
    budgetTiers: [1, 2],
  }),
  cat({
    id: "fine_dining",
    name: "Fine Dining Night",
    group: "food",
    description: "Special-occasion menu.",
    defaultVibes: ["classy", "romantic"],
    venueTypes: ["fine_dining"],
    budgetTiers: [3, 4],
    conversationFriendly: true,
  }),
  cat({
    id: "tasting_menu",
    name: "Tasting Menu Night",
    group: "food",
    description: "Chef's-counter experience.",
    defaultVibes: ["classy", "instagrammy"],
    venueTypes: ["tasting_menu", "omakase"],
    budgetTiers: [3, 4],
  }),
  cat({
    id: "seafood_night",
    name: "Seafood Night",
    group: "food",
    description: "Oysters, crudo, whole fish.",
    defaultVibes: ["classy"],
    venueTypes: ["seafood_restaurant", "oyster_bar"],
    waterfront: "preferred",
  }),
  cat({
    id: "steakhouse",
    name: "Steakhouse Night",
    group: "food",
    description: "Steak + martini + cigar maybe.",
    defaultVibes: ["classy", "grown_man"],
    venueTypes: ["steakhouse"],
    budgetTiers: [3, 4],
  }),
  cat({
    id: "sushi_night",
    name: "Sushi Night",
    group: "food",
    description: "Omakase or rolls.",
    defaultVibes: ["classy"],
    venueTypes: ["sushi", "omakase"],
  }),
  cat({
    id: "pizza_night",
    name: "Pizza Night",
    group: "food",
    description: "Slices or sit-down pies.",
    defaultVibes: ["chill", "social"],
    venueTypes: ["pizzeria"],
    familySafe: true,
    budgetTiers: [1, 2],
  }),
  cat({
    id: "bbq_night",
    name: "BBQ Night",
    group: "food",
    description: "Smokehouse + sides.",
    defaultVibes: ["chill", "social"],
    venueTypes: ["bbq", "smokehouse"],
    familySafe: true,
  }),
  cat({
    id: "local_eats",
    name: "Local Eats Night",
    group: "food",
    description: "Neighborhood favorites.",
    defaultVibes: ["local", "chill"],
    venueTypes: ["local_restaurant", "hole_in_the_wall"],
    familySafe: true,
  }),
  cat({
    id: "farmers_market_am",
    name: "Farmers Market Morning",
    group: "food",
    description: "Market + breakfast.",
    defaultVibes: ["chill", "local"],
    venueTypes: ["farmers_market", "cafe"],
    familySafe: true,
    weatherSensitive: true,
    seasonal: true,
    nightlifeIntensity: "low",
    budgetTiers: [1, 2],
  }),
  cat({
    id: "coffee_pastry_am",
    name: "Coffee + Pastry Morning",
    group: "food",
    description: "Cafe crawl.",
    defaultVibes: ["chill", "soft_life"],
    venueTypes: ["specialty_coffee", "patisserie"],
    familySafe: true,
    nightlifeIntensity: "low",
    budgetTiers: [1, 2],
  }),

  // 5. CULTURE ────────────────────────────────────────────────────
  cat({
    id: "museum_night",
    name: "Museum Night",
    group: "culture",
    description: "After-dark museums or galleries.",
    defaultVibes: ["classy", "chill"],
    venueTypes: ["museum"],
    familySafe: true,
    nightlifeIntensity: "low",
  }),
  cat({
    id: "art_district",
    name: "Art District Night",
    group: "culture",
    description: "Walkable art + dinner.",
    defaultVibes: ["instagrammy", "classy"],
    venueTypes: ["gallery_district", "restaurant"],
    familySafe: true,
  }),
  cat({
    id: "gallery_night",
    name: "Gallery Night",
    group: "culture",
    description: "Openings + wine.",
    defaultVibes: ["classy", "instagrammy"],
    venueTypes: ["gallery", "wine_bar"],
  }),
  cat({
    id: "theater_night",
    name: "Theater Night",
    group: "culture",
    description: "Play, musical, or opera.",
    defaultVibes: ["classy", "romantic"],
    venueTypes: ["theater"],
    familySafe: true,
    budgetTiers: [2, 3, 4],
  }),
  cat({
    id: "comedy_show",
    name: "Comedy Show Night",
    group: "culture",
    description: "Standup + late-night bite.",
    defaultVibes: ["social", "wild"],
    venueTypes: ["comedy_club"],
    familySafe: false,
    adultOnly: true,
    safetyFilters: ADULT_ONLY_FILTERS,
  }),
  cat({
    id: "jazz_night",
    name: "Jazz Night",
    group: "culture",
    description: "Live jazz, cocktails, low light.",
    defaultVibes: ["classy", "romantic", "live_music"],
    venueTypes: ["jazz_club"],
    conversationFriendly: true,
  }),
  cat({
    id: "live_music_night",
    name: "Live Music Night",
    group: "culture",
    description: "Local band, indie venue.",
    defaultVibes: ["live_music", "social"],
    venueTypes: ["live_music_venue", "concert_hall"],
  }),
  cat({
    id: "poetry_night",
    name: "Poetry Night",
    group: "culture",
    description: "Open mic / spoken word.",
    defaultVibes: ["classy", "chill"],
    venueTypes: ["cafe", "bookstore"],
  }),
  cat({
    id: "cultural_festival",
    name: "Cultural Festival Night",
    group: "culture",
    description: "Block festivals + food vendors.",
    defaultVibes: ["social", "local"],
    venueTypes: ["festival"],
    familySafe: true,
    weatherSensitive: true,
    seasonal: true,
  }),
  cat({
    id: "historical_tour",
    name: "Historical Tour",
    group: "culture",
    description: "Guided history walks.",
    defaultVibes: ["classy", "local"],
    venueTypes: ["historic_site", "tour_company"],
    familySafe: true,
    nightlifeIntensity: "low",
  }),
  cat({
    id: "architecture_tour",
    name: "Architecture Tour",
    group: "culture",
    description: "Boat or walking.",
    defaultVibes: ["classy", "instagrammy"],
    venueTypes: ["tour_company"],
    familySafe: true,
    nightlifeIntensity: "low",
  }),
  cat({
    id: "local_landmarks",
    name: "Local Landmarks Tour",
    group: "culture",
    description: "Hit the iconic stops.",
    defaultVibes: ["instagrammy", "local"],
    venueTypes: ["landmark"],
    familySafe: true,
    weatherSensitive: true,
    nightlifeIntensity: "low",
  }),
  cat({
    id: "sightseeing_day",
    name: "Sightseeing Day",
    group: "culture",
    description: "Full-day must-see itinerary.",
    defaultVibes: ["instagrammy", "local"],
    venueTypes: ["landmark", "viewpoint", "museum"],
    familySafe: true,
    weatherSensitive: true,
    nightlifeIntensity: "low",
  }),

  // 6. ADVENTURE ──────────────────────────────────────────────────
  cat({
    id: "adventure_night",
    name: "Adventure Night",
    group: "adventure",
    description: "Active before dinner.",
    defaultVibes: ["adventurous", "social"],
    venueTypes: ["activity"],
    weatherSensitive: true,
  }),
  cat({
    id: "hiking_trip",
    name: "Hiking Trip",
    group: "adventure",
    description: "Trail + lookout + post-hike beers.",
    defaultVibes: ["adventurous", "local"],
    venueTypes: ["trail", "brewery"],
    familySafe: true,
    weatherSensitive: true,
    nightlifeIntensity: "low",
  }),
  cat({
    id: "nature_walk",
    name: "Nature Walk",
    group: "adventure",
    description: "Easy paths + photo stops.",
    defaultVibes: ["chill", "instagrammy"],
    venueTypes: ["park", "nature_preserve"],
    familySafe: true,
    weatherSensitive: true,
    nightlifeIntensity: "low",
    budgetTiers: [1, 2],
  }),
  cat({
    id: "botanical_garden",
    name: "Botanical Garden Visit",
    group: "adventure",
    description: "Gardens + cafe.",
    defaultVibes: ["soft_life", "instagrammy"],
    venueTypes: ["botanical_garden"],
    familySafe: true,
    weatherSensitive: true,
    nightlifeIntensity: "low",
    budgetTiers: [1, 2],
  }),
  cat({
    id: "zoo_aquarium",
    name: "Zoo or Aquarium",
    group: "adventure",
    description: "Daytime family-friendly.",
    defaultVibes: ["family_friendly", "instagrammy"],
    venueTypes: ["zoo", "aquarium"],
    familySafe: true,
    nightlifeIntensity: "low",
  }),
  cat({
    id: "jet_ski",
    name: "Jet Ski Day",
    group: "adventure",
    description: "Open-water rentals.",
    defaultVibes: ["adventurous", "day_party"],
    venueTypes: ["jet_ski_rental"],
    waterfront: "required",
    weatherSensitive: true,
    seasonal: true,
    budgetTiers: [2, 3],
  }),
  cat({
    id: "boat_cruise",
    name: "Boat Cruise",
    group: "adventure",
    description: "Skyline or scenic boat ride.",
    defaultVibes: ["instagrammy", "soft_life"],
    venueTypes: ["cruise"],
    waterfront: "required",
    weatherSensitive: true,
    familySafe: true,
  }),
  cat({
    id: "kayak",
    name: "Kayak / Paddleboard",
    group: "adventure",
    description: "Calm-water paddle.",
    defaultVibes: ["adventurous", "chill"],
    venueTypes: ["paddlesports_rental"],
    waterfront: "required",
    weatherSensitive: true,
    familySafe: true,
    nightlifeIntensity: "low",
    budgetTiers: [1, 2],
  }),
  cat({
    id: "zipline",
    name: "Zipline Adventure",
    group: "adventure",
    description: "Canopy course.",
    defaultVibes: ["adventurous"],
    venueTypes: ["zipline_park"],
    weatherSensitive: true,
    familySafe: true,
  }),
  cat({
    id: "gokart",
    name: "Go-Kart Racing",
    group: "adventure",
    description: "Indoor or outdoor karts.",
    defaultVibes: ["adventurous", "social"],
    venueTypes: ["gokart"],
    familySafe: true,
  }),
  cat({
    id: "f1_sim",
    name: "F1 Racing Simulator",
    group: "adventure",
    description: "Sim racing + beers.",
    defaultVibes: ["adventurous", "social"],
    venueTypes: ["racing_sim_lounge"],
  }),
  cat({
    id: "atv",
    name: "ATV Riding",
    group: "adventure",
    description: "Trail ATV tours.",
    defaultVibes: ["adventurous"],
    venueTypes: ["atv_tour"],
    weatherSensitive: true,
    seasonal: true,
  }),
  cat({
    id: "horseback",
    name: "Horseback Riding",
    group: "adventure",
    description: "Trail or beach rides.",
    defaultVibes: ["adventurous", "romantic"],
    venueTypes: ["stable"],
    familySafe: true,
    weatherSensitive: true,
  }),
  cat({
    id: "rock_climbing",
    name: "Rock Climbing",
    group: "adventure",
    description: "Indoor or outdoor wall.",
    defaultVibes: ["adventurous"],
    venueTypes: ["climbing_gym"],
    familySafe: true,
  }),
  cat({
    id: "bike_tour",
    name: "Bike Tour",
    group: "adventure",
    description: "Group bike route.",
    defaultVibes: ["local", "adventurous"],
    venueTypes: ["bike_tour"],
    familySafe: true,
    weatherSensitive: true,
    nightlifeIntensity: "low",
  }),
  cat({
    id: "beach_day",
    name: "Beach Day",
    group: "adventure",
    description: "Beach + lunch + drinks.",
    defaultVibes: ["day_party", "soft_life"],
    venueTypes: ["beach", "beach_bar"],
    waterfront: "required",
    weatherSensitive: true,
    seasonal: true,
    familySafe: true,
  }),
  cat({
    id: "ski_day",
    name: "Ski / Snowboard Day",
    group: "adventure",
    description: "Mountain day + apres.",
    defaultVibes: ["adventurous"],
    venueTypes: ["ski_resort"],
    weatherSensitive: true,
    seasonal: true,
    budgetTiers: [3, 4],
  }),

  // 7. ACTION ─────────────────────────────────────────────────────
  cat({
    id: "gun_range",
    name: "Gun Range",
    group: "action",
    description: "Indoor pistol/rifle session.",
    defaultVibes: ["adventurous", "grown_man"],
    venueTypes: ["gun_range"],
    familySafe: false,
    adultOnly: true,
    nightlifeIntensity: "low",
    safetyFilters: [...ADULT_ONLY_FILTERS, "no_alcohol_before_activity", "valid_id_required"],
    avoidVenueTypes: ["bar_before_range"],
  }),
  cat({
    id: "archery",
    name: "Archery Range",
    group: "action",
    description: "Targets + coaching.",
    defaultVibes: ["adventurous"],
    venueTypes: ["archery_range"],
    familySafe: true,
    nightlifeIntensity: "low",
  }),
  cat({
    id: "axe_throwing",
    name: "Axe Throwing",
    group: "action",
    description: "Throw + beers.",
    defaultVibes: ["adventurous", "social"],
    venueTypes: ["axe_throwing"],
  }),
  cat({
    id: "rage_room",
    name: "Rage Room",
    group: "action",
    description: "Smash session.",
    defaultVibes: ["wild", "adventurous"],
    venueTypes: ["rage_room"],
    familySafe: false,
    adultOnly: true,
    safetyFilters: ADULT_ONLY_FILTERS,
  }),
  cat({
    id: "escape_room",
    name: "Escape Room",
    group: "action",
    description: "Puzzle room + drinks after.",
    defaultVibes: ["social", "adventurous"],
    venueTypes: ["escape_room"],
    familySafe: true,
  }),
  cat({
    id: "laser_tag",
    name: "Laser Tag",
    group: "action",
    description: "Arena laser tag.",
    defaultVibes: ["social", "adventurous"],
    venueTypes: ["laser_tag"],
    familySafe: true,
  }),
  cat({
    id: "paintball",
    name: "Paintball",
    group: "action",
    description: "Field play.",
    defaultVibes: ["adventurous", "wild"],
    venueTypes: ["paintball"],
    weatherSensitive: true,
  }),
  cat({
    id: "trampoline_park",
    name: "Trampoline Park",
    group: "action",
    description: "Jump session.",
    defaultVibes: ["family_friendly", "adventurous"],
    venueTypes: ["trampoline_park"],
    familySafe: true,
  }),
  cat({
    id: "vr_arena",
    name: "VR Arena",
    group: "action",
    description: "Free-roam VR.",
    defaultVibes: ["adventurous", "social"],
    venueTypes: ["vr_arena"],
    familySafe: true,
  }),
  cat({
    id: "arcade_night",
    name: "Arcade Night",
    group: "action",
    description: "Pinball, classics, prize tickets.",
    defaultVibes: ["social", "instagrammy"],
    venueTypes: ["arcade", "barcade"],
    familySafe: true,
  }),
  cat({
    id: "bowling_night",
    name: "Bowling Night",
    group: "action",
    description: "Lanes + bites.",
    defaultVibes: ["social", "chill"],
    venueTypes: ["bowling"],
    familySafe: true,
  }),
  cat({
    id: "mini_golf",
    name: "Mini Golf",
    group: "action",
    description: "Themed mini golf.",
    defaultVibes: ["family_friendly", "social"],
    venueTypes: ["mini_golf"],
    familySafe: true,
    weatherSensitive: true,
  }),
  cat({
    id: "sports_game",
    name: "Sports Game Night",
    group: "action",
    description: "Live game + pre/post bar.",
    defaultVibes: ["social", "turn_up"],
    venueTypes: ["arena", "sports_bar"],
    familySafe: true,
  }),

  // 8. LUXURY ─────────────────────────────────────────────────────
  cat({
    id: "soft_life_night",
    name: "Soft Life Night",
    group: "luxury",
    description: "Slow, beautiful, easy.",
    defaultVibes: ["soft_life", "classy"],
    venueTypes: ["spa", "fine_dining", "rooftop"],
    budgetTiers: [3, 4],
  }),
  cat({
    id: "luxury_dinner",
    name: "Luxury Dinner",
    group: "luxury",
    description: "Best table in town.",
    defaultVibes: ["classy", "romantic"],
    venueTypes: ["fine_dining", "tasting_menu"],
    budgetTiers: [4],
  }),
  cat({
    id: "yacht_sunset",
    name: "Yacht Sunset",
    group: "luxury",
    description: "Charter at golden hour.",
    defaultVibes: ["soft_life", "romantic"],
    venueTypes: ["yacht_charter"],
    waterfront: "required",
    weatherSensitive: true,
    budgetTiers: [3, 4],
  }),
  cat({
    id: "spa_day",
    name: "Spa Day",
    group: "luxury",
    description: "Massage + sauna + lounge.",
    defaultVibes: ["soft_life", "wellness"],
    venueTypes: ["spa"],
    nightlifeIntensity: "low",
    budgetTiers: [2, 3, 4],
  }),
  cat({
    id: "massage_day",
    name: "Massage Day",
    group: "luxury",
    description: "Deep tissue or couples massage.",
    defaultVibes: ["soft_life"],
    venueTypes: ["spa", "massage_studio"],
    nightlifeIntensity: "low",
  }),
  cat({
    id: "facial_day",
    name: "Facial Day",
    group: "luxury",
    description: "Skincare appointment + lunch.",
    defaultVibes: ["soft_life"],
    venueTypes: ["spa", "skincare_studio"],
    nightlifeIntensity: "low",
  }),
  cat({
    id: "nail_date",
    name: "Nail Date",
    group: "luxury",
    description: "Manis + champagne.",
    defaultVibes: ["soft_life", "instagrammy"],
    venueTypes: ["nail_salon"],
    nightlifeIntensity: "low",
    budgetTiers: [1, 2],
  }),
  cat({
    id: "chauffeur_night",
    name: "Chauffeur Night",
    group: "luxury",
    description: "Black-car + multi-stop.",
    defaultVibes: ["classy", "soft_life"],
    venueTypes: ["car_service", "fine_dining"],
    budgetTiers: [3, 4],
  }),
  cat({
    id: "vip_night",
    name: "VIP Night",
    group: "luxury",
    description: "Reservation + table + queue skip.",
    defaultVibes: ["classy", "wild"],
    venueTypes: ["lounge", "dance_club"],
    familySafe: false,
    adultOnly: true,
    budgetTiers: [3, 4],
    safetyFilters: ADULT_ONLY_FILTERS,
  }),
  cat({
    id: "penthouse_night",
    name: "Penthouse Night",
    group: "luxury",
    description: "Private rental + chef.",
    defaultVibes: ["classy", "soft_life"],
    venueTypes: ["penthouse_rental", "private_chef"],
    budgetTiers: [4],
    adultOnly: true,
  }),
  cat({
    id: "luxury_shopping",
    name: "Luxury Shopping",
    group: "luxury",
    description: "Designer + champagne lunch.",
    defaultVibes: ["classy", "soft_life"],
    venueTypes: ["luxury_mall", "designer_boutique"],
    nightlifeIntensity: "low",
    budgetTiers: [3, 4],
  }),
  cat({
    id: "designer_tour",
    name: "Designer Boutique Tour",
    group: "luxury",
    description: "Best of the design district.",
    defaultVibes: ["instagrammy", "classy"],
    venueTypes: ["designer_boutique"],
    nightlifeIntensity: "low",
    budgetTiers: [3, 4],
  }),

  // 9. WELLNESS ───────────────────────────────────────────────────
  cat({
    id: "spa_sauna",
    name: "Spa & Sauna",
    group: "wellness",
    description: "Korean-style or Nordic spa.",
    defaultVibes: ["soft_life", "wellness"],
    venueTypes: ["spa", "sauna"],
    nightlifeIntensity: "low",
  }),
  cat({
    id: "massage",
    name: "Massage",
    group: "wellness",
    description: "Standalone massage appointment.",
    defaultVibes: ["soft_life"],
    venueTypes: ["massage_studio"],
    nightlifeIntensity: "low",
  }),
  cat({
    id: "facial",
    name: "Facial",
    group: "wellness",
    description: "Skincare studio session.",
    defaultVibes: ["soft_life"],
    venueTypes: ["skincare_studio"],
    nightlifeIntensity: "low",
  }),
  cat({
    id: "nails",
    name: "Nail Appointment",
    group: "wellness",
    description: "Mani/pedi.",
    defaultVibes: ["soft_life"],
    venueTypes: ["nail_salon"],
    nightlifeIntensity: "low",
    budgetTiers: [1, 2],
  }),
  cat({
    id: "yoga",
    name: "Yoga Class",
    group: "wellness",
    description: "Vinyasa, hot, or restorative.",
    defaultVibes: ["wellness", "chill"],
    venueTypes: ["yoga_studio"],
    familySafe: true,
    nightlifeIntensity: "low",
    budgetTiers: [1, 2],
  }),
  cat({
    id: "meditation",
    name: "Meditation Class",
    group: "wellness",
    description: "Guided session.",
    defaultVibes: ["wellness", "chill"],
    venueTypes: ["meditation_studio"],
    nightlifeIntensity: "low",
    budgetTiers: [1, 2],
  }),
  cat({
    id: "sound_bath",
    name: "Sound Bath",
    group: "wellness",
    description: "Sound healing.",
    defaultVibes: ["wellness", "soft_life"],
    venueTypes: ["sound_bath_studio"],
    nightlifeIntensity: "low",
  }),
  cat({
    id: "wellness_retreat",
    name: "Wellness Retreat",
    group: "wellness",
    description: "Half-day reset.",
    defaultVibes: ["wellness", "soft_life"],
    venueTypes: ["wellness_center"],
    nightlifeIntensity: "low",
    budgetTiers: [3, 4],
  }),
  cat({
    id: "hot_springs",
    name: "Hot Springs",
    group: "wellness",
    description: "Natural or commercial hot springs.",
    defaultVibes: ["wellness", "soft_life"],
    venueTypes: ["hot_springs"],
    waterfront: "optional",
    weatherSensitive: true,
    nightlifeIntensity: "low",
  }),
  cat({
    id: "cold_plunge",
    name: "Cold Plunge Studio",
    group: "wellness",
    description: "Plunge + sauna contrast.",
    defaultVibes: ["wellness", "adventurous"],
    venueTypes: ["plunge_studio"],
    nightlifeIntensity: "low",
  }),

  // 10. SHOPPING ──────────────────────────────────────────────────
  cat({
    id: "shopping_mall",
    name: "Shopping Mall Day",
    group: "shopping",
    description: "Big mall + food court.",
    defaultVibes: ["chill", "social"],
    venueTypes: ["mall"],
    familySafe: true,
    nightlifeIntensity: "low",
  }),
  cat({
    id: "thrifting",
    name: "Thrifting Day",
    group: "shopping",
    description: "Best thrift + vintage block.",
    defaultVibes: ["local", "instagrammy"],
    venueTypes: ["thrift_store", "vintage_store"],
    familySafe: true,
    nightlifeIntensity: "low",
    budgetTiers: [1, 2],
  }),
  cat({
    id: "boutiques",
    name: "Local Boutiques Tour",
    group: "shopping",
    description: "Indie shop crawl.",
    defaultVibes: ["local", "instagrammy"],
    venueTypes: ["boutique"],
    familySafe: true,
    nightlifeIntensity: "low",
  }),
  cat({
    id: "outlet_mall",
    name: "Outlet Mall Trip",
    group: "shopping",
    description: "Outlet day trip.",
    defaultVibes: ["chill"],
    venueTypes: ["outlet_mall"],
    familySafe: true,
    nightlifeIntensity: "low",
  }),
  cat({
    id: "popup",
    name: "Pop-Up Event",
    group: "shopping",
    description: "Pop-up shop / market.",
    defaultVibes: ["instagrammy", "local"],
    venueTypes: ["popup_event"],
    familySafe: true,
    nightlifeIntensity: "low",
  }),
  cat({
    id: "flea_market",
    name: "Flea Market",
    group: "shopping",
    description: "Weekend flea.",
    defaultVibes: ["local", "chill"],
    venueTypes: ["flea_market"],
    familySafe: true,
    weatherSensitive: true,
    nightlifeIntensity: "low",
    budgetTiers: [1, 2],
  }),
  cat({
    id: "vintage_market",
    name: "Vintage Market",
    group: "shopping",
    description: "Curated vintage event.",
    defaultVibes: ["instagrammy", "local"],
    venueTypes: ["vintage_market"],
    familySafe: true,
    nightlifeIntensity: "low",
  }),
  cat({
    id: "bookstore_crawl",
    name: "Bookstore Crawl",
    group: "shopping",
    description: "Indie bookshops + cafe.",
    defaultVibes: ["chill", "classy"],
    venueTypes: ["bookstore", "cafe"],
    familySafe: true,
    nightlifeIntensity: "low",
    budgetTiers: [1, 2],
  }),

  // 11. LOCAL EXPERIENCES ────────────────────────────────────────
  cat({
    id: "hidden_gems",
    name: "Local Hidden Gems",
    group: "local",
    description: "Off-the-tourist-path stops.",
    defaultVibes: ["local", "chill"],
    venueTypes: ["local_restaurant", "speakeasy", "local_bar"],
  }),
  cat({
    id: "neighborhood_tour",
    name: "Neighborhood Tour",
    group: "local",
    description: "Best of one neighborhood.",
    defaultVibes: ["local", "instagrammy"],
    venueTypes: ["restaurant", "bar", "shop"],
    familySafe: true,
  }),
  cat({
    id: "farmers_market",
    name: "Farmers Market",
    group: "local",
    description: "Saturday market visit.",
    defaultVibes: ["local", "chill"],
    venueTypes: ["farmers_market"],
    familySafe: true,
    weatherSensitive: true,
    seasonal: true,
    nightlifeIntensity: "low",
    budgetTiers: [1, 2],
  }),
  cat({
    id: "local_coffee_crawl",
    name: "Local Coffee Crawl",
    group: "local",
    description: "3+ specialty coffees.",
    defaultVibes: ["local", "chill"],
    venueTypes: ["specialty_coffee"],
    familySafe: true,
    nightlifeIntensity: "low",
    budgetTiers: [1, 2],
  }),
  cat({
    id: "local_breakfast",
    name: "Local Breakfast Spots",
    group: "local",
    description: "Best AM eats.",
    defaultVibes: ["local", "chill"],
    venueTypes: ["breakfast_spot", "diner"],
    familySafe: true,
    nightlifeIntensity: "low",
    budgetTiers: [1, 2],
  }),
  cat({
    id: "local_bars",
    name: "Local Bars",
    group: "local",
    description: "Where locals actually drink.",
    defaultVibes: ["local", "social"],
    venueTypes: ["local_bar", "dive_bar"],
    familySafe: false,
    adultOnly: true,
    safetyFilters: ADULT_ONLY_FILTERS,
  }),
  cat({
    id: "local_art_walk",
    name: "Local Art Walk",
    group: "local",
    description: "Studio open hours.",
    defaultVibes: ["local", "classy"],
    venueTypes: ["gallery", "studio"],
    familySafe: true,
    nightlifeIntensity: "low",
  }),
  cat({
    id: "local_festivals",
    name: "Local Festivals",
    group: "local",
    description: "Seasonal block events.",
    defaultVibes: ["local", "social"],
    venueTypes: ["festival"],
    familySafe: true,
    weatherSensitive: true,
    seasonal: true,
  }),
  cat({
    id: "local_food_tour",
    name: "Local Food Tour",
    group: "local",
    description: "Guided tasting route.",
    defaultVibes: ["local", "instagrammy"],
    venueTypes: ["tour_company", "restaurant"],
    familySafe: true,
  }),

  // 12. CUSTOM ────────────────────────────────────────────────────
  cat({
    id: "custom_vibe",
    name: "Custom Vibe Night",
    group: "custom",
    description: "User-defined vibe.",
    defaultVibes: ["surprise"],
    venueTypes: [],
  }),
  cat({
    id: "build_your_own",
    name: "Build-Your-Own Night",
    group: "custom",
    description: "Mix-and-match.",
    defaultVibes: ["surprise"],
    venueTypes: [],
  }),
  cat({
    id: "surprise_me",
    name: "Surprise Me Night",
    group: "custom",
    description: "AI picks the whole thing.",
    defaultVibes: ["surprise"],
    venueTypes: [],
  }),
  cat({
    id: "mystery_night",
    name: "Mystery Night",
    group: "custom",
    description: "Hidden itinerary, revealed stop-by-stop.",
    defaultVibes: ["surprise", "adventurous"],
    venueTypes: [],
  }),
  cat({
    id: "hybrid_night",
    name: "Hybrid Night",
    group: "custom",
    description: "Multi-category mash-up.",
    defaultVibes: ["surprise"],
    venueTypes: [],
  }),
  cat({
    id: "ai_vibe",
    name: "AI-Generated Vibe Night",
    group: "custom",
    description: "AI-classified free-text request.",
    defaultVibes: ["surprise"],
    venueTypes: [],
  }),
];

export const CATEGORIES_BY_ID: Record<string, OutingCategory> = Object.fromEntries(
  OUTING_CATEGORIES.map((c) => [c.id, c]),
);

export function categoriesInGroup(group: CategoryGroupId): OutingCategory[] {
  return OUTING_CATEGORIES.filter((c) => c.group === group);
}

/**
 * Merge a set of selected categories into a single resolved constraint set
 * the planner can use as a directive.
 */
export type ResolvedConstraints = {
  categoryIds: string[];
  categoryNames: string[];
  vibeTags: string[];
  venueTypes: string[];
  avoidVenueTypes: string[];
  safetyFilters: string[];
  budgetTiers: (1 | 2 | 3 | 4)[];
  groupSize: [number, number];
  waterfront: WaterfrontRelevance;
  familySafe: boolean;
  adultOnly: boolean;
  conversationFriendly: boolean;
  weatherSensitive: boolean;
};

const WATER_RANK: Record<WaterfrontRelevance, number> = {
  none: 0,
  optional: 1,
  preferred: 2,
  required: 3,
};

export function resolveCategories(ids: string[]): ResolvedConstraints | null {
  const cats = ids.map((id) => CATEGORIES_BY_ID[id]).filter(Boolean);
  if (!cats.length) return null;

  const setOf = (arr: string[][]) => Array.from(new Set(arr.flat()));
  const groupMin = Math.max(...cats.map((c) => c.idealGroupSize[0]));
  const groupMax = Math.min(...cats.map((c) => c.idealGroupSize[1]));
  const waterfront = cats.reduce<WaterfrontRelevance>(
    (acc, c) => (WATER_RANK[c.waterfront] > WATER_RANK[acc] ? c.waterfront : acc),
    "none",
  );

  return {
    categoryIds: cats.map((c) => c.id),
    categoryNames: cats.map((c) => c.name),
    vibeTags: setOf([cats.map((c) => c.defaultVibes).flat()]),
    venueTypes: setOf([cats.map((c) => c.venueTypes).flat()]),
    avoidVenueTypes: setOf([cats.map((c) => c.avoidVenueTypes).flat()]),
    safetyFilters: setOf([cats.map((c) => c.safetyFilters).flat()]),
    budgetTiers: setOf([cats.map((c) => c.budgetTiers.map(String)).flat()]).map(
      (n) => Number(n) as 1 | 2 | 3 | 4,
    ),
    groupSize: [groupMin, Math.max(groupMin, groupMax)],
    waterfront,
    familySafe: cats.every((c) => c.familySafe),
    adultOnly: cats.some((c) => c.adultOnly),
    conversationFriendly: cats.some((c) => c.conversationFriendly),
    weatherSensitive: cats.some((c) => c.weatherSensitive),
  };
}

/**
 * Build a single directive string the planner can append to the LLM prompt.
 * Promo-safe: never mentions sponsorship or paid placement.
 */
export function buildCategoryDirective(c: ResolvedConstraints, freeText?: string): string {
  const parts: string[] = [];
  parts.push(`outing categories: ${c.categoryNames.join(" + ")}`);
  if (freeText?.trim()) parts.push(`user said: "${freeText.trim().slice(0, 200)}"`);
  if (c.vibeTags.length) parts.push(`vibe tags: ${c.vibeTags.join(", ")}`);
  if (c.venueTypes.length)
    parts.push(`prefer venue types: ${c.venueTypes.slice(0, 18).join(", ")}`);
  if (c.avoidVenueTypes.length) parts.push(`AVOID venue types: ${c.avoidVenueTypes.join(", ")}`);
  if (c.safetyFilters.length) parts.push(`hard safety filters: ${c.safetyFilters.join(", ")}`);
  if (c.familySafe)
    parts.push("must be family-safe (no clubs, strip clubs, heavy drinking, adult entertainment)");
  if (c.adultOnly) parts.push("21+ only");
  if (c.conversationFriendly)
    parts.push("must be conversation-friendly (no loud clubs / dive bars)");
  if (c.waterfront === "required") parts.push("waterfront is required");
  else if (c.waterfront === "preferred")
    parts.push("prefer waterfront, else scenic alternative (rooftop, overlook, skyline, garden)");
  return parts.join("; ");
}
