-- Seed social_venue_signals for DC (city_slug='dmv') from dc-venues-seed.json
-- Idempotent: clears prior seed rows first. Review columns vs live schema before running.
begin;

delete from public.social_venue_signals where city_slug = 'dmv' and signal_type = 'seed';

insert into public.social_venue_signals
  (venue_name, venue_slug, city_slug, category, signal_type, platform, engagement_score, sentiment, snippet, neighborhood, hashtags, outing_tags, is_active, collected_at)
values
  ('Albi', 'albi', 'dmv', 'Fine Dining', 'seed', 'confetti_seed', 86, 'positive', 'Michael Rafidi''s love letter to Palestinian and Levantine cooking. Fire-kissed meats and vegetables, sumac-bright salads, and house-baked breads in a stunning Navy Yard dining room.', 'Navy Yard', ARRAY['#romantic','#upscale','#cultural','#firecooked']::text[], ARRAY['Dinner Night','Couples Night','Group Night Out','Best Friends Night','Birthday Night','Anniversary Night','Fine Dining Night','Luxury Dinner Night','Soft Life Night','VIP Night']::text[], true, now()),
  ('Jônt', 'jont', 'dmv', 'Fine Dining', 'seed', 'confetti_seed', 94, 'positive', 'Chef Ryan Ratino''s 2-Michelin-star tasting menu blending American technique with Japanese precision. One of DC''s most exclusive dinner experiences with only 16 seats.', '14th Street Corridor', ARRAY['#intimate','#omakase','#upscale','#avantgarde']::text[], ARRAY['Dinner Night','Couples Night','Group Night Out','Best Friends Night','Birthday Night','Anniversary Night','Fine Dining Night','Luxury Dinner Night','Soft Life Night','VIP Night','Sushi Night']::text[], true, now()),
  ('Moon Rabbit', 'moon-rabbit', 'dmv', 'Dining', 'seed', 'confetti_seed', 91, 'positive', 'Chef Kevin Tien''s contemporary Vietnamese cooking is bold, precise, and deeply personal. Near the National Mall with some of DC''s most beautifully plated dishes.', 'Penn Quarter', ARRAY['#upscale','#modern','#cultural','#elegant']::text[], ARRAY['Dinner Night','Couples Night','Group Night Out','Best Friends Night','Birthday Night','Fine Dining Night','Luxury Dinner Night','Soft Life Night','VIP Night','Anniversary Night']::text[], true, now()),
  ('Masseria', 'masseria', 'dmv', 'Fine Dining', 'seed', 'confetti_seed', 70, 'positive', 'A Michelin-starred Italian farmhouse hidden in the Union Market district. Nicholas Stefanelli''s Southern Italian tasting menus are some of DC''s most transporting experiences.', 'Union Market', ARRAY['#rusticchic','#romantic','#upscale','#pastoral']::text[], ARRAY['Dinner Night','Couples Night','Group Night Out','Best Friends Night','Birthday Night','Anniversary Night','Fine Dining Night','Luxury Dinner Night','Soft Life Night','VIP Night']::text[], true, now()),
  ('Pascual', 'pascual', 'dmv', 'Dining', 'seed', 'confetti_seed', 78, 'positive', 'Chef Isabel Coss brings refined Mexican technique and seasonal ingredients to this celebrated Navy Yard newcomer. Mezcal cocktails and masa-driven dishes in a lively, colorful setting.', 'Ivy City / NoMa', ARRAY['#vibrant','#festive','#modern','#farmtotable']::text[], ARRAY['Dinner Night','Couples Night','Group Night Out','Best Friends Night','Birthday Night']::text[], true, now()),
  ('Bresca', 'bresca', 'dmv', 'Fine Dining', 'seed', 'confetti_seed', 83, 'positive', 'Ryan Ratino''s approachable companion to Jônt. Whimsical, art-forward fine dining on 14th Street — the tasting menu changes seasonally and always surprises.', '14th Street Corridor', ARRAY['#whimsical','#creative','#intimate','#artistic']::text[], ARRAY['Dinner Night','Couples Night','Group Night Out','Best Friends Night','Birthday Night','Anniversary Night','Fine Dining Night','Luxury Dinner Night','Soft Life Night']::text[], true, now()),
  ('The Dabney', 'the-dabney', 'dmv', 'Dining', 'seed', 'confetti_seed', 80, 'positive', 'Tucked into Blagden Alley in Shaw, this Michelin-starred gem celebrates Mid-Atlantic ingredients cooked over wood fire. One of DC''s most beloved neighborhood restaurants.', 'Shaw', ARRAY['#cozy','#rustic','#seasonal','#neighborhoodgem']::text[], ARRAY['Dinner Night','Couples Night','Group Night Out','Best Friends Night','Birthday Night']::text[], true, now()),
  ('Oyster Oyster', 'oyster-oyster', 'dmv', 'Dining', 'seed', 'confetti_seed', 71, 'positive', 'Chef Rob Rubba''s plant-forward, sustainability-focused tasting menu with a focus on fungi, oysters, and hyper-local ingredients. A Michelin green star recipient.', 'Shaw', ARRAY['#ecoconscious','#creative','#intimate','#trendy']::text[], ARRAY['Dinner Night','Couples Night','Group Night Out','Best Friends Night','Birthday Night','Anniversary Night','Seafood Night']::text[], true, now()),
  ('minibar by José Andrés', 'minibar', 'dmv', 'Fine Dining', 'seed', 'confetti_seed', 78, 'positive', '2-Michelin-star avant-garde laboratory from culinary icon José Andrés. A multi-course sensory experience with only 12 seats. One of America''s most influential restaurants.', 'Penn Quarter', ARRAY['#avantgarde','#theatrical','#exclusive','#mindblowing']::text[], ARRAY['Dinner Night','Couples Night','Group Night Out','Best Friends Night','Birthday Night','Fine Dining Night','Luxury Dinner Night','Soft Life Night']::text[], true, now()),
  ('Pineapple and Pearls', 'pineapple-and-pearls', 'dmv', 'Fine Dining', 'seed', 'confetti_seed', 94, 'positive', 'Aaron Silverman''s most extravagant expression — an all-inclusive, tips-included tasting menu dinner on Capitol Hill that reimagines what a special night out can be.', 'Capitol Hill', ARRAY['#luxurious','#playful','#celebratory','#overthetop']::text[], ARRAY['Dinner Night','Couples Night','Group Night Out','Best Friends Night','Birthday Night','Fine Dining Night','Luxury Dinner Night','Soft Life Night']::text[], true, now()),
  ('Sfoglina', 'sfoglina', 'dmv', 'Dining', 'seed', 'confetti_seed', 85, 'positive', 'James Beard-nominated chef Amy Brandwein''s house-made pasta restaurant. A neighborhood favorite for fresh tagliatelle, tortellini, and Roman classics in a warm setting.', 'Van Ness / Tenleytown', ARRAY['#cozy','#romantic','#neighborhood','#handmade']::text[], ARRAY['Dinner Night','Couples Night','Group Night Out','Best Friends Night','Birthday Night','Anniversary Night']::text[], true, now()),
  ('Compass Rose', 'compass-rose', 'dmv', 'Dining', 'seed', 'confetti_seed', 93, 'positive', 'Street food from around the world in a gorgeous rowhouse with a dreamy courtyard. The khachapuri (Georgian cheese bread) is legendary. Perfect for groups and adventurous eaters.', '14th Street Corridor', ARRAY['#eclectic','#adventurous','#social','#global']::text[], ARRAY['Dinner Night','Couples Night','Group Night Out','Best Friends Night','Birthday Night']::text[], true, now()),
  ('Service Bar', 'service-bar', 'dmv', 'Nightlife', 'seed', 'confetti_seed', 72, 'positive', 'Ranked #23 on North America''s 50 Best Bars 2026. DC''s premier craft cocktail destination — serious, inventive drinks in an intimate setting on U Street. Industry insiders'' favorite.', 'U Street Corridor', ARRAY['#craftcocktail','#industryfavorite','#intimate','#seriousdrinker']::text[], ARRAY['Chill Night','Bar Hop','Happy Hour','Group Night Out','Girls Night','Guys Night','Couples Night','Best Friends Night','Anniversary Night','Lounge Night','After-Hours Night']::text[], true, now()),
  ('Death & Co DC', 'death-and-co-dc', 'dmv', 'Nightlife', 'seed', 'confetti_seed', 82, 'positive', 'The DC outpost of the legendary New York cocktail bar. Dark, moody, and meticulously crafted — Death & Co brings NYC cocktail culture to DC with its own local twist.', 'Shaw / Dupont Circle', ARRAY['#upscale','#craftcocktail','#darkmoody','#famous']::text[], ARRAY['Chill Night','Bar Hop','Happy Hour','Group Night Out','Girls Night','Guys Night','Couples Night','Best Friends Night','Fine Dining Night','Luxury Dinner Night','Soft Life Night','VIP Night','Anniversary Night','Lounge Night','After-Hours Night']::text[], true, now()),
  ('Flight Club DC', 'flight-club-dc', 'dmv', 'Nightlife', 'seed', 'confetti_seed', 80, 'positive', 'Social darts reimagined for a night out. Automated scoring, craft cocktails, and shareable food in a massive Penn Quarter venue. Perfect for groups who want fun and drinks.', 'Penn Quarter', ARRAY['#social','#fun','#competitive','#upscalecasual']::text[], ARRAY['Chill Night','Bar Hop','Happy Hour','Group Night Out','Girls Night','Guys Night','Couples Night','Best Friends Night','Fine Dining Night','Luxury Dinner Night','Soft Life Night','VIP Night','Anniversary Night','Club Night','Turn-Up Night','After-Hours Night']::text[], true, now()),
  ('Off the Record', 'off-the-record', 'dmv', 'Nightlife', 'seed', 'confetti_seed', 82, 'positive', 'The basement bar of the Hay-Adams Hotel, a block from the White House. DC''s most storied watering hole — where senators, diplomats, and power brokers have gathered for decades.', 'Downtown / White House', ARRAY['#historic','#political','#powerscene','#underground']::text[], ARRAY['Chill Night','Bar Hop','Happy Hour','Group Night Out','Girls Night','Guys Night','Couples Night','Best Friends Night']::text[], true, now()),
  ('Madam''s Organ', 'madams-organ', 'dmv', 'Live Music', 'seed', 'confetti_seed', 74, 'positive', 'Adams Morgan''s most iconic live music bar. Blues, soul, and funk every night, cheap drinks, and a rooftop with city views. The heartbeat of DC''s nightlife scene since 1990.', 'Adams Morgan', ARRAY['#divechic','#livemusic','#bohemian','#legendary']::text[], ARRAY['Chill Night','Bar Hop','Happy Hour','Group Night Out','Girls Night','Guys Night','Couples Night','Best Friends Night','Jazz Night','Live Music Night']::text[], true, now()),
  ('Puttery', 'puttery', 'dmv', 'Nightlife', 'seed', 'confetti_seed', 78, 'positive', 'Multi-course mini golf with craft cocktails and DJ music. A buzzy, social experience in Penn Quarter that''s become DC''s go-to for group birthdays and date nights.', 'Penn Quarter / Chinatown', ARRAY['#fun','#social','#groupactivity','#upscalecasual']::text[], ARRAY['Chill Night','Bar Hop','Happy Hour','Group Night Out','Girls Night','Guys Night','Couples Night','Best Friends Night','Fine Dining Night','Luxury Dinner Night','Soft Life Night','VIP Night','Anniversary Night']::text[], true, now()),
  ('Harp & Cask', 'harp-and-cask', 'dmv', 'Nightlife', 'seed', 'confetti_seed', 93, 'positive', 'One of DC''s most buzzed-about new openings — a sophisticated whiskey and craft beer bar on Capitol Hill with an exceptional spirits selection and intimate atmosphere.', 'Capitol Hill', ARRAY['#intimate','#whiskeyfocused','#new','#hiddengem']::text[], ARRAY['Chill Night','Bar Hop','Happy Hour','Group Night Out','Girls Night','Guys Night','Couples Night','Best Friends Night','Anniversary Night']::text[], true, now()),
  ('Riff Raff Room', 'riff-raff-room', 'dmv', 'Nightlife', 'seed', 'confetti_seed', 80, 'positive', 'A new neighborhood bar in Columbia Heights making waves on Eater DC''s best new bars list. Eclectic, fun, and affordable with a great playlist and strong cocktails.', 'Columbia Heights', ARRAY['#eclectic','#divechic','#new','#latenight']::text[], ARRAY['Chill Night','Bar Hop','Happy Hour','Group Night Out','Girls Night','Guys Night','Couples Night','Best Friends Night']::text[], true, now()),
  ('The Dubliner', 'the-dubliner', 'dmv', 'Nightlife', 'seed', 'confetti_seed', 87, 'positive', 'DC''s most beloved Irish pub, steps from Union Station and the Capitol. A true institution — senators and staffers have been tipping pints here for 50 years. Live Irish music nightly.', 'Capitol Hill', ARRAY['#classic','#lively','#casual','#political']::text[], ARRAY['Chill Night','Bar Hop','Happy Hour','Group Night Out','Girls Night','Guys Night','Couples Night','Best Friends Night']::text[], true, now()),
  ('Eebee''s Co.', 'eebees-co', 'dmv', 'Nightlife', 'seed', 'confetti_seed', 79, 'positive', 'One of Eater DC''s best new bars of 2025/2026. A cocktail-forward neighborhood hangout in the Shaw/Logan Circle corridor with a fun, social vibe and creative drinks.', 'Shaw / Logan Circle', ARRAY['#trendy','#new','#cocktailforward','#social']::text[], ARRAY['Chill Night','Bar Hop','Happy Hour','Group Night Out','Girls Night','Guys Night','Couples Night','Best Friends Night','Lounge Night','After-Hours Night']::text[], true, now()),
  ('Upstate FTW', 'upstate-ftw', 'dmv', 'Nightlife', 'seed', 'confetti_seed', 92, 'positive', 'An Eater DC-highlighted new bar bringing New York upstate dive bar energy to Shaw. Cheap beers, strong vibes, and zero pretension — a breath of fresh air in a neighborhood gone upscale.', 'Shaw', ARRAY['#divebar','#unpretentious','#new','#neighborhood']::text[], ARRAY['Chill Night','Bar Hop','Happy Hour','Group Night Out','Girls Night','Guys Night','Couples Night','Best Friends Night']::text[], true, now());

commit;

-- 23 venues seeded.
