/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as InfluencerRouteImport } from './routes/influencer'
import { Route as HealthRouteImport } from './routes/health'
import { Route as ForBusinessRouteImport } from './routes/for-business'
import { Route as CheckInRouteImport } from './routes/check-in'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as BoardingPassRouteImport } from './routes/boarding-pass'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as AboutRouteImport } from './routes/about'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TripsIndexRouteImport } from './routes/trips.index'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as BusinessIndexRouteImport } from './routes/business.index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as VenueIdRouteImport } from './routes/venue.$id'
import { Route as TripsIdRouteImport } from './routes/trips.$id'
import { Route as PCodeRouteImport } from './routes/p.$code'
import { Route as EventsEventIdRouteImport } from './routes/events.$eventId'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as BusinessVerifyRouteImport } from './routes/business.verify'
import { Route as BusinessSocialRouteImport } from './routes/business.social'
import { Route as BusinessSettingsRouteImport } from './routes/business.settings'
import { Route as BusinessPromotersRouteImport } from './routes/business.promoters'
import { Route as BusinessMediaRouteImport } from './routes/business.media'
import { Route as BusinessLoginRouteImport } from './routes/business.login'
import { Route as BusinessEventsRouteImport } from './routes/business.events'
import { Route as BusinessDashboardRouteImport } from './routes/business.dashboard'
import { Route as BusinessClaimRouteImport } from './routes/business.claim'
import { Route as BusinessAnalyticsRouteImport } from './routes/business.analytics'
import { Route as BusinessAdsRouteImport } from './routes/business.ads'
import { Route as AppReelsRouteImport } from './routes/app.reels'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppPlanRouteImport } from './routes/app.plan'
import { Route as AppExploreRouteImport } from './routes/app.explore'
import { Route as ApiPlanRouteImport } from './routes/api/plan'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AdminTrendRadarRouteImport } from './routes/admin.trend-radar'
import { Route as AdminPartnersRouteImport } from './routes/admin.partners'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminConsoleRouteImport } from './routes/admin.console'
import { Route as TripsIdPassportRouteImport } from './routes/trips.$id.passport'
import { Route as ApiPublicPickEventsRouteImport } from './routes/api/public/pick-events'
import { Route as ApiMapsSatelliteRouteImport } from './routes/api/maps/satellite'
import { Route as ApiPublicWebhooksPartnerRouteImport } from './routes/api/public/webhooks/partner'
import { Route as ApiPublicWalletGoogleRouteImport } from './routes/api/public/wallet/google'
import { Route as ApiPublicTiktokCallbackRouteImport } from './routes/api/public/tiktok.callback'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicInstagramCallbackRouteImport } from './routes/api/public/instagram.callback'
import { Route as ApiPublicHooksTiktokRefreshRouteImport } from './routes/api/public/hooks/tiktok-refresh'
import { Route as ApiPublicHooksRefreshVenueMediaRouteImport } from './routes/api/public/hooks/refresh-venue-media'
import { Route as ApiPublicHooksRefreshTrendingVenuesRouteImport } from './routes/api/public/hooks/refresh-trending-venues'
import { Route as ApiPublicHooksRefreshOutreachCsvRouteImport } from './routes/api/public/hooks/refresh-outreach-csv'
import { Route as ApiPublicHooksDiscoverViralRouteImport } from './routes/api/public/hooks/discover-viral'
import { Route as ApiAdminWalletGoogleDebugRouteImport } from './routes/api/admin/wallet/google-debug'
import { Route as ApiAdminWalletGoogleClassRouteImport } from './routes/api/admin/wallet/google-class'
import { Route as ApiPublicPartnerV1MenuRouteImport } from './routes/api/public/partner/v1/menu'
import { Route as ApiPublicPartnerV1AvailabilityRouteImport } from './routes/api/public/partner/v1/availability'
import { Route as ApiPublicPartnerV1ReservationsIndexRouteImport } from './routes/api/public/partner/v1/reservations/index'
import { Route as ApiPublicPartnerV1OrdersIndexRouteImport } from './routes/api/public/partner/v1/orders/index'
import { Route as ApiPublicPartnerV1ReservationsIdRouteImport } from './routes/api/public/partner/v1/reservations/$id'
import { Route as ApiPublicPartnerV1OrdersIdRouteImport } from './routes/api/public/partner/v1/orders/$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/privacy.lazy').then((d) => d.Route))
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const InfluencerRoute = InfluencerRouteImport.update({
  id: '/influencer',
  path: '/influencer',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/influencer.lazy').then((d) => d.Route))
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ForBusinessRoute = ForBusinessRouteImport.update({
  id: '/for-business',
  path: '/for-business',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckInRoute = CheckInRouteImport.update({
  id: '/check-in',
  path: '/check-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardingPassRoute = BoardingPassRouteImport.update({
  id: '/boarding-pass',
  path: '/boarding-pass',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/auth.lazy').then((d) => d.Route))
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/accessibility.lazy').then((d) => d.Route))
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsIndexRoute = TripsIndexRouteImport.update({
  id: '/trips/',
  path: '/trips/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessIndexRoute = BusinessIndexRouteImport.update({
  id: '/business/',
  path: '/business/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const VenueIdRoute = VenueIdRouteImport.update({
  id: '/venue/$id',
  path: '/venue/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsIdRoute = TripsIdRouteImport.update({
  id: '/trips/$id',
  path: '/trips/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PCodeRoute = PCodeRouteImport.update({
  id: '/p/$code',
  path: '/p/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessVerifyRoute = BusinessVerifyRouteImport.update({
  id: '/business/verify',
  path: '/business/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessSocialRoute = BusinessSocialRouteImport.update({
  id: '/business/social',
  path: '/business/social',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessSettingsRoute = BusinessSettingsRouteImport.update({
  id: '/business/settings',
  path: '/business/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessPromotersRoute = BusinessPromotersRouteImport.update({
  id: '/business/promoters',
  path: '/business/promoters',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessMediaRoute = BusinessMediaRouteImport.update({
  id: '/business/media',
  path: '/business/media',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessLoginRoute = BusinessLoginRouteImport.update({
  id: '/business/login',
  path: '/business/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessEventsRoute = BusinessEventsRouteImport.update({
  id: '/business/events',
  path: '/business/events',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessDashboardRoute = BusinessDashboardRouteImport.update({
  id: '/business/dashboard',
  path: '/business/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessClaimRoute = BusinessClaimRouteImport.update({
  id: '/business/claim',
  path: '/business/claim',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessAnalyticsRoute = BusinessAnalyticsRouteImport.update({
  id: '/business/analytics',
  path: '/business/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessAdsRoute = BusinessAdsRouteImport.update({
  id: '/business/ads',
  path: '/business/ads',
  getParentRoute: () => rootRouteImport,
} as any)
const AppReelsRoute = AppReelsRouteImport.update({
  id: '/reels',
  path: '/reels',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPlanRoute = AppPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AppRoute,
} as any)
const AppExploreRoute = AppExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => AppRoute,
} as any)
const ApiPlanRoute = ApiPlanRouteImport.update({
  id: '/api/plan',
  path: '/api/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTrendRadarRoute = AdminTrendRadarRouteImport.update({
  id: '/admin/trend-radar',
  path: '/admin/trend-radar',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPartnersRoute = AdminPartnersRouteImport.update({
  id: '/admin/partners',
  path: '/admin/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConsoleRoute = AdminConsoleRouteImport.update({
  id: '/admin/console',
  path: '/admin/console',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsIdPassportRoute = TripsIdPassportRouteImport.update({
  id: '/passport',
  path: '/passport',
  getParentRoute: () => TripsIdRoute,
} as any)
const ApiPublicPickEventsRoute = ApiPublicPickEventsRouteImport.update({
  id: '/api/public/pick-events',
  path: '/api/public/pick-events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMapsSatelliteRoute = ApiMapsSatelliteRouteImport.update({
  id: '/api/maps/satellite',
  path: '/api/maps/satellite',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksPartnerRoute =
  ApiPublicWebhooksPartnerRouteImport.update({
    id: '/api/public/webhooks/partner',
    path: '/api/public/webhooks/partner',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWalletGoogleRoute = ApiPublicWalletGoogleRouteImport.update({
  id: '/api/public/wallet/google',
  path: '/api/public/wallet/google',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTiktokCallbackRoute = ApiPublicTiktokCallbackRouteImport.update({
  id: '/api/public/tiktok/callback',
  path: '/api/public/tiktok/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicInstagramCallbackRoute =
  ApiPublicInstagramCallbackRouteImport.update({
    id: '/api/public/instagram/callback',
    path: '/api/public/instagram/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksTiktokRefreshRoute =
  ApiPublicHooksTiktokRefreshRouteImport.update({
    id: '/api/public/hooks/tiktok-refresh',
    path: '/api/public/hooks/tiktok-refresh',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRefreshVenueMediaRoute =
  ApiPublicHooksRefreshVenueMediaRouteImport.update({
    id: '/api/public/hooks/refresh-venue-media',
    path: '/api/public/hooks/refresh-venue-media',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRefreshTrendingVenuesRoute =
  ApiPublicHooksRefreshTrendingVenuesRouteImport.update({
    id: '/api/public/hooks/refresh-trending-venues',
    path: '/api/public/hooks/refresh-trending-venues',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRefreshOutreachCsvRoute =
  ApiPublicHooksRefreshOutreachCsvRouteImport.update({
    id: '/api/public/hooks/refresh-outreach-csv',
    path: '/api/public/hooks/refresh-outreach-csv',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDiscoverViralRoute =
  ApiPublicHooksDiscoverViralRouteImport.update({
    id: '/api/public/hooks/discover-viral',
    path: '/api/public/hooks/discover-viral',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminWalletGoogleDebugRoute =
  ApiAdminWalletGoogleDebugRouteImport.update({
    id: '/api/admin/wallet/google-debug',
    path: '/api/admin/wallet/google-debug',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminWalletGoogleClassRoute =
  ApiAdminWalletGoogleClassRouteImport.update({
    id: '/api/admin/wallet/google-class',
    path: '/api/admin/wallet/google-class',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPartnerV1MenuRoute = ApiPublicPartnerV1MenuRouteImport.update({
  id: '/api/public/partner/v1/menu',
  path: '/api/public/partner/v1/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPartnerV1AvailabilityRoute =
  ApiPublicPartnerV1AvailabilityRouteImport.update({
    id: '/api/public/partner/v1/availability',
    path: '/api/public/partner/v1/availability',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPartnerV1ReservationsIndexRoute =
  ApiPublicPartnerV1ReservationsIndexRouteImport.update({
    id: '/api/public/partner/v1/reservations/',
    path: '/api/public/partner/v1/reservations/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPartnerV1OrdersIndexRoute =
  ApiPublicPartnerV1OrdersIndexRouteImport.update({
    id: '/api/public/partner/v1/orders/',
    path: '/api/public/partner/v1/orders/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPartnerV1ReservationsIdRoute =
  ApiPublicPartnerV1ReservationsIdRouteImport.update({
    id: '/api/public/partner/v1/reservations/$id',
    path: '/api/public/partner/v1/reservations/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPartnerV1OrdersIdRoute =
  ApiPublicPartnerV1OrdersIdRouteImport.update({
    id: '/api/public/partner/v1/orders/$id',
    path: '/api/public/partner/v1/orders/$id',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/boarding-pass': typeof BoardingPassRoute
  '/chat': typeof ChatRoute
  '/check-in': typeof CheckInRoute
  '/for-business': typeof ForBusinessRoute
  '/health': typeof HealthRoute
  '/influencer': typeof InfluencerRoute
  '/legal': typeof LegalRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/console': typeof AdminConsoleRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/trend-radar': typeof AdminTrendRadarRoute
  '/api/chat': typeof ApiChatRoute
  '/api/plan': typeof ApiPlanRoute
  '/app/explore': typeof AppExploreRoute
  '/app/plan': typeof AppPlanRoute
  '/app/profile': typeof AppProfileRoute
  '/app/reels': typeof AppReelsRoute
  '/business/ads': typeof BusinessAdsRoute
  '/business/analytics': typeof BusinessAnalyticsRoute
  '/business/claim': typeof BusinessClaimRoute
  '/business/dashboard': typeof BusinessDashboardRoute
  '/business/events': typeof BusinessEventsRoute
  '/business/login': typeof BusinessLoginRoute
  '/business/media': typeof BusinessMediaRoute
  '/business/promoters': typeof BusinessPromotersRoute
  '/business/settings': typeof BusinessSettingsRoute
  '/business/social': typeof BusinessSocialRoute
  '/business/verify': typeof BusinessVerifyRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/p/$code': typeof PCodeRoute
  '/trips/$id': typeof TripsIdRouteWithChildren
  '/venue/$id': typeof VenueIdRoute
  '/app/': typeof AppIndexRoute
  '/business/': typeof BusinessIndexRoute
  '/events/': typeof EventsIndexRoute
  '/trips/': typeof TripsIndexRoute
  '/api/maps/satellite': typeof ApiMapsSatelliteRoute
  '/api/public/pick-events': typeof ApiPublicPickEventsRoute
  '/trips/$id/passport': typeof TripsIdPassportRoute
  '/api/admin/wallet/google-class': typeof ApiAdminWalletGoogleClassRoute
  '/api/admin/wallet/google-debug': typeof ApiAdminWalletGoogleDebugRoute
  '/api/public/hooks/discover-viral': typeof ApiPublicHooksDiscoverViralRoute
  '/api/public/hooks/refresh-outreach-csv': typeof ApiPublicHooksRefreshOutreachCsvRoute
  '/api/public/hooks/refresh-trending-venues': typeof ApiPublicHooksRefreshTrendingVenuesRoute
  '/api/public/hooks/refresh-venue-media': typeof ApiPublicHooksRefreshVenueMediaRoute
  '/api/public/hooks/tiktok-refresh': typeof ApiPublicHooksTiktokRefreshRoute
  '/api/public/instagram/callback': typeof ApiPublicInstagramCallbackRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/tiktok/callback': typeof ApiPublicTiktokCallbackRoute
  '/api/public/wallet/google': typeof ApiPublicWalletGoogleRoute
  '/api/public/webhooks/partner': typeof ApiPublicWebhooksPartnerRoute
  '/api/public/partner/v1/availability': typeof ApiPublicPartnerV1AvailabilityRoute
  '/api/public/partner/v1/menu': typeof ApiPublicPartnerV1MenuRoute
  '/api/public/partner/v1/orders/$id': typeof ApiPublicPartnerV1OrdersIdRoute
  '/api/public/partner/v1/reservations/$id': typeof ApiPublicPartnerV1ReservationsIdRoute
  '/api/public/partner/v1/orders/': typeof ApiPublicPartnerV1OrdersIndexRoute
  '/api/public/partner/v1/reservations/': typeof ApiPublicPartnerV1ReservationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/auth': typeof AuthRoute
  '/boarding-pass': typeof BoardingPassRoute
  '/chat': typeof ChatRoute
  '/check-in': typeof CheckInRoute
  '/for-business': typeof ForBusinessRoute
  '/health': typeof HealthRoute
  '/influencer': typeof InfluencerRoute
  '/legal': typeof LegalRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/console': typeof AdminConsoleRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/trend-radar': typeof AdminTrendRadarRoute
  '/api/chat': typeof ApiChatRoute
  '/api/plan': typeof ApiPlanRoute
  '/app/explore': typeof AppExploreRoute
  '/app/plan': typeof AppPlanRoute
  '/app/profile': typeof AppProfileRoute
  '/app/reels': typeof AppReelsRoute
  '/business/ads': typeof BusinessAdsRoute
  '/business/analytics': typeof BusinessAnalyticsRoute
  '/business/claim': typeof BusinessClaimRoute
  '/business/dashboard': typeof BusinessDashboardRoute
  '/business/events': typeof BusinessEventsRoute
  '/business/login': typeof BusinessLoginRoute
  '/business/media': typeof BusinessMediaRoute
  '/business/promoters': typeof BusinessPromotersRoute
  '/business/settings': typeof BusinessSettingsRoute
  '/business/social': typeof BusinessSocialRoute
  '/business/verify': typeof BusinessVerifyRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/p/$code': typeof PCodeRoute
  '/trips/$id': typeof TripsIdRouteWithChildren
  '/venue/$id': typeof VenueIdRoute
  '/app': typeof AppIndexRoute
  '/business': typeof BusinessIndexRoute
  '/events': typeof EventsIndexRoute
  '/trips': typeof TripsIndexRoute
  '/api/maps/satellite': typeof ApiMapsSatelliteRoute
  '/api/public/pick-events': typeof ApiPublicPickEventsRoute
  '/trips/$id/passport': typeof TripsIdPassportRoute
  '/api/admin/wallet/google-class': typeof ApiAdminWalletGoogleClassRoute
  '/api/admin/wallet/google-debug': typeof ApiAdminWalletGoogleDebugRoute
  '/api/public/hooks/discover-viral': typeof ApiPublicHooksDiscoverViralRoute
  '/api/public/hooks/refresh-outreach-csv': typeof ApiPublicHooksRefreshOutreachCsvRoute
  '/api/public/hooks/refresh-trending-venues': typeof ApiPublicHooksRefreshTrendingVenuesRoute
  '/api/public/hooks/refresh-venue-media': typeof ApiPublicHooksRefreshVenueMediaRoute
  '/api/public/hooks/tiktok-refresh': typeof ApiPublicHooksTiktokRefreshRoute
  '/api/public/instagram/callback': typeof ApiPublicInstagramCallbackRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/tiktok/callback': typeof ApiPublicTiktokCallbackRoute
  '/api/public/wallet/google': typeof ApiPublicWalletGoogleRoute
  '/api/public/webhooks/partner': typeof ApiPublicWebhooksPartnerRoute
  '/api/public/partner/v1/availability': typeof ApiPublicPartnerV1AvailabilityRoute
  '/api/public/partner/v1/menu': typeof ApiPublicPartnerV1MenuRoute
  '/api/public/partner/v1/orders/$id': typeof ApiPublicPartnerV1OrdersIdRoute
  '/api/public/partner/v1/reservations/$id': typeof ApiPublicPartnerV1ReservationsIdRoute
  '/api/public/partner/v1/orders': typeof ApiPublicPartnerV1OrdersIndexRoute
  '/api/public/partner/v1/reservations': typeof ApiPublicPartnerV1ReservationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/boarding-pass': typeof BoardingPassRoute
  '/chat': typeof ChatRoute
  '/check-in': typeof CheckInRoute
  '/for-business': typeof ForBusinessRoute
  '/health': typeof HealthRoute
  '/influencer': typeof InfluencerRoute
  '/legal': typeof LegalRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/console': typeof AdminConsoleRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/trend-radar': typeof AdminTrendRadarRoute
  '/api/chat': typeof ApiChatRoute
  '/api/plan': typeof ApiPlanRoute
  '/app/explore': typeof AppExploreRoute
  '/app/plan': typeof AppPlanRoute
  '/app/profile': typeof AppProfileRoute
  '/app/reels': typeof AppReelsRoute
  '/business/ads': typeof BusinessAdsRoute
  '/business/analytics': typeof BusinessAnalyticsRoute
  '/business/claim': typeof BusinessClaimRoute
  '/business/dashboard': typeof BusinessDashboardRoute
  '/business/events': typeof BusinessEventsRoute
  '/business/login': typeof BusinessLoginRoute
  '/business/media': typeof BusinessMediaRoute
  '/business/promoters': typeof BusinessPromotersRoute
  '/business/settings': typeof BusinessSettingsRoute
  '/business/social': typeof BusinessSocialRoute
  '/business/verify': typeof BusinessVerifyRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/p/$code': typeof PCodeRoute
  '/trips/$id': typeof TripsIdRouteWithChildren
  '/venue/$id': typeof VenueIdRoute
  '/app/': typeof AppIndexRoute
  '/business/': typeof BusinessIndexRoute
  '/events/': typeof EventsIndexRoute
  '/trips/': typeof TripsIndexRoute
  '/api/maps/satellite': typeof ApiMapsSatelliteRoute
  '/api/public/pick-events': typeof ApiPublicPickEventsRoute
  '/trips/$id/passport': typeof TripsIdPassportRoute
  '/api/admin/wallet/google-class': typeof ApiAdminWalletGoogleClassRoute
  '/api/admin/wallet/google-debug': typeof ApiAdminWalletGoogleDebugRoute
  '/api/public/hooks/discover-viral': typeof ApiPublicHooksDiscoverViralRoute
  '/api/public/hooks/refresh-outreach-csv': typeof ApiPublicHooksRefreshOutreachCsvRoute
  '/api/public/hooks/refresh-trending-venues': typeof ApiPublicHooksRefreshTrendingVenuesRoute
  '/api/public/hooks/refresh-venue-media': typeof ApiPublicHooksRefreshVenueMediaRoute
  '/api/public/hooks/tiktok-refresh': typeof ApiPublicHooksTiktokRefreshRoute
  '/api/public/instagram/callback': typeof ApiPublicInstagramCallbackRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/tiktok/callback': typeof ApiPublicTiktokCallbackRoute
  '/api/public/wallet/google': typeof ApiPublicWalletGoogleRoute
  '/api/public/webhooks/partner': typeof ApiPublicWebhooksPartnerRoute
  '/api/public/partner/v1/availability': typeof ApiPublicPartnerV1AvailabilityRoute
  '/api/public/partner/v1/menu': typeof ApiPublicPartnerV1MenuRoute
  '/api/public/partner/v1/orders/$id': typeof ApiPublicPartnerV1OrdersIdRoute
  '/api/public/partner/v1/reservations/$id': typeof ApiPublicPartnerV1ReservationsIdRoute
  '/api/public/partner/v1/orders/': typeof ApiPublicPartnerV1OrdersIndexRoute
  '/api/public/partner/v1/reservations/': typeof ApiPublicPartnerV1ReservationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/about'
    | '/accessibility'
    | '/app'
    | '/auth'
    | '/boarding-pass'
    | '/chat'
    | '/check-in'
    | '/for-business'
    | '/health'
    | '/influencer'
    | '/legal'
    | '/privacy'
    | '/sitemap.xml'
    | '/admin/console'
    | '/admin/login'
    | '/admin/partners'
    | '/admin/trend-radar'
    | '/api/chat'
    | '/api/plan'
    | '/app/explore'
    | '/app/plan'
    | '/app/profile'
    | '/app/reels'
    | '/business/ads'
    | '/business/analytics'
    | '/business/claim'
    | '/business/dashboard'
    | '/business/events'
    | '/business/login'
    | '/business/media'
    | '/business/promoters'
    | '/business/settings'
    | '/business/social'
    | '/business/verify'
    | '/checkout/return'
    | '/events/$eventId'
    | '/p/$code'
    | '/trips/$id'
    | '/venue/$id'
    | '/app/'
    | '/business/'
    | '/events/'
    | '/trips/'
    | '/api/maps/satellite'
    | '/api/public/pick-events'
    | '/trips/$id/passport'
    | '/api/admin/wallet/google-class'
    | '/api/admin/wallet/google-debug'
    | '/api/public/hooks/discover-viral'
    | '/api/public/hooks/refresh-outreach-csv'
    | '/api/public/hooks/refresh-trending-venues'
    | '/api/public/hooks/refresh-venue-media'
    | '/api/public/hooks/tiktok-refresh'
    | '/api/public/instagram/callback'
    | '/api/public/payments/webhook'
    | '/api/public/tiktok/callback'
    | '/api/public/wallet/google'
    | '/api/public/webhooks/partner'
    | '/api/public/partner/v1/availability'
    | '/api/public/partner/v1/menu'
    | '/api/public/partner/v1/orders/$id'
    | '/api/public/partner/v1/reservations/$id'
    | '/api/public/partner/v1/orders/'
    | '/api/public/partner/v1/reservations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/about'
    | '/accessibility'
    | '/auth'
    | '/boarding-pass'
    | '/chat'
    | '/check-in'
    | '/for-business'
    | '/health'
    | '/influencer'
    | '/legal'
    | '/privacy'
    | '/sitemap.xml'
    | '/admin/console'
    | '/admin/login'
    | '/admin/partners'
    | '/admin/trend-radar'
    | '/api/chat'
    | '/api/plan'
    | '/app/explore'
    | '/app/plan'
    | '/app/profile'
    | '/app/reels'
    | '/business/ads'
    | '/business/analytics'
    | '/business/claim'
    | '/business/dashboard'
    | '/business/events'
    | '/business/login'
    | '/business/media'
    | '/business/promoters'
    | '/business/settings'
    | '/business/social'
    | '/business/verify'
    | '/checkout/return'
    | '/events/$eventId'
    | '/p/$code'
    | '/trips/$id'
    | '/venue/$id'
    | '/app'
    | '/business'
    | '/events'
    | '/trips'
    | '/api/maps/satellite'
    | '/api/public/pick-events'
    | '/trips/$id/passport'
    | '/api/admin/wallet/google-class'
    | '/api/admin/wallet/google-debug'
    | '/api/public/hooks/discover-viral'
    | '/api/public/hooks/refresh-outreach-csv'
    | '/api/public/hooks/refresh-trending-venues'
    | '/api/public/hooks/refresh-venue-media'
    | '/api/public/hooks/tiktok-refresh'
    | '/api/public/instagram/callback'
    | '/api/public/payments/webhook'
    | '/api/public/tiktok/callback'
    | '/api/public/wallet/google'
    | '/api/public/webhooks/partner'
    | '/api/public/partner/v1/availability'
    | '/api/public/partner/v1/menu'
    | '/api/public/partner/v1/orders/$id'
    | '/api/public/partner/v1/reservations/$id'
    | '/api/public/partner/v1/orders'
    | '/api/public/partner/v1/reservations'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/about'
    | '/accessibility'
    | '/app'
    | '/auth'
    | '/boarding-pass'
    | '/chat'
    | '/check-in'
    | '/for-business'
    | '/health'
    | '/influencer'
    | '/legal'
    | '/privacy'
    | '/sitemap.xml'
    | '/admin/console'
    | '/admin/login'
    | '/admin/partners'
    | '/admin/trend-radar'
    | '/api/chat'
    | '/api/plan'
    | '/app/explore'
    | '/app/plan'
    | '/app/profile'
    | '/app/reels'
    | '/business/ads'
    | '/business/analytics'
    | '/business/claim'
    | '/business/dashboard'
    | '/business/events'
    | '/business/login'
    | '/business/media'
    | '/business/promoters'
    | '/business/settings'
    | '/business/social'
    | '/business/verify'
    | '/checkout/return'
    | '/events/$eventId'
    | '/p/$code'
    | '/trips/$id'
    | '/venue/$id'
    | '/app/'
    | '/business/'
    | '/events/'
    | '/trips/'
    | '/api/maps/satellite'
    | '/api/public/pick-events'
    | '/trips/$id/passport'
    | '/api/admin/wallet/google-class'
    | '/api/admin/wallet/google-debug'
    | '/api/public/hooks/discover-viral'
    | '/api/public/hooks/refresh-outreach-csv'
    | '/api/public/hooks/refresh-trending-venues'
    | '/api/public/hooks/refresh-venue-media'
    | '/api/public/hooks/tiktok-refresh'
    | '/api/public/instagram/callback'
    | '/api/public/payments/webhook'
    | '/api/public/tiktok/callback'
    | '/api/public/wallet/google'
    | '/api/public/webhooks/partner'
    | '/api/public/partner/v1/availability'
    | '/api/public/partner/v1/menu'
    | '/api/public/partner/v1/orders/$id'
    | '/api/public/partner/v1/reservations/$id'
    | '/api/public/partner/v1/orders/'
    | '/api/public/partner/v1/reservations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AboutRoute: typeof AboutRoute
  AccessibilityRoute: typeof AccessibilityRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  BoardingPassRoute: typeof BoardingPassRoute
  ChatRoute: typeof ChatRoute
  CheckInRoute: typeof CheckInRoute
  ForBusinessRoute: typeof ForBusinessRoute
  HealthRoute: typeof HealthRoute
  InfluencerRoute: typeof InfluencerRoute
  LegalRoute: typeof LegalRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminConsoleRoute: typeof AdminConsoleRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPartnersRoute: typeof AdminPartnersRoute
  AdminTrendRadarRoute: typeof AdminTrendRadarRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiPlanRoute: typeof ApiPlanRoute
  BusinessAdsRoute: typeof BusinessAdsRoute
  BusinessAnalyticsRoute: typeof BusinessAnalyticsRoute
  BusinessClaimRoute: typeof BusinessClaimRoute
  BusinessDashboardRoute: typeof BusinessDashboardRoute
  BusinessEventsRoute: typeof BusinessEventsRoute
  BusinessLoginRoute: typeof BusinessLoginRoute
  BusinessMediaRoute: typeof BusinessMediaRoute
  BusinessPromotersRoute: typeof BusinessPromotersRoute
  BusinessSettingsRoute: typeof BusinessSettingsRoute
  BusinessSocialRoute: typeof BusinessSocialRoute
  BusinessVerifyRoute: typeof BusinessVerifyRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  EventsEventIdRoute: typeof EventsEventIdRoute
  PCodeRoute: typeof PCodeRoute
  TripsIdRoute: typeof TripsIdRouteWithChildren
  VenueIdRoute: typeof VenueIdRoute
  BusinessIndexRoute: typeof BusinessIndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
  TripsIndexRoute: typeof TripsIndexRoute
  ApiMapsSatelliteRoute: typeof ApiMapsSatelliteRoute
  ApiPublicPickEventsRoute: typeof ApiPublicPickEventsRoute
  ApiAdminWalletGoogleClassRoute: typeof ApiAdminWalletGoogleClassRoute
  ApiAdminWalletGoogleDebugRoute: typeof ApiAdminWalletGoogleDebugRoute
  ApiPublicHooksDiscoverViralRoute: typeof ApiPublicHooksDiscoverViralRoute
  ApiPublicHooksRefreshOutreachCsvRoute: typeof ApiPublicHooksRefreshOutreachCsvRoute
  ApiPublicHooksRefreshTrendingVenuesRoute: typeof ApiPublicHooksRefreshTrendingVenuesRoute
  ApiPublicHooksRefreshVenueMediaRoute: typeof ApiPublicHooksRefreshVenueMediaRoute
  ApiPublicHooksTiktokRefreshRoute: typeof ApiPublicHooksTiktokRefreshRoute
  ApiPublicInstagramCallbackRoute: typeof ApiPublicInstagramCallbackRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  ApiPublicTiktokCallbackRoute: typeof ApiPublicTiktokCallbackRoute
  ApiPublicWalletGoogleRoute: typeof ApiPublicWalletGoogleRoute
  ApiPublicWebhooksPartnerRoute: typeof ApiPublicWebhooksPartnerRoute
  ApiPublicPartnerV1AvailabilityRoute: typeof ApiPublicPartnerV1AvailabilityRoute
  ApiPublicPartnerV1MenuRoute: typeof ApiPublicPartnerV1MenuRoute
  ApiPublicPartnerV1OrdersIdRoute: typeof ApiPublicPartnerV1OrdersIdRoute
  ApiPublicPartnerV1ReservationsIdRoute: typeof ApiPublicPartnerV1ReservationsIdRoute
  ApiPublicPartnerV1OrdersIndexRoute: typeof ApiPublicPartnerV1OrdersIndexRoute
  ApiPublicPartnerV1ReservationsIndexRoute: typeof ApiPublicPartnerV1ReservationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/influencer': {
      id: '/influencer'
      path: '/influencer'
      fullPath: '/influencer'
      preLoaderRoute: typeof InfluencerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-business': {
      id: '/for-business'
      path: '/for-business'
      fullPath: '/for-business'
      preLoaderRoute: typeof ForBusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-in': {
      id: '/check-in'
      path: '/check-in'
      fullPath: '/check-in'
      preLoaderRoute: typeof CheckInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boarding-pass': {
      id: '/boarding-pass'
      path: '/boarding-pass'
      fullPath: '/boarding-pass'
      preLoaderRoute: typeof BoardingPassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/': {
      id: '/trips/'
      path: '/trips'
      fullPath: '/trips/'
      preLoaderRoute: typeof TripsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/': {
      id: '/business/'
      path: '/business'
      fullPath: '/business/'
      preLoaderRoute: typeof BusinessIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/venue/$id': {
      id: '/venue/$id'
      path: '/venue/$id'
      fullPath: '/venue/$id'
      preLoaderRoute: typeof VenueIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/$id': {
      id: '/trips/$id'
      path: '/trips/$id'
      fullPath: '/trips/$id'
      preLoaderRoute: typeof TripsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$code': {
      id: '/p/$code'
      path: '/p/$code'
      fullPath: '/p/$code'
      preLoaderRoute: typeof PCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/verify': {
      id: '/business/verify'
      path: '/business/verify'
      fullPath: '/business/verify'
      preLoaderRoute: typeof BusinessVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/social': {
      id: '/business/social'
      path: '/business/social'
      fullPath: '/business/social'
      preLoaderRoute: typeof BusinessSocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/settings': {
      id: '/business/settings'
      path: '/business/settings'
      fullPath: '/business/settings'
      preLoaderRoute: typeof BusinessSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/promoters': {
      id: '/business/promoters'
      path: '/business/promoters'
      fullPath: '/business/promoters'
      preLoaderRoute: typeof BusinessPromotersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/media': {
      id: '/business/media'
      path: '/business/media'
      fullPath: '/business/media'
      preLoaderRoute: typeof BusinessMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/login': {
      id: '/business/login'
      path: '/business/login'
      fullPath: '/business/login'
      preLoaderRoute: typeof BusinessLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/events': {
      id: '/business/events'
      path: '/business/events'
      fullPath: '/business/events'
      preLoaderRoute: typeof BusinessEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/dashboard': {
      id: '/business/dashboard'
      path: '/business/dashboard'
      fullPath: '/business/dashboard'
      preLoaderRoute: typeof BusinessDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/claim': {
      id: '/business/claim'
      path: '/business/claim'
      fullPath: '/business/claim'
      preLoaderRoute: typeof BusinessClaimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/analytics': {
      id: '/business/analytics'
      path: '/business/analytics'
      fullPath: '/business/analytics'
      preLoaderRoute: typeof BusinessAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/ads': {
      id: '/business/ads'
      path: '/business/ads'
      fullPath: '/business/ads'
      preLoaderRoute: typeof BusinessAdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/reels': {
      id: '/app/reels'
      path: '/reels'
      fullPath: '/app/reels'
      preLoaderRoute: typeof AppReelsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/plan': {
      id: '/app/plan'
      path: '/plan'
      fullPath: '/app/plan'
      preLoaderRoute: typeof AppPlanRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/explore': {
      id: '/app/explore'
      path: '/explore'
      fullPath: '/app/explore'
      preLoaderRoute: typeof AppExploreRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/plan': {
      id: '/api/plan'
      path: '/api/plan'
      fullPath: '/api/plan'
      preLoaderRoute: typeof ApiPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/trend-radar': {
      id: '/admin/trend-radar'
      path: '/admin/trend-radar'
      fullPath: '/admin/trend-radar'
      preLoaderRoute: typeof AdminTrendRadarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/partners': {
      id: '/admin/partners'
      path: '/admin/partners'
      fullPath: '/admin/partners'
      preLoaderRoute: typeof AdminPartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/console': {
      id: '/admin/console'
      path: '/admin/console'
      fullPath: '/admin/console'
      preLoaderRoute: typeof AdminConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/$id/passport': {
      id: '/trips/$id/passport'
      path: '/passport'
      fullPath: '/trips/$id/passport'
      preLoaderRoute: typeof TripsIdPassportRouteImport
      parentRoute: typeof TripsIdRoute
    }
    '/api/public/pick-events': {
      id: '/api/public/pick-events'
      path: '/api/public/pick-events'
      fullPath: '/api/public/pick-events'
      preLoaderRoute: typeof ApiPublicPickEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/maps/satellite': {
      id: '/api/maps/satellite'
      path: '/api/maps/satellite'
      fullPath: '/api/maps/satellite'
      preLoaderRoute: typeof ApiMapsSatelliteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/partner': {
      id: '/api/public/webhooks/partner'
      path: '/api/public/webhooks/partner'
      fullPath: '/api/public/webhooks/partner'
      preLoaderRoute: typeof ApiPublicWebhooksPartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/wallet/google': {
      id: '/api/public/wallet/google'
      path: '/api/public/wallet/google'
      fullPath: '/api/public/wallet/google'
      preLoaderRoute: typeof ApiPublicWalletGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/tiktok/callback': {
      id: '/api/public/tiktok/callback'
      path: '/api/public/tiktok/callback'
      fullPath: '/api/public/tiktok/callback'
      preLoaderRoute: typeof ApiPublicTiktokCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/instagram/callback': {
      id: '/api/public/instagram/callback'
      path: '/api/public/instagram/callback'
      fullPath: '/api/public/instagram/callback'
      preLoaderRoute: typeof ApiPublicInstagramCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/tiktok-refresh': {
      id: '/api/public/hooks/tiktok-refresh'
      path: '/api/public/hooks/tiktok-refresh'
      fullPath: '/api/public/hooks/tiktok-refresh'
      preLoaderRoute: typeof ApiPublicHooksTiktokRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/refresh-venue-media': {
      id: '/api/public/hooks/refresh-venue-media'
      path: '/api/public/hooks/refresh-venue-media'
      fullPath: '/api/public/hooks/refresh-venue-media'
      preLoaderRoute: typeof ApiPublicHooksRefreshVenueMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/refresh-trending-venues': {
      id: '/api/public/hooks/refresh-trending-venues'
      path: '/api/public/hooks/refresh-trending-venues'
      fullPath: '/api/public/hooks/refresh-trending-venues'
      preLoaderRoute: typeof ApiPublicHooksRefreshTrendingVenuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/refresh-outreach-csv': {
      id: '/api/public/hooks/refresh-outreach-csv'
      path: '/api/public/hooks/refresh-outreach-csv'
      fullPath: '/api/public/hooks/refresh-outreach-csv'
      preLoaderRoute: typeof ApiPublicHooksRefreshOutreachCsvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/discover-viral': {
      id: '/api/public/hooks/discover-viral'
      path: '/api/public/hooks/discover-viral'
      fullPath: '/api/public/hooks/discover-viral'
      preLoaderRoute: typeof ApiPublicHooksDiscoverViralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/wallet/google-debug': {
      id: '/api/admin/wallet/google-debug'
      path: '/api/admin/wallet/google-debug'
      fullPath: '/api/admin/wallet/google-debug'
      preLoaderRoute: typeof ApiAdminWalletGoogleDebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/wallet/google-class': {
      id: '/api/admin/wallet/google-class'
      path: '/api/admin/wallet/google-class'
      fullPath: '/api/admin/wallet/google-class'
      preLoaderRoute: typeof ApiAdminWalletGoogleClassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/partner/v1/menu': {
      id: '/api/public/partner/v1/menu'
      path: '/api/public/partner/v1/menu'
      fullPath: '/api/public/partner/v1/menu'
      preLoaderRoute: typeof ApiPublicPartnerV1MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/partner/v1/availability': {
      id: '/api/public/partner/v1/availability'
      path: '/api/public/partner/v1/availability'
      fullPath: '/api/public/partner/v1/availability'
      preLoaderRoute: typeof ApiPublicPartnerV1AvailabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/partner/v1/reservations/': {
      id: '/api/public/partner/v1/reservations/'
      path: '/api/public/partner/v1/reservations'
      fullPath: '/api/public/partner/v1/reservations/'
      preLoaderRoute: typeof ApiPublicPartnerV1ReservationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/partner/v1/orders/': {
      id: '/api/public/partner/v1/orders/'
      path: '/api/public/partner/v1/orders'
      fullPath: '/api/public/partner/v1/orders/'
      preLoaderRoute: typeof ApiPublicPartnerV1OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/partner/v1/reservations/$id': {
      id: '/api/public/partner/v1/reservations/$id'
      path: '/api/public/partner/v1/reservations/$id'
      fullPath: '/api/public/partner/v1/reservations/$id'
      preLoaderRoute: typeof ApiPublicPartnerV1ReservationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/partner/v1/orders/$id': {
      id: '/api/public/partner/v1/orders/$id'
      path: '/api/public/partner/v1/orders/$id'
      fullPath: '/api/public/partner/v1/orders/$id'
      preLoaderRoute: typeof ApiPublicPartnerV1OrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppExploreRoute: typeof AppExploreRoute
  AppPlanRoute: typeof AppPlanRoute
  AppProfileRoute: typeof AppProfileRoute
  AppReelsRoute: typeof AppReelsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppExploreRoute: AppExploreRoute,
  AppPlanRoute: AppPlanRoute,
  AppProfileRoute: AppProfileRoute,
  AppReelsRoute: AppReelsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface TripsIdRouteChildren {
  TripsIdPassportRoute: typeof TripsIdPassportRoute
}

const TripsIdRouteChildren: TripsIdRouteChildren = {
  TripsIdPassportRoute: TripsIdPassportRoute,
}

const TripsIdRouteWithChildren =
  TripsIdRoute._addFileChildren(TripsIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AboutRoute: AboutRoute,
  AccessibilityRoute: AccessibilityRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  BoardingPassRoute: BoardingPassRoute,
  ChatRoute: ChatRoute,
  CheckInRoute: CheckInRoute,
  ForBusinessRoute: ForBusinessRoute,
  HealthRoute: HealthRoute,
  InfluencerRoute: InfluencerRoute,
  LegalRoute: LegalRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminConsoleRoute: AdminConsoleRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminPartnersRoute: AdminPartnersRoute,
  AdminTrendRadarRoute: AdminTrendRadarRoute,
  ApiChatRoute: ApiChatRoute,
  ApiPlanRoute: ApiPlanRoute,
  BusinessAdsRoute: BusinessAdsRoute,
  BusinessAnalyticsRoute: BusinessAnalyticsRoute,
  BusinessClaimRoute: BusinessClaimRoute,
  BusinessDashboardRoute: BusinessDashboardRoute,
  BusinessEventsRoute: BusinessEventsRoute,
  BusinessLoginRoute: BusinessLoginRoute,
  BusinessMediaRoute: BusinessMediaRoute,
  BusinessPromotersRoute: BusinessPromotersRoute,
  BusinessSettingsRoute: BusinessSettingsRoute,
  BusinessSocialRoute: BusinessSocialRoute,
  BusinessVerifyRoute: BusinessVerifyRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  EventsEventIdRoute: EventsEventIdRoute,
  PCodeRoute: PCodeRoute,
  TripsIdRoute: TripsIdRouteWithChildren,
  VenueIdRoute: VenueIdRoute,
  BusinessIndexRoute: BusinessIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
  TripsIndexRoute: TripsIndexRoute,
  ApiMapsSatelliteRoute: ApiMapsSatelliteRoute,
  ApiPublicPickEventsRoute: ApiPublicPickEventsRoute,
  ApiAdminWalletGoogleClassRoute: ApiAdminWalletGoogleClassRoute,
  ApiAdminWalletGoogleDebugRoute: ApiAdminWalletGoogleDebugRoute,
  ApiPublicHooksDiscoverViralRoute: ApiPublicHooksDiscoverViralRoute,
  ApiPublicHooksRefreshOutreachCsvRoute: ApiPublicHooksRefreshOutreachCsvRoute,
  ApiPublicHooksRefreshTrendingVenuesRoute:
    ApiPublicHooksRefreshTrendingVenuesRoute,
  ApiPublicHooksRefreshVenueMediaRoute: ApiPublicHooksRefreshVenueMediaRoute,
  ApiPublicHooksTiktokRefreshRoute: ApiPublicHooksTiktokRefreshRoute,
  ApiPublicInstagramCallbackRoute: ApiPublicInstagramCallbackRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  ApiPublicTiktokCallbackRoute: ApiPublicTiktokCallbackRoute,
  ApiPublicWalletGoogleRoute: ApiPublicWalletGoogleRoute,
  ApiPublicWebhooksPartnerRoute: ApiPublicWebhooksPartnerRoute,
  ApiPublicPartnerV1AvailabilityRoute: ApiPublicPartnerV1AvailabilityRoute,
  ApiPublicPartnerV1MenuRoute: ApiPublicPartnerV1MenuRoute,
  ApiPublicPartnerV1OrdersIdRoute: ApiPublicPartnerV1OrdersIdRoute,
  ApiPublicPartnerV1ReservationsIdRoute: ApiPublicPartnerV1ReservationsIdRoute,
  ApiPublicPartnerV1OrdersIndexRoute: ApiPublicPartnerV1OrdersIndexRoute,
  ApiPublicPartnerV1ReservationsIndexRoute:
    ApiPublicPartnerV1ReservationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
