/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeatherRouteImport } from './routes/weather'
import { Route as ViralRouteImport } from './routes/viral'
import { Route as TranslateRouteImport } from './routes/translate'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as TasteTunerRouteImport } from './routes/taste-tuner'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as ReservationsRouteImport } from './routes/reservations'
import { Route as QuickGenerateRouteImport } from './routes/quick-generate'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as PassportRouteImport } from './routes/passport'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MeRouteImport } from './routes/me'
import { Route as InvestorsRouteImport } from './routes/investors'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as DataTermsRouteImport } from './routes/data-terms'
import { Route as CreateRouteImport } from './routes/create'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConfirmationRouteImport } from './routes/confirmation'
import { Route as ConciergeRouteImport } from './routes/concierge'
import { Route as CheckInRouteImport } from './routes/check-in'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as BoardingPassRouteImport } from './routes/boarding-pass'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdvertiseRouteImport } from './routes/advertise'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ActiveLoopRouteImport } from './routes/active-loop'
import { Route as ActiveConfettiRouteImport } from './routes/active-confetti'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TripsIndexRouteImport } from './routes/trips.index'
import { Route as TeamsIndexRouteImport } from './routes/teams.index'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as ConciergeIndexRouteImport } from './routes/concierge.index'
import { Route as AdvertiseIndexRouteImport } from './routes/advertise.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as VenueIdRouteImport } from './routes/venue.$id'
import { Route as TripsIdRouteImport } from './routes/trips.$id'
import { Route as TeamsNewRouteImport } from './routes/teams.new'
import { Route as TeamsIdRouteImport } from './routes/teams.$id'
import { Route as RsvpTripIdRouteImport } from './routes/rsvp.$tripId'
import { Route as RsvpTokenRouteImport } from './routes/rsvp.$token'
import { Route as RecapItineraryIdRouteImport } from './routes/recap.$itineraryId'
import { Route as PortalViralRouteImport } from './routes/portal.viral'
import { Route as PortalSavedRouteImport } from './routes/portal.saved'
import { Route as PortalReferRouteImport } from './routes/portal.refer'
import { Route as PortalProfileRouteImport } from './routes/portal.profile'
import { Route as PortalBookingsRouteImport } from './routes/portal.bookings'
import { Route as PortalActivityRouteImport } from './routes/portal.activity'
import { Route as PortalAchievementsRouteImport } from './routes/portal.achievements'
import { Route as PlanReadyRouteImport } from './routes/plan.ready'
import { Route as PlanPreviewRouteImport } from './routes/plan.preview'
import { Route as IdeasSlugRouteImport } from './routes/ideas.$slug'
import { Route as EventsEventIdRouteImport } from './routes/events.$eventId'
import { Route as ConciergeProfileRouteImport } from './routes/concierge.profile'
import { Route as ConciergePassportRouteImport } from './routes/concierge.passport'
import { Route as CollabTripIdRouteImport } from './routes/collab.$tripId'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AdvertisePortalRouteImport } from './routes/advertise.portal'
import { Route as AdminWalletDebugRouteImport } from './routes/admin.wallet-debug'
import { Route as AdminVenuesRouteImport } from './routes/admin.venues'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTestimonialsRouteImport } from './routes/admin.testimonials'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminPickAnalyticsRouteImport } from './routes/admin.pick-analytics'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminModerationRouteImport } from './routes/admin.moderation'
import { Route as AdminMarqueeRouteImport } from './routes/admin.marquee'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminLaunchRouteImport } from './routes/admin.launch'
import { Route as AdminIntegrationsRouteImport } from './routes/admin.integrations'
import { Route as AdminBookingsRouteImport } from './routes/admin.bookings'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminAdvertisersRouteImport } from './routes/admin.advertisers'
import { Route as AdminAdAnalyticsRouteImport } from './routes/admin.ad-analytics'
import { Route as ConciergeChatIndexRouteImport } from './routes/concierge.chat.index'
import { Route as TripsIdPassportRouteImport } from './routes/trips.$id.passport'
import { Route as ConciergeChatThreadIdRouteImport } from './routes/concierge.chat.$threadId'
import { Route as ApiPublicPickEventsRouteImport } from './routes/api/public/pick-events'
import { Route as ApiPublicWalletGoogleRouteImport } from './routes/api/public/wallet/google'
import { Route as ApiPublicTiktokCallbackRouteImport } from './routes/api/public/tiktok.callback'
import { Route as ApiPublicInstagramCallbackRouteImport } from './routes/api/public/instagram.callback'
import { Route as ApiPublicHooksTiktokRefreshRouteImport } from './routes/api/public/hooks/tiktok-refresh'
import { Route as ApiPublicHooksDiscoverViralRouteImport } from './routes/api/public/hooks/discover-viral'
import { Route as ApiAdminWalletGoogleDebugRouteImport } from './routes/api/admin/wallet/google-debug'
import { Route as ApiAdminWalletGoogleClassRouteImport } from './routes/api/admin/wallet/google-class'

const WeatherRoute = WeatherRouteImport.update({
  id: '/weather',
  path: '/weather',
  getParentRoute: () => rootRouteImport,
} as any)
const ViralRoute = ViralRouteImport.update({
  id: '/viral',
  path: '/viral',
  getParentRoute: () => rootRouteImport,
} as any)
const TranslateRoute = TranslateRouteImport.update({
  id: '/translate',
  path: '/translate',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const TasteTunerRoute = TasteTunerRouteImport.update({
  id: '/taste-tuner',
  path: '/taste-tuner',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationsRoute = ReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => rootRouteImport,
} as any)
const QuickGenerateRoute = QuickGenerateRouteImport.update({
  id: '/quick-generate',
  path: '/quick-generate',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const PassportRoute = PassportRouteImport.update({
  id: '/passport',
  path: '/passport',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestorsRoute = InvestorsRouteImport.update({
  id: '/investors',
  path: '/investors',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const DataTermsRoute = DataTermsRouteImport.update({
  id: '/data-terms',
  path: '/data-terms',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmationRoute = ConfirmationRouteImport.update({
  id: '/confirmation',
  path: '/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const ConciergeRoute = ConciergeRouteImport.update({
  id: '/concierge',
  path: '/concierge',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckInRoute = CheckInRouteImport.update({
  id: '/check-in',
  path: '/check-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardingPassRoute = BoardingPassRouteImport.update({
  id: '/boarding-pass',
  path: '/boarding-pass',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvertiseRoute = AdvertiseRouteImport.update({
  id: '/advertise',
  path: '/advertise',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ActiveLoopRoute = ActiveLoopRouteImport.update({
  id: '/active-loop',
  path: '/active-loop',
  getParentRoute: () => rootRouteImport,
} as any)
const ActiveConfettiRoute = ActiveConfettiRouteImport.update({
  id: '/active-confetti',
  path: '/active-confetti',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsIndexRoute = TripsIndexRouteImport.update({
  id: '/trips/',
  path: '/trips/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsIndexRoute = TeamsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeamsRoute,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConciergeIndexRoute = ConciergeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConciergeRoute,
} as any)
const AdvertiseIndexRoute = AdvertiseIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdvertiseRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const VenueIdRoute = VenueIdRouteImport.update({
  id: '/venue/$id',
  path: '/venue/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsIdRoute = TripsIdRouteImport.update({
  id: '/trips/$id',
  path: '/trips/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsNewRoute = TeamsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => TeamsRoute,
} as any)
const TeamsIdRoute = TeamsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TeamsRoute,
} as any)
const RsvpTripIdRoute = RsvpTripIdRouteImport.update({
  id: '/rsvp/$tripId',
  path: '/rsvp/$tripId',
  getParentRoute: () => rootRouteImport,
} as any)
const RsvpTokenRoute = RsvpTokenRouteImport.update({
  id: '/rsvp/$token',
  path: '/rsvp/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const RecapItineraryIdRoute = RecapItineraryIdRouteImport.update({
  id: '/recap/$itineraryId',
  path: '/recap/$itineraryId',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalViralRoute = PortalViralRouteImport.update({
  id: '/viral',
  path: '/viral',
  getParentRoute: () => PortalRoute,
} as any)
const PortalSavedRoute = PortalSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => PortalRoute,
} as any)
const PortalReferRoute = PortalReferRouteImport.update({
  id: '/refer',
  path: '/refer',
  getParentRoute: () => PortalRoute,
} as any)
const PortalProfileRoute = PortalProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PortalRoute,
} as any)
const PortalBookingsRoute = PortalBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => PortalRoute,
} as any)
const PortalActivityRoute = PortalActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAchievementsRoute = PortalAchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => PortalRoute,
} as any)
const PlanReadyRoute = PlanReadyRouteImport.update({
  id: '/ready',
  path: '/ready',
  getParentRoute: () => PlanRoute,
} as any)
const PlanPreviewRoute = PlanPreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => PlanRoute,
} as any)
const IdeasSlugRoute = IdeasSlugRouteImport.update({
  id: '/ideas/$slug',
  path: '/ideas/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const ConciergeProfileRoute = ConciergeProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ConciergeRoute,
} as any)
const ConciergePassportRoute = ConciergePassportRouteImport.update({
  id: '/passport',
  path: '/passport',
  getParentRoute: () => ConciergeRoute,
} as any)
const CollabTripIdRoute = CollabTripIdRouteImport.update({
  id: '/collab/$tripId',
  path: '/collab/$tripId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvertisePortalRoute = AdvertisePortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AdvertiseRoute,
} as any)
const AdminWalletDebugRoute = AdminWalletDebugRouteImport.update({
  id: '/wallet-debug',
  path: '/wallet-debug',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVenuesRoute = AdminVenuesRouteImport.update({
  id: '/venues',
  path: '/venues',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTestimonialsRoute = AdminTestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPickAnalyticsRoute = AdminPickAnalyticsRouteImport.update({
  id: '/pick-analytics',
  path: '/pick-analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModerationRoute = AdminModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMarqueeRoute = AdminMarqueeRouteImport.update({
  id: '/marquee',
  path: '/marquee',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLaunchRoute = AdminLaunchRouteImport.update({
  id: '/launch',
  path: '/launch',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIntegrationsRoute = AdminIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdvertisersRoute = AdminAdvertisersRouteImport.update({
  id: '/advertisers',
  path: '/advertisers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdAnalyticsRoute = AdminAdAnalyticsRouteImport.update({
  id: '/ad-analytics',
  path: '/ad-analytics',
  getParentRoute: () => AdminRoute,
} as any)
const ConciergeChatIndexRoute = ConciergeChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => ConciergeRoute,
} as any)
const TripsIdPassportRoute = TripsIdPassportRouteImport.update({
  id: '/passport',
  path: '/passport',
  getParentRoute: () => TripsIdRoute,
} as any)
const ConciergeChatThreadIdRoute = ConciergeChatThreadIdRouteImport.update({
  id: '/chat/$threadId',
  path: '/chat/$threadId',
  getParentRoute: () => ConciergeRoute,
} as any)
const ApiPublicPickEventsRoute = ApiPublicPickEventsRouteImport.update({
  id: '/api/public/pick-events',
  path: '/api/public/pick-events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWalletGoogleRoute = ApiPublicWalletGoogleRouteImport.update({
  id: '/api/public/wallet/google',
  path: '/api/public/wallet/google',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTiktokCallbackRoute = ApiPublicTiktokCallbackRouteImport.update({
  id: '/api/public/tiktok/callback',
  path: '/api/public/tiktok/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicInstagramCallbackRoute =
  ApiPublicInstagramCallbackRouteImport.update({
    id: '/api/public/instagram/callback',
    path: '/api/public/instagram/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksTiktokRefreshRoute =
  ApiPublicHooksTiktokRefreshRouteImport.update({
    id: '/api/public/hooks/tiktok-refresh',
    path: '/api/public/hooks/tiktok-refresh',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDiscoverViralRoute =
  ApiPublicHooksDiscoverViralRouteImport.update({
    id: '/api/public/hooks/discover-viral',
    path: '/api/public/hooks/discover-viral',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminWalletGoogleDebugRoute =
  ApiAdminWalletGoogleDebugRouteImport.update({
    id: '/api/admin/wallet/google-debug',
    path: '/api/admin/wallet/google-debug',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminWalletGoogleClassRoute =
  ApiAdminWalletGoogleClassRouteImport.update({
    id: '/api/admin/wallet/google-class',
    path: '/api/admin/wallet/google-class',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/active-confetti': typeof ActiveConfettiRoute
  '/active-loop': typeof ActiveLoopRoute
  '/admin': typeof AdminRouteWithChildren
  '/advertise': typeof AdvertiseRouteWithChildren
  '/auth': typeof AuthRoute
  '/boarding-pass': typeof BoardingPassRoute
  '/chat': typeof ChatRoute
  '/check-in': typeof CheckInRoute
  '/concierge': typeof ConciergeRouteWithChildren
  '/confirmation': typeof ConfirmationRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/create': typeof CreateRoute
  '/data-terms': typeof DataTermsRoute
  '/discover': typeof DiscoverRoute
  '/features': typeof FeaturesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/investors': typeof InvestorsRoute
  '/me': typeof MeRoute
  '/onboarding': typeof OnboardingRoute
  '/passport': typeof PassportRoute
  '/plan': typeof PlanRouteWithChildren
  '/portal': typeof PortalRouteWithChildren
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/quick-generate': typeof QuickGenerateRoute
  '/reservations': typeof ReservationsRoute
  '/scan': typeof ScanRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/taste-tuner': typeof TasteTunerRoute
  '/teams': typeof TeamsRouteWithChildren
  '/terms': typeof TermsRoute
  '/testimonials': typeof TestimonialsRoute
  '/translate': typeof TranslateRoute
  '/viral': typeof ViralRoute
  '/weather': typeof WeatherRoute
  '/admin/ad-analytics': typeof AdminAdAnalyticsRoute
  '/admin/advertisers': typeof AdminAdvertisersRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/launch': typeof AdminLaunchRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/marquee': typeof AdminMarqueeRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/pick-analytics': typeof AdminPickAnalyticsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/venues': typeof AdminVenuesRoute
  '/admin/wallet-debug': typeof AdminWalletDebugRoute
  '/advertise/portal': typeof AdvertisePortalRoute
  '/api/chat': typeof ApiChatRoute
  '/collab/$tripId': typeof CollabTripIdRoute
  '/concierge/passport': typeof ConciergePassportRoute
  '/concierge/profile': typeof ConciergeProfileRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/ideas/$slug': typeof IdeasSlugRoute
  '/plan/preview': typeof PlanPreviewRoute
  '/plan/ready': typeof PlanReadyRoute
  '/portal/achievements': typeof PortalAchievementsRoute
  '/portal/activity': typeof PortalActivityRoute
  '/portal/bookings': typeof PortalBookingsRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal/refer': typeof PortalReferRoute
  '/portal/saved': typeof PortalSavedRoute
  '/portal/viral': typeof PortalViralRoute
  '/recap/$itineraryId': typeof RecapItineraryIdRoute
  '/rsvp/$token': typeof RsvpTokenRoute
  '/rsvp/$tripId': typeof RsvpTripIdRoute
  '/teams/$id': typeof TeamsIdRoute
  '/teams/new': typeof TeamsNewRoute
  '/trips/$id': typeof TripsIdRouteWithChildren
  '/venue/$id': typeof VenueIdRoute
  '/admin/': typeof AdminIndexRoute
  '/advertise/': typeof AdvertiseIndexRoute
  '/concierge/': typeof ConciergeIndexRoute
  '/events/': typeof EventsIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/teams/': typeof TeamsIndexRoute
  '/trips/': typeof TripsIndexRoute
  '/api/public/pick-events': typeof ApiPublicPickEventsRoute
  '/concierge/chat/$threadId': typeof ConciergeChatThreadIdRoute
  '/trips/$id/passport': typeof TripsIdPassportRoute
  '/concierge/chat/': typeof ConciergeChatIndexRoute
  '/api/admin/wallet/google-class': typeof ApiAdminWalletGoogleClassRoute
  '/api/admin/wallet/google-debug': typeof ApiAdminWalletGoogleDebugRoute
  '/api/public/hooks/discover-viral': typeof ApiPublicHooksDiscoverViralRoute
  '/api/public/hooks/tiktok-refresh': typeof ApiPublicHooksTiktokRefreshRoute
  '/api/public/instagram/callback': typeof ApiPublicInstagramCallbackRoute
  '/api/public/tiktok/callback': typeof ApiPublicTiktokCallbackRoute
  '/api/public/wallet/google': typeof ApiPublicWalletGoogleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/active-confetti': typeof ActiveConfettiRoute
  '/active-loop': typeof ActiveLoopRoute
  '/auth': typeof AuthRoute
  '/boarding-pass': typeof BoardingPassRoute
  '/chat': typeof ChatRoute
  '/check-in': typeof CheckInRoute
  '/confirmation': typeof ConfirmationRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/create': typeof CreateRoute
  '/data-terms': typeof DataTermsRoute
  '/discover': typeof DiscoverRoute
  '/features': typeof FeaturesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/investors': typeof InvestorsRoute
  '/me': typeof MeRoute
  '/onboarding': typeof OnboardingRoute
  '/passport': typeof PassportRoute
  '/plan': typeof PlanRouteWithChildren
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/quick-generate': typeof QuickGenerateRoute
  '/reservations': typeof ReservationsRoute
  '/scan': typeof ScanRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/taste-tuner': typeof TasteTunerRoute
  '/terms': typeof TermsRoute
  '/testimonials': typeof TestimonialsRoute
  '/translate': typeof TranslateRoute
  '/viral': typeof ViralRoute
  '/weather': typeof WeatherRoute
  '/admin/ad-analytics': typeof AdminAdAnalyticsRoute
  '/admin/advertisers': typeof AdminAdvertisersRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/launch': typeof AdminLaunchRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/marquee': typeof AdminMarqueeRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/pick-analytics': typeof AdminPickAnalyticsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/venues': typeof AdminVenuesRoute
  '/admin/wallet-debug': typeof AdminWalletDebugRoute
  '/advertise/portal': typeof AdvertisePortalRoute
  '/api/chat': typeof ApiChatRoute
  '/collab/$tripId': typeof CollabTripIdRoute
  '/concierge/passport': typeof ConciergePassportRoute
  '/concierge/profile': typeof ConciergeProfileRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/ideas/$slug': typeof IdeasSlugRoute
  '/plan/preview': typeof PlanPreviewRoute
  '/plan/ready': typeof PlanReadyRoute
  '/portal/achievements': typeof PortalAchievementsRoute
  '/portal/activity': typeof PortalActivityRoute
  '/portal/bookings': typeof PortalBookingsRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal/refer': typeof PortalReferRoute
  '/portal/saved': typeof PortalSavedRoute
  '/portal/viral': typeof PortalViralRoute
  '/recap/$itineraryId': typeof RecapItineraryIdRoute
  '/rsvp/$token': typeof RsvpTokenRoute
  '/rsvp/$tripId': typeof RsvpTripIdRoute
  '/teams/$id': typeof TeamsIdRoute
  '/teams/new': typeof TeamsNewRoute
  '/trips/$id': typeof TripsIdRouteWithChildren
  '/venue/$id': typeof VenueIdRoute
  '/admin': typeof AdminIndexRoute
  '/advertise': typeof AdvertiseIndexRoute
  '/concierge': typeof ConciergeIndexRoute
  '/events': typeof EventsIndexRoute
  '/portal': typeof PortalIndexRoute
  '/teams': typeof TeamsIndexRoute
  '/trips': typeof TripsIndexRoute
  '/api/public/pick-events': typeof ApiPublicPickEventsRoute
  '/concierge/chat/$threadId': typeof ConciergeChatThreadIdRoute
  '/trips/$id/passport': typeof TripsIdPassportRoute
  '/concierge/chat': typeof ConciergeChatIndexRoute
  '/api/admin/wallet/google-class': typeof ApiAdminWalletGoogleClassRoute
  '/api/admin/wallet/google-debug': typeof ApiAdminWalletGoogleDebugRoute
  '/api/public/hooks/discover-viral': typeof ApiPublicHooksDiscoverViralRoute
  '/api/public/hooks/tiktok-refresh': typeof ApiPublicHooksTiktokRefreshRoute
  '/api/public/instagram/callback': typeof ApiPublicInstagramCallbackRoute
  '/api/public/tiktok/callback': typeof ApiPublicTiktokCallbackRoute
  '/api/public/wallet/google': typeof ApiPublicWalletGoogleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/active-confetti': typeof ActiveConfettiRoute
  '/active-loop': typeof ActiveLoopRoute
  '/admin': typeof AdminRouteWithChildren
  '/advertise': typeof AdvertiseRouteWithChildren
  '/auth': typeof AuthRoute
  '/boarding-pass': typeof BoardingPassRoute
  '/chat': typeof ChatRoute
  '/check-in': typeof CheckInRoute
  '/concierge': typeof ConciergeRouteWithChildren
  '/confirmation': typeof ConfirmationRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/create': typeof CreateRoute
  '/data-terms': typeof DataTermsRoute
  '/discover': typeof DiscoverRoute
  '/features': typeof FeaturesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/investors': typeof InvestorsRoute
  '/me': typeof MeRoute
  '/onboarding': typeof OnboardingRoute
  '/passport': typeof PassportRoute
  '/plan': typeof PlanRouteWithChildren
  '/portal': typeof PortalRouteWithChildren
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/quick-generate': typeof QuickGenerateRoute
  '/reservations': typeof ReservationsRoute
  '/scan': typeof ScanRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/taste-tuner': typeof TasteTunerRoute
  '/teams': typeof TeamsRouteWithChildren
  '/terms': typeof TermsRoute
  '/testimonials': typeof TestimonialsRoute
  '/translate': typeof TranslateRoute
  '/viral': typeof ViralRoute
  '/weather': typeof WeatherRoute
  '/admin/ad-analytics': typeof AdminAdAnalyticsRoute
  '/admin/advertisers': typeof AdminAdvertisersRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/launch': typeof AdminLaunchRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/marquee': typeof AdminMarqueeRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/pick-analytics': typeof AdminPickAnalyticsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/venues': typeof AdminVenuesRoute
  '/admin/wallet-debug': typeof AdminWalletDebugRoute
  '/advertise/portal': typeof AdvertisePortalRoute
  '/api/chat': typeof ApiChatRoute
  '/collab/$tripId': typeof CollabTripIdRoute
  '/concierge/passport': typeof ConciergePassportRoute
  '/concierge/profile': typeof ConciergeProfileRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/ideas/$slug': typeof IdeasSlugRoute
  '/plan/preview': typeof PlanPreviewRoute
  '/plan/ready': typeof PlanReadyRoute
  '/portal/achievements': typeof PortalAchievementsRoute
  '/portal/activity': typeof PortalActivityRoute
  '/portal/bookings': typeof PortalBookingsRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal/refer': typeof PortalReferRoute
  '/portal/saved': typeof PortalSavedRoute
  '/portal/viral': typeof PortalViralRoute
  '/recap/$itineraryId': typeof RecapItineraryIdRoute
  '/rsvp/$token': typeof RsvpTokenRoute
  '/rsvp/$tripId': typeof RsvpTripIdRoute
  '/teams/$id': typeof TeamsIdRoute
  '/teams/new': typeof TeamsNewRoute
  '/trips/$id': typeof TripsIdRouteWithChildren
  '/venue/$id': typeof VenueIdRoute
  '/admin/': typeof AdminIndexRoute
  '/advertise/': typeof AdvertiseIndexRoute
  '/concierge/': typeof ConciergeIndexRoute
  '/events/': typeof EventsIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/teams/': typeof TeamsIndexRoute
  '/trips/': typeof TripsIndexRoute
  '/api/public/pick-events': typeof ApiPublicPickEventsRoute
  '/concierge/chat/$threadId': typeof ConciergeChatThreadIdRoute
  '/trips/$id/passport': typeof TripsIdPassportRoute
  '/concierge/chat/': typeof ConciergeChatIndexRoute
  '/api/admin/wallet/google-class': typeof ApiAdminWalletGoogleClassRoute
  '/api/admin/wallet/google-debug': typeof ApiAdminWalletGoogleDebugRoute
  '/api/public/hooks/discover-viral': typeof ApiPublicHooksDiscoverViralRoute
  '/api/public/hooks/tiktok-refresh': typeof ApiPublicHooksTiktokRefreshRoute
  '/api/public/instagram/callback': typeof ApiPublicInstagramCallbackRoute
  '/api/public/tiktok/callback': typeof ApiPublicTiktokCallbackRoute
  '/api/public/wallet/google': typeof ApiPublicWalletGoogleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accessibility'
    | '/active-confetti'
    | '/active-loop'
    | '/admin'
    | '/advertise'
    | '/auth'
    | '/boarding-pass'
    | '/chat'
    | '/check-in'
    | '/concierge'
    | '/confirmation'
    | '/contact'
    | '/cookies'
    | '/create'
    | '/data-terms'
    | '/discover'
    | '/features'
    | '/how-it-works'
    | '/investors'
    | '/me'
    | '/onboarding'
    | '/passport'
    | '/plan'
    | '/portal'
    | '/pricing'
    | '/privacy'
    | '/quick-generate'
    | '/reservations'
    | '/scan'
    | '/sitemap.xml'
    | '/taste-tuner'
    | '/teams'
    | '/terms'
    | '/testimonials'
    | '/translate'
    | '/viral'
    | '/weather'
    | '/admin/ad-analytics'
    | '/admin/advertisers'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/bookings'
    | '/admin/integrations'
    | '/admin/launch'
    | '/admin/login'
    | '/admin/marquee'
    | '/admin/moderation'
    | '/admin/notifications'
    | '/admin/pick-analytics'
    | '/admin/settings'
    | '/admin/testimonials'
    | '/admin/users'
    | '/admin/venues'
    | '/admin/wallet-debug'
    | '/advertise/portal'
    | '/api/chat'
    | '/collab/$tripId'
    | '/concierge/passport'
    | '/concierge/profile'
    | '/events/$eventId'
    | '/ideas/$slug'
    | '/plan/preview'
    | '/plan/ready'
    | '/portal/achievements'
    | '/portal/activity'
    | '/portal/bookings'
    | '/portal/profile'
    | '/portal/refer'
    | '/portal/saved'
    | '/portal/viral'
    | '/recap/$itineraryId'
    | '/rsvp/$token'
    | '/rsvp/$tripId'
    | '/teams/$id'
    | '/teams/new'
    | '/trips/$id'
    | '/venue/$id'
    | '/admin/'
    | '/advertise/'
    | '/concierge/'
    | '/events/'
    | '/portal/'
    | '/teams/'
    | '/trips/'
    | '/api/public/pick-events'
    | '/concierge/chat/$threadId'
    | '/trips/$id/passport'
    | '/concierge/chat/'
    | '/api/admin/wallet/google-class'
    | '/api/admin/wallet/google-debug'
    | '/api/public/hooks/discover-viral'
    | '/api/public/hooks/tiktok-refresh'
    | '/api/public/instagram/callback'
    | '/api/public/tiktok/callback'
    | '/api/public/wallet/google'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accessibility'
    | '/active-confetti'
    | '/active-loop'
    | '/auth'
    | '/boarding-pass'
    | '/chat'
    | '/check-in'
    | '/confirmation'
    | '/contact'
    | '/cookies'
    | '/create'
    | '/data-terms'
    | '/discover'
    | '/features'
    | '/how-it-works'
    | '/investors'
    | '/me'
    | '/onboarding'
    | '/passport'
    | '/plan'
    | '/pricing'
    | '/privacy'
    | '/quick-generate'
    | '/reservations'
    | '/scan'
    | '/sitemap.xml'
    | '/taste-tuner'
    | '/terms'
    | '/testimonials'
    | '/translate'
    | '/viral'
    | '/weather'
    | '/admin/ad-analytics'
    | '/admin/advertisers'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/bookings'
    | '/admin/integrations'
    | '/admin/launch'
    | '/admin/login'
    | '/admin/marquee'
    | '/admin/moderation'
    | '/admin/notifications'
    | '/admin/pick-analytics'
    | '/admin/settings'
    | '/admin/testimonials'
    | '/admin/users'
    | '/admin/venues'
    | '/admin/wallet-debug'
    | '/advertise/portal'
    | '/api/chat'
    | '/collab/$tripId'
    | '/concierge/passport'
    | '/concierge/profile'
    | '/events/$eventId'
    | '/ideas/$slug'
    | '/plan/preview'
    | '/plan/ready'
    | '/portal/achievements'
    | '/portal/activity'
    | '/portal/bookings'
    | '/portal/profile'
    | '/portal/refer'
    | '/portal/saved'
    | '/portal/viral'
    | '/recap/$itineraryId'
    | '/rsvp/$token'
    | '/rsvp/$tripId'
    | '/teams/$id'
    | '/teams/new'
    | '/trips/$id'
    | '/venue/$id'
    | '/admin'
    | '/advertise'
    | '/concierge'
    | '/events'
    | '/portal'
    | '/teams'
    | '/trips'
    | '/api/public/pick-events'
    | '/concierge/chat/$threadId'
    | '/trips/$id/passport'
    | '/concierge/chat'
    | '/api/admin/wallet/google-class'
    | '/api/admin/wallet/google-debug'
    | '/api/public/hooks/discover-viral'
    | '/api/public/hooks/tiktok-refresh'
    | '/api/public/instagram/callback'
    | '/api/public/tiktok/callback'
    | '/api/public/wallet/google'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/accessibility'
    | '/active-confetti'
    | '/active-loop'
    | '/admin'
    | '/advertise'
    | '/auth'
    | '/boarding-pass'
    | '/chat'
    | '/check-in'
    | '/concierge'
    | '/confirmation'
    | '/contact'
    | '/cookies'
    | '/create'
    | '/data-terms'
    | '/discover'
    | '/features'
    | '/how-it-works'
    | '/investors'
    | '/me'
    | '/onboarding'
    | '/passport'
    | '/plan'
    | '/portal'
    | '/pricing'
    | '/privacy'
    | '/quick-generate'
    | '/reservations'
    | '/scan'
    | '/sitemap.xml'
    | '/taste-tuner'
    | '/teams'
    | '/terms'
    | '/testimonials'
    | '/translate'
    | '/viral'
    | '/weather'
    | '/admin/ad-analytics'
    | '/admin/advertisers'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/bookings'
    | '/admin/integrations'
    | '/admin/launch'
    | '/admin/login'
    | '/admin/marquee'
    | '/admin/moderation'
    | '/admin/notifications'
    | '/admin/pick-analytics'
    | '/admin/settings'
    | '/admin/testimonials'
    | '/admin/users'
    | '/admin/venues'
    | '/admin/wallet-debug'
    | '/advertise/portal'
    | '/api/chat'
    | '/collab/$tripId'
    | '/concierge/passport'
    | '/concierge/profile'
    | '/events/$eventId'
    | '/ideas/$slug'
    | '/plan/preview'
    | '/plan/ready'
    | '/portal/achievements'
    | '/portal/activity'
    | '/portal/bookings'
    | '/portal/profile'
    | '/portal/refer'
    | '/portal/saved'
    | '/portal/viral'
    | '/recap/$itineraryId'
    | '/rsvp/$token'
    | '/rsvp/$tripId'
    | '/teams/$id'
    | '/teams/new'
    | '/trips/$id'
    | '/venue/$id'
    | '/admin/'
    | '/advertise/'
    | '/concierge/'
    | '/events/'
    | '/portal/'
    | '/teams/'
    | '/trips/'
    | '/api/public/pick-events'
    | '/concierge/chat/$threadId'
    | '/trips/$id/passport'
    | '/concierge/chat/'
    | '/api/admin/wallet/google-class'
    | '/api/admin/wallet/google-debug'
    | '/api/public/hooks/discover-viral'
    | '/api/public/hooks/tiktok-refresh'
    | '/api/public/instagram/callback'
    | '/api/public/tiktok/callback'
    | '/api/public/wallet/google'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccessibilityRoute: typeof AccessibilityRoute
  ActiveConfettiRoute: typeof ActiveConfettiRoute
  ActiveLoopRoute: typeof ActiveLoopRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdvertiseRoute: typeof AdvertiseRouteWithChildren
  AuthRoute: typeof AuthRoute
  BoardingPassRoute: typeof BoardingPassRoute
  ChatRoute: typeof ChatRoute
  CheckInRoute: typeof CheckInRoute
  ConciergeRoute: typeof ConciergeRouteWithChildren
  ConfirmationRoute: typeof ConfirmationRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  CreateRoute: typeof CreateRoute
  DataTermsRoute: typeof DataTermsRoute
  DiscoverRoute: typeof DiscoverRoute
  FeaturesRoute: typeof FeaturesRoute
  HowItWorksRoute: typeof HowItWorksRoute
  InvestorsRoute: typeof InvestorsRoute
  MeRoute: typeof MeRoute
  OnboardingRoute: typeof OnboardingRoute
  PassportRoute: typeof PassportRoute
  PlanRoute: typeof PlanRouteWithChildren
  PortalRoute: typeof PortalRouteWithChildren
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  QuickGenerateRoute: typeof QuickGenerateRoute
  ReservationsRoute: typeof ReservationsRoute
  ScanRoute: typeof ScanRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TasteTunerRoute: typeof TasteTunerRoute
  TeamsRoute: typeof TeamsRouteWithChildren
  TermsRoute: typeof TermsRoute
  TestimonialsRoute: typeof TestimonialsRoute
  TranslateRoute: typeof TranslateRoute
  ViralRoute: typeof ViralRoute
  WeatherRoute: typeof WeatherRoute
  ApiChatRoute: typeof ApiChatRoute
  CollabTripIdRoute: typeof CollabTripIdRoute
  EventsEventIdRoute: typeof EventsEventIdRoute
  IdeasSlugRoute: typeof IdeasSlugRoute
  RecapItineraryIdRoute: typeof RecapItineraryIdRoute
  RsvpTokenRoute: typeof RsvpTokenRoute
  RsvpTripIdRoute: typeof RsvpTripIdRoute
  TripsIdRoute: typeof TripsIdRouteWithChildren
  VenueIdRoute: typeof VenueIdRoute
  EventsIndexRoute: typeof EventsIndexRoute
  TripsIndexRoute: typeof TripsIndexRoute
  ApiPublicPickEventsRoute: typeof ApiPublicPickEventsRoute
  ApiAdminWalletGoogleClassRoute: typeof ApiAdminWalletGoogleClassRoute
  ApiAdminWalletGoogleDebugRoute: typeof ApiAdminWalletGoogleDebugRoute
  ApiPublicHooksDiscoverViralRoute: typeof ApiPublicHooksDiscoverViralRoute
  ApiPublicHooksTiktokRefreshRoute: typeof ApiPublicHooksTiktokRefreshRoute
  ApiPublicInstagramCallbackRoute: typeof ApiPublicInstagramCallbackRoute
  ApiPublicTiktokCallbackRoute: typeof ApiPublicTiktokCallbackRoute
  ApiPublicWalletGoogleRoute: typeof ApiPublicWalletGoogleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/weather': {
      id: '/weather'
      path: '/weather'
      fullPath: '/weather'
      preLoaderRoute: typeof WeatherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/viral': {
      id: '/viral'
      path: '/viral'
      fullPath: '/viral'
      preLoaderRoute: typeof ViralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/translate': {
      id: '/translate'
      path: '/translate'
      fullPath: '/translate'
      preLoaderRoute: typeof TranslateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taste-tuner': {
      id: '/taste-tuner'
      path: '/taste-tuner'
      fullPath: '/taste-tuner'
      preLoaderRoute: typeof TasteTunerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservations': {
      id: '/reservations'
      path: '/reservations'
      fullPath: '/reservations'
      preLoaderRoute: typeof ReservationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quick-generate': {
      id: '/quick-generate'
      path: '/quick-generate'
      fullPath: '/quick-generate'
      preLoaderRoute: typeof QuickGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passport': {
      id: '/passport'
      path: '/passport'
      fullPath: '/passport'
      preLoaderRoute: typeof PassportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investors': {
      id: '/investors'
      path: '/investors'
      fullPath: '/investors'
      preLoaderRoute: typeof InvestorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-terms': {
      id: '/data-terms'
      path: '/data-terms'
      fullPath: '/data-terms'
      preLoaderRoute: typeof DataTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmation': {
      id: '/confirmation'
      path: '/confirmation'
      fullPath: '/confirmation'
      preLoaderRoute: typeof ConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concierge': {
      id: '/concierge'
      path: '/concierge'
      fullPath: '/concierge'
      preLoaderRoute: typeof ConciergeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-in': {
      id: '/check-in'
      path: '/check-in'
      fullPath: '/check-in'
      preLoaderRoute: typeof CheckInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boarding-pass': {
      id: '/boarding-pass'
      path: '/boarding-pass'
      fullPath: '/boarding-pass'
      preLoaderRoute: typeof BoardingPassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advertise': {
      id: '/advertise'
      path: '/advertise'
      fullPath: '/advertise'
      preLoaderRoute: typeof AdvertiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/active-loop': {
      id: '/active-loop'
      path: '/active-loop'
      fullPath: '/active-loop'
      preLoaderRoute: typeof ActiveLoopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/active-confetti': {
      id: '/active-confetti'
      path: '/active-confetti'
      fullPath: '/active-confetti'
      preLoaderRoute: typeof ActiveConfettiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/': {
      id: '/trips/'
      path: '/trips'
      fullPath: '/trips/'
      preLoaderRoute: typeof TripsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/': {
      id: '/teams/'
      path: '/'
      fullPath: '/teams/'
      preLoaderRoute: typeof TeamsIndexRouteImport
      parentRoute: typeof TeamsRoute
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concierge/': {
      id: '/concierge/'
      path: '/'
      fullPath: '/concierge/'
      preLoaderRoute: typeof ConciergeIndexRouteImport
      parentRoute: typeof ConciergeRoute
    }
    '/advertise/': {
      id: '/advertise/'
      path: '/'
      fullPath: '/advertise/'
      preLoaderRoute: typeof AdvertiseIndexRouteImport
      parentRoute: typeof AdvertiseRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/venue/$id': {
      id: '/venue/$id'
      path: '/venue/$id'
      fullPath: '/venue/$id'
      preLoaderRoute: typeof VenueIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/$id': {
      id: '/trips/$id'
      path: '/trips/$id'
      fullPath: '/trips/$id'
      preLoaderRoute: typeof TripsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/new': {
      id: '/teams/new'
      path: '/new'
      fullPath: '/teams/new'
      preLoaderRoute: typeof TeamsNewRouteImport
      parentRoute: typeof TeamsRoute
    }
    '/teams/$id': {
      id: '/teams/$id'
      path: '/$id'
      fullPath: '/teams/$id'
      preLoaderRoute: typeof TeamsIdRouteImport
      parentRoute: typeof TeamsRoute
    }
    '/rsvp/$tripId': {
      id: '/rsvp/$tripId'
      path: '/rsvp/$tripId'
      fullPath: '/rsvp/$tripId'
      preLoaderRoute: typeof RsvpTripIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rsvp/$token': {
      id: '/rsvp/$token'
      path: '/rsvp/$token'
      fullPath: '/rsvp/$token'
      preLoaderRoute: typeof RsvpTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recap/$itineraryId': {
      id: '/recap/$itineraryId'
      path: '/recap/$itineraryId'
      fullPath: '/recap/$itineraryId'
      preLoaderRoute: typeof RecapItineraryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/viral': {
      id: '/portal/viral'
      path: '/viral'
      fullPath: '/portal/viral'
      preLoaderRoute: typeof PortalViralRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/saved': {
      id: '/portal/saved'
      path: '/saved'
      fullPath: '/portal/saved'
      preLoaderRoute: typeof PortalSavedRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/refer': {
      id: '/portal/refer'
      path: '/refer'
      fullPath: '/portal/refer'
      preLoaderRoute: typeof PortalReferRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/profile': {
      id: '/portal/profile'
      path: '/profile'
      fullPath: '/portal/profile'
      preLoaderRoute: typeof PortalProfileRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/bookings': {
      id: '/portal/bookings'
      path: '/bookings'
      fullPath: '/portal/bookings'
      preLoaderRoute: typeof PortalBookingsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/activity': {
      id: '/portal/activity'
      path: '/activity'
      fullPath: '/portal/activity'
      preLoaderRoute: typeof PortalActivityRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/achievements': {
      id: '/portal/achievements'
      path: '/achievements'
      fullPath: '/portal/achievements'
      preLoaderRoute: typeof PortalAchievementsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/plan/ready': {
      id: '/plan/ready'
      path: '/ready'
      fullPath: '/plan/ready'
      preLoaderRoute: typeof PlanReadyRouteImport
      parentRoute: typeof PlanRoute
    }
    '/plan/preview': {
      id: '/plan/preview'
      path: '/preview'
      fullPath: '/plan/preview'
      preLoaderRoute: typeof PlanPreviewRouteImport
      parentRoute: typeof PlanRoute
    }
    '/ideas/$slug': {
      id: '/ideas/$slug'
      path: '/ideas/$slug'
      fullPath: '/ideas/$slug'
      preLoaderRoute: typeof IdeasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concierge/profile': {
      id: '/concierge/profile'
      path: '/profile'
      fullPath: '/concierge/profile'
      preLoaderRoute: typeof ConciergeProfileRouteImport
      parentRoute: typeof ConciergeRoute
    }
    '/concierge/passport': {
      id: '/concierge/passport'
      path: '/passport'
      fullPath: '/concierge/passport'
      preLoaderRoute: typeof ConciergePassportRouteImport
      parentRoute: typeof ConciergeRoute
    }
    '/collab/$tripId': {
      id: '/collab/$tripId'
      path: '/collab/$tripId'
      fullPath: '/collab/$tripId'
      preLoaderRoute: typeof CollabTripIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advertise/portal': {
      id: '/advertise/portal'
      path: '/portal'
      fullPath: '/advertise/portal'
      preLoaderRoute: typeof AdvertisePortalRouteImport
      parentRoute: typeof AdvertiseRoute
    }
    '/admin/wallet-debug': {
      id: '/admin/wallet-debug'
      path: '/wallet-debug'
      fullPath: '/admin/wallet-debug'
      preLoaderRoute: typeof AdminWalletDebugRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/venues': {
      id: '/admin/venues'
      path: '/venues'
      fullPath: '/admin/venues'
      preLoaderRoute: typeof AdminVenuesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/testimonials': {
      id: '/admin/testimonials'
      path: '/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AdminTestimonialsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pick-analytics': {
      id: '/admin/pick-analytics'
      path: '/pick-analytics'
      fullPath: '/admin/pick-analytics'
      preLoaderRoute: typeof AdminPickAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/moderation': {
      id: '/admin/moderation'
      path: '/moderation'
      fullPath: '/admin/moderation'
      preLoaderRoute: typeof AdminModerationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/marquee': {
      id: '/admin/marquee'
      path: '/marquee'
      fullPath: '/admin/marquee'
      preLoaderRoute: typeof AdminMarqueeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/launch': {
      id: '/admin/launch'
      path: '/launch'
      fullPath: '/admin/launch'
      preLoaderRoute: typeof AdminLaunchRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/integrations': {
      id: '/admin/integrations'
      path: '/integrations'
      fullPath: '/admin/integrations'
      preLoaderRoute: typeof AdminIntegrationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/advertisers': {
      id: '/admin/advertisers'
      path: '/advertisers'
      fullPath: '/admin/advertisers'
      preLoaderRoute: typeof AdminAdvertisersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ad-analytics': {
      id: '/admin/ad-analytics'
      path: '/ad-analytics'
      fullPath: '/admin/ad-analytics'
      preLoaderRoute: typeof AdminAdAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/concierge/chat/': {
      id: '/concierge/chat/'
      path: '/chat'
      fullPath: '/concierge/chat/'
      preLoaderRoute: typeof ConciergeChatIndexRouteImport
      parentRoute: typeof ConciergeRoute
    }
    '/trips/$id/passport': {
      id: '/trips/$id/passport'
      path: '/passport'
      fullPath: '/trips/$id/passport'
      preLoaderRoute: typeof TripsIdPassportRouteImport
      parentRoute: typeof TripsIdRoute
    }
    '/concierge/chat/$threadId': {
      id: '/concierge/chat/$threadId'
      path: '/chat/$threadId'
      fullPath: '/concierge/chat/$threadId'
      preLoaderRoute: typeof ConciergeChatThreadIdRouteImport
      parentRoute: typeof ConciergeRoute
    }
    '/api/public/pick-events': {
      id: '/api/public/pick-events'
      path: '/api/public/pick-events'
      fullPath: '/api/public/pick-events'
      preLoaderRoute: typeof ApiPublicPickEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/wallet/google': {
      id: '/api/public/wallet/google'
      path: '/api/public/wallet/google'
      fullPath: '/api/public/wallet/google'
      preLoaderRoute: typeof ApiPublicWalletGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/tiktok/callback': {
      id: '/api/public/tiktok/callback'
      path: '/api/public/tiktok/callback'
      fullPath: '/api/public/tiktok/callback'
      preLoaderRoute: typeof ApiPublicTiktokCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/instagram/callback': {
      id: '/api/public/instagram/callback'
      path: '/api/public/instagram/callback'
      fullPath: '/api/public/instagram/callback'
      preLoaderRoute: typeof ApiPublicInstagramCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/tiktok-refresh': {
      id: '/api/public/hooks/tiktok-refresh'
      path: '/api/public/hooks/tiktok-refresh'
      fullPath: '/api/public/hooks/tiktok-refresh'
      preLoaderRoute: typeof ApiPublicHooksTiktokRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/discover-viral': {
      id: '/api/public/hooks/discover-viral'
      path: '/api/public/hooks/discover-viral'
      fullPath: '/api/public/hooks/discover-viral'
      preLoaderRoute: typeof ApiPublicHooksDiscoverViralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/wallet/google-debug': {
      id: '/api/admin/wallet/google-debug'
      path: '/api/admin/wallet/google-debug'
      fullPath: '/api/admin/wallet/google-debug'
      preLoaderRoute: typeof ApiAdminWalletGoogleDebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/wallet/google-class': {
      id: '/api/admin/wallet/google-class'
      path: '/api/admin/wallet/google-class'
      fullPath: '/api/admin/wallet/google-class'
      preLoaderRoute: typeof ApiAdminWalletGoogleClassRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAdAnalyticsRoute: typeof AdminAdAnalyticsRoute
  AdminAdvertisersRoute: typeof AdminAdvertisersRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminIntegrationsRoute: typeof AdminIntegrationsRoute
  AdminLaunchRoute: typeof AdminLaunchRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMarqueeRoute: typeof AdminMarqueeRoute
  AdminModerationRoute: typeof AdminModerationRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminPickAnalyticsRoute: typeof AdminPickAnalyticsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTestimonialsRoute: typeof AdminTestimonialsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVenuesRoute: typeof AdminVenuesRoute
  AdminWalletDebugRoute: typeof AdminWalletDebugRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdAnalyticsRoute: AdminAdAnalyticsRoute,
  AdminAdvertisersRoute: AdminAdvertisersRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminBookingsRoute: AdminBookingsRoute,
  AdminIntegrationsRoute: AdminIntegrationsRoute,
  AdminLaunchRoute: AdminLaunchRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMarqueeRoute: AdminMarqueeRoute,
  AdminModerationRoute: AdminModerationRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminPickAnalyticsRoute: AdminPickAnalyticsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTestimonialsRoute: AdminTestimonialsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVenuesRoute: AdminVenuesRoute,
  AdminWalletDebugRoute: AdminWalletDebugRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AdvertiseRouteChildren {
  AdvertisePortalRoute: typeof AdvertisePortalRoute
  AdvertiseIndexRoute: typeof AdvertiseIndexRoute
}

const AdvertiseRouteChildren: AdvertiseRouteChildren = {
  AdvertisePortalRoute: AdvertisePortalRoute,
  AdvertiseIndexRoute: AdvertiseIndexRoute,
}

const AdvertiseRouteWithChildren = AdvertiseRoute._addFileChildren(
  AdvertiseRouteChildren,
)

interface ConciergeRouteChildren {
  ConciergePassportRoute: typeof ConciergePassportRoute
  ConciergeProfileRoute: typeof ConciergeProfileRoute
  ConciergeIndexRoute: typeof ConciergeIndexRoute
  ConciergeChatThreadIdRoute: typeof ConciergeChatThreadIdRoute
  ConciergeChatIndexRoute: typeof ConciergeChatIndexRoute
}

const ConciergeRouteChildren: ConciergeRouteChildren = {
  ConciergePassportRoute: ConciergePassportRoute,
  ConciergeProfileRoute: ConciergeProfileRoute,
  ConciergeIndexRoute: ConciergeIndexRoute,
  ConciergeChatThreadIdRoute: ConciergeChatThreadIdRoute,
  ConciergeChatIndexRoute: ConciergeChatIndexRoute,
}

const ConciergeRouteWithChildren = ConciergeRoute._addFileChildren(
  ConciergeRouteChildren,
)

interface PlanRouteChildren {
  PlanPreviewRoute: typeof PlanPreviewRoute
  PlanReadyRoute: typeof PlanReadyRoute
}

const PlanRouteChildren: PlanRouteChildren = {
  PlanPreviewRoute: PlanPreviewRoute,
  PlanReadyRoute: PlanReadyRoute,
}

const PlanRouteWithChildren = PlanRoute._addFileChildren(PlanRouteChildren)

interface PortalRouteChildren {
  PortalAchievementsRoute: typeof PortalAchievementsRoute
  PortalActivityRoute: typeof PortalActivityRoute
  PortalBookingsRoute: typeof PortalBookingsRoute
  PortalProfileRoute: typeof PortalProfileRoute
  PortalReferRoute: typeof PortalReferRoute
  PortalSavedRoute: typeof PortalSavedRoute
  PortalViralRoute: typeof PortalViralRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalAchievementsRoute: PortalAchievementsRoute,
  PortalActivityRoute: PortalActivityRoute,
  PortalBookingsRoute: PortalBookingsRoute,
  PortalProfileRoute: PortalProfileRoute,
  PortalReferRoute: PortalReferRoute,
  PortalSavedRoute: PortalSavedRoute,
  PortalViralRoute: PortalViralRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

interface TeamsRouteChildren {
  TeamsIdRoute: typeof TeamsIdRoute
  TeamsNewRoute: typeof TeamsNewRoute
  TeamsIndexRoute: typeof TeamsIndexRoute
}

const TeamsRouteChildren: TeamsRouteChildren = {
  TeamsIdRoute: TeamsIdRoute,
  TeamsNewRoute: TeamsNewRoute,
  TeamsIndexRoute: TeamsIndexRoute,
}

const TeamsRouteWithChildren = TeamsRoute._addFileChildren(TeamsRouteChildren)

interface TripsIdRouteChildren {
  TripsIdPassportRoute: typeof TripsIdPassportRoute
}

const TripsIdRouteChildren: TripsIdRouteChildren = {
  TripsIdPassportRoute: TripsIdPassportRoute,
}

const TripsIdRouteWithChildren =
  TripsIdRoute._addFileChildren(TripsIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccessibilityRoute: AccessibilityRoute,
  ActiveConfettiRoute: ActiveConfettiRoute,
  ActiveLoopRoute: ActiveLoopRoute,
  AdminRoute: AdminRouteWithChildren,
  AdvertiseRoute: AdvertiseRouteWithChildren,
  AuthRoute: AuthRoute,
  BoardingPassRoute: BoardingPassRoute,
  ChatRoute: ChatRoute,
  CheckInRoute: CheckInRoute,
  ConciergeRoute: ConciergeRouteWithChildren,
  ConfirmationRoute: ConfirmationRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  CreateRoute: CreateRoute,
  DataTermsRoute: DataTermsRoute,
  DiscoverRoute: DiscoverRoute,
  FeaturesRoute: FeaturesRoute,
  HowItWorksRoute: HowItWorksRoute,
  InvestorsRoute: InvestorsRoute,
  MeRoute: MeRoute,
  OnboardingRoute: OnboardingRoute,
  PassportRoute: PassportRoute,
  PlanRoute: PlanRouteWithChildren,
  PortalRoute: PortalRouteWithChildren,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  QuickGenerateRoute: QuickGenerateRoute,
  ReservationsRoute: ReservationsRoute,
  ScanRoute: ScanRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TasteTunerRoute: TasteTunerRoute,
  TeamsRoute: TeamsRouteWithChildren,
  TermsRoute: TermsRoute,
  TestimonialsRoute: TestimonialsRoute,
  TranslateRoute: TranslateRoute,
  ViralRoute: ViralRoute,
  WeatherRoute: WeatherRoute,
  ApiChatRoute: ApiChatRoute,
  CollabTripIdRoute: CollabTripIdRoute,
  EventsEventIdRoute: EventsEventIdRoute,
  IdeasSlugRoute: IdeasSlugRoute,
  RecapItineraryIdRoute: RecapItineraryIdRoute,
  RsvpTokenRoute: RsvpTokenRoute,
  RsvpTripIdRoute: RsvpTripIdRoute,
  TripsIdRoute: TripsIdRouteWithChildren,
  VenueIdRoute: VenueIdRoute,
  EventsIndexRoute: EventsIndexRoute,
  TripsIndexRoute: TripsIndexRoute,
  ApiPublicPickEventsRoute: ApiPublicPickEventsRoute,
  ApiAdminWalletGoogleClassRoute: ApiAdminWalletGoogleClassRoute,
  ApiAdminWalletGoogleDebugRoute: ApiAdminWalletGoogleDebugRoute,
  ApiPublicHooksDiscoverViralRoute: ApiPublicHooksDiscoverViralRoute,
  ApiPublicHooksTiktokRefreshRoute: ApiPublicHooksTiktokRefreshRoute,
  ApiPublicInstagramCallbackRoute: ApiPublicInstagramCallbackRoute,
  ApiPublicTiktokCallbackRoute: ApiPublicTiktokCallbackRoute,
  ApiPublicWalletGoogleRoute: ApiPublicWalletGoogleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
