-- Seed social_venue_signals for DC (city_slug='dmv') from dc-venues-seed.json
-- Idempotent: clears prior seed rows first. Review columns vs live schema before running.
begin;

delete from public.social_venue_signals where city_slug = 'dmv' and generation_batch = 'dc-seed-v1';

insert into public.social_venue_signals
  (venue_name, venue_slug, city_slug, category, signal_type, platform, engagement_score, sentiment, snippet, neighborhood, hashtags, outing_tags, is_active, collected_at, generation_batch)
values
  ('Albi', 'albi', 'dmv', 'Fine Dining', 'popular', 'tiktok', 76, 'positive', 'Michael Rafidi''s love letter to Palestinian and Levantine cooking. Fire-kissed meats and vegetables, sumac-bright salads, and house-baked breads in a stunning Navy Yard dining room.', 'Navy Yard', '#romantic,#upscale,#cultural,#firecooked', ARRAY['Dinner Night','Couples Night','Group Night Out','Best Friends Night','Birthday Night','Anniversary Night','Fine Dining Night','Luxury Dinner Night','Soft Life Night','VIP Night']::text[], true, now(), 'dc-seed-v1'),
  ('Jônt', 'jont', 'dmv', 'Fine Dining', 'popular', 'instagram', 83, 'positive', 'Chef Ryan Ratino''s 2-Michelin-star tasting menu blending American technique with Japanese precision. One of DC''s most exclusive dinner experiences with only 16 seats.', '14th Street Corridor', '#intimate,#omakase,#upscale,#avantgarde', ARRAY['Dinner Night','Couples Night','Group Night Out','Best Friends Night','Birthday Night','Anniversary Night','Fine Dining Night','Luxury Dinner Night','Soft Life Night','VIP Night','Sushi Night']::text[], true, now(), 'dc-seed-v1'),
  ('Moon Rabbit', 'moon-rabbit', 'dmv', 'Dining', 'popular', 'tiktok', 91, 'positive', 'Chef Kevin Tien''s contemporary Vietnamese cooking is bold, precise, and deeply personal. Near the National Mall with some of DC''s most beautifully plated dishes.', 'Penn Quarter', '#upscale,#modern,#cultural,#elegant', ARRAY['Dinner Night','Couples Night','Group Night Out','Best Friends Night','Birthday Night','Fine Dining Night','Luxury Dinner Night','Soft Life Night','VIP Night','Anniversary Night']::text[], true, now(), 'dc-seed-v1'),
  ('Masseria', 'masseria', 'dmv', 'Fine Dining', 'popular', 'instagram', 75, 'positive', 'A Michelin-starred Italian farmhouse hidden in the Union Market district. Nicholas Stefanelli''s Southern Italian tasting menus are some of DC''s most transporting experiences.', 'Union Market', '#rusticchic,#romantic,#upscale,#pastoral', ARRAY['Dinner Night','Couples Night','Group Night Out','Best Friends Night','Birthday Night','Anniversary Night','Fine Dining Night','Luxury Dinner Night','Soft Life Night','VIP Night']::text[], true, now(), 'dc-seed-v1'),
  ('Pascual', 'pascual', 'dmv', 'Dining', 'popular', 'tiktok', 90, 'positive', 'Chef Isabel Coss brings refined Mexican technique and seasonal ingredients to this celebrated Navy Yard newcomer. Mezcal cocktails and masa-driven dishes in a lively, colorful setting.', 'Ivy City / NoMa', '#vibrant,#festive,#modern,#farmtotable', ARRAY['Dinner Night','Couples Night','Group Night Out','Best Friends Night','Birthday Night']::text[], true, now(), 'dc-seed-v1'),
  ('Bresca', 'bresca', 'dmv', 'Fine Dining', 'popular', 'instagram', 89, 'positive', 'Ryan Ratino''s approachable companion to Jônt. Whimsical, art-forward fine dining on 14th Street — the tasting menu changes seasonally and always surprises.', '14th Street Corridor', '#whimsical,#creative,#intimate,#artistic', ARRAY['Dinner Night','Couples Night','Group Night Out','Best Friends Night','Birthday Night','Anniversary Night','Fine Dining Night','Luxury Dinner Night','Soft Life Night']::text[], true, now(), 'dc-seed-v1'),
  ('The Dabney', 'the-dabney', 'dmv', 'Dining', 'popular', 'tiktok', 82, 'positive', 'Tucked into Blagden Alley in Shaw, this Michelin-starred gem celebrates Mid-Atlantic ingredients cooked over wood fire. One of DC''s most beloved neighborhood restaurants.', 'Shaw', '#cozy,#rustic,#seasonal,#neighborhoodgem', ARRAY['Dinner Night','Couples Night','Group Night Out','Best Friends Night','Birthday Night']::text[], true, now(), 'dc-seed-v1'),
  ('Oyster Oyster', 'oyster-oyster', 'dmv', 'Dining', 'popular', 'instagram', 72, 'positive', 'Chef Rob Rubba''s plant-forward, sustainability-focused tasting menu with a focus on fungi, oysters, and hyper-local ingredients. A Michelin green star recipient.', 'Shaw', '#ecoconscious,#creative,#intimate,#trendy', ARRAY['Dinner Night','Couples Night','Group Night Out','Best Friends Night','Birthday Night','Anniversary Night','Seafood Night']::text[], true, now(), 'dc-seed-v1'),
  ('minibar by José Andrés', 'minibar', 'dmv', 'Fine Dining', 'popular', 'tiktok', 70, 'positive', '2-Michelin-star avant-garde laboratory from culinary icon José Andrés. A multi-course sensory experience with only 12 seats. One of America''s most influential restaurants.', 'Penn Quarter', '#avantgarde,#theatrical,#exclusive,#mindblowing', ARRAY['Dinner Night','Couples Night','Group Night Out','Best Friends Night','Birthday Night','Fine Dining Night','Luxury Dinner Night','Soft Life Night']::text[], true, now(), 'dc-seed-v1'),
  ('Pineapple and Pearls', 'pineapple-and-pearls', 'dmv', 'Fine Dining', 'popular', 'instagram', 79, 'positive', 'Aaron Silverman''s most extravagant expression — an all-inclusive, tips-included tasting menu dinner on Capitol Hill that reimagines what a special night out can be.', 'Capitol Hill', '#luxurious,#playful,#celebratory,#overthetop', ARRAY['Dinner Night','Couples Night','Group Night Out','Best Friends Night','Birthday Night','Fine Dining Night','Luxury Dinner Night','Soft Life Night']::text[], true, now(), 'dc-seed-v1'),
  ('Sfoglina', 'sfoglina', 'dmv', 'Dining', 'popular', 'tiktok', 71, 'positive', 'James Beard-nominated chef Amy Brandwein''s house-made pasta restaurant. A neighborhood favorite for fresh tagliatelle, tortellini, and Roman classics in a warm setting.', 'Van Ness / Tenleytown', '#cozy,#romantic,#neighborhood,#handmade', ARRAY['Dinner Night','Couples Night','Group Night Out','Best Friends Night','Birthday Night','Anniversary Night']::text[], true, now(), 'dc-seed-v1'),
  ('Compass Rose', 'compass-rose', 'dmv', 'Dining', 'popular', 'instagram', 83, 'positive', 'Street food from around the world in a gorgeous rowhouse with a dreamy courtyard. The khachapuri (Georgian cheese bread) is legendary. Perfect for groups and adventurous eaters.', '14th Street Corridor', '#eclectic,#adventurous,#social,#global', ARRAY['Dinner Night','Couples Night','Group Night Out','Best Friends Night','Birthday Night']::text[], true, now(), 'dc-seed-v1'),
  ('Service Bar', 'service-bar', 'dmv', 'Nightlife', 'popular', 'tiktok', 90, 'positive', 'Ranked #23 on North America''s 50 Best Bars 2026. DC''s premier craft cocktail destination — serious, inventive drinks in an intimate setting on U Street. Industry insiders'' favorite.', 'U Street Corridor', '#craftcocktail,#industryfavorite,#intimate,#seriousdrinker', ARRAY['Chill Night','Bar Hop','Happy Hour','Group Night Out','Girls Night','Guys Night','Couples Night','Best Friends Night','Anniversary Night','Lounge Night','After-Hours Night']::text[], true, now(), 'dc-seed-v1'),
  ('Death & Co DC', 'death-and-co-dc', 'dmv', 'Nightlife', 'popular', 'instagram', 90, 'positive', 'The DC outpost of the legendary New York cocktail bar. Dark, moody, and meticulously crafted — Death & Co brings NYC cocktail culture to DC with its own local twist.', 'Shaw / Dupont Circle', '#upscale,#craftcocktail,#darkmoody,#famous', ARRAY['Chill Night','Bar Hop','Happy Hour','Group Night Out','Girls Night','Guys Night','Couples Night','Best Friends Night','Fine Dining Night','Luxury Dinner Night','Soft Life Night','VIP Night','Anniversary Night','Lounge Night','After-Hours Night']::text[], true, now(), 'dc-seed-v1'),
  ('Flight Club DC', 'flight-club-dc', 'dmv', 'Nightlife', 'popular', 'tiktok', 75, 'positive', 'Social darts reimagined for a night out. Automated scoring, craft cocktails, and shareable food in a massive Penn Quarter venue. Perfect for groups who want fun and drinks.', 'Penn Quarter', '#social,#fun,#competitive,#upscalecasual', ARRAY['Chill Night','Bar Hop','Happy Hour','Group Night Out','Girls Night','Guys Night','Couples Night','Best Friends Night','Fine Dining Night','Luxury Dinner Night','Soft Life Night','VIP Night','Anniversary Night','Club Night','Turn-Up Night','After-Hours Night']::text[], true, now(), 'dc-seed-v1'),
  ('Off the Record', 'off-the-record', 'dmv', 'Nightlife', 'popular', 'instagram', 78, 'positive', 'The basement bar of the Hay-Adams Hotel, a block from the White House. DC''s most storied watering hole — where senators, diplomats, and power brokers have gathered for decades.', 'Downtown / White House', '#historic,#political,#powerscene,#underground', ARRAY['Chill Night','Bar Hop','Happy Hour','Group Night Out','Girls Night','Guys Night','Couples Night','Best Friends Night']::text[], true, now(), 'dc-seed-v1'),
  ('Madam''s Organ', 'madams-organ', 'dmv', 'Live Music', 'popular', 'tiktok', 93, 'positive', 'Adams Morgan''s most iconic live music bar. Blues, soul, and funk every night, cheap drinks, and a rooftop with city views. The heartbeat of DC''s nightlife scene since 1990.', 'Adams Morgan', '#divechic,#livemusic,#bohemian,#legendary', ARRAY['Chill Night','Bar Hop','Happy Hour','Group Night Out','Girls Night','Guys Night','Couples Night','Best Friends Night','Jazz Night','Live Music Night']::text[], true, now(), 'dc-seed-v1'),
  ('Puttery', 'puttery', 'dmv', 'Nightlife', 'popular', 'instagram', 74, 'positive', 'Multi-course mini golf with craft cocktails and DJ music. A buzzy, social experience in Penn Quarter that''s become DC''s go-to for group birthdays and date nights.', 'Penn Quarter / Chinatown', '#fun,#social,#groupactivity,#upscalecasual', ARRAY['Chill Night','Bar Hop','Happy Hour','Group Night Out','Girls Night','Guys Night','Couples Night','Best Friends Night','Fine Dining Night','Luxury Dinner Night','Soft Life Night','VIP Night','Anniversary Night']::text[], true, now(), 'dc-seed-v1'),
  ('Harp & Cask', 'harp-and-cask', 'dmv', 'Nightlife', 'popular', 'tiktok', 73, 'positive', 'One of DC''s most buzzed-about new openings — a sophisticated whiskey and craft beer bar on Capitol Hill with an exceptional spirits selection and intimate atmosphere.', 'Capitol Hill', '#intimate,#whiskeyfocused,#new,#hiddengem', ARRAY['Chill Night','Bar Hop','Happy Hour','Group Night Out','Girls Night','Guys Night','Couples Night','Best Friends Night','Anniversary Night']::text[], true, now(), 'dc-seed-v1'),
  ('Riff Raff Room', 'riff-raff-room', 'dmv', 'Nightlife', 'popular', 'instagram', 80, 'positive', 'A new neighborhood bar in Columbia Heights making waves on Eater DC''s best new bars list. Eclectic, fun, and affordable with a great playlist and strong cocktails.', 'Columbia Heights', '#eclectic,#divechic,#new,#latenight', ARRAY['Chill Night','Bar Hop','Happy Hour','Group Night Out','Girls Night','Guys Night','Couples Night','Best Friends Night']::text[], true, now(), 'dc-seed-v1'),
  ('The Dubliner', 'the-dubliner', 'dmv', 'Nightlife', 'popular', 'tiktok', 76, 'positive', 'DC''s most beloved Irish pub, steps from Union Station and the Capitol. A true institution — senators and staffers have been tipping pints here for 50 years. Live Irish music nightly.', 'Capitol Hill', '#classic,#lively,#casual,#political', ARRAY['Chill Night','Bar Hop','Happy Hour','Group Night Out','Girls Night','Guys Night','Couples Night','Best Friends Night']::text[], true, now(), 'dc-seed-v1'),
  ('Eebee''s Co.', 'eebees-co', 'dmv', 'Nightlife', 'popular', 'instagram', 73, 'positive', 'One of Eater DC''s best new bars of 2025/2026. A cocktail-forward neighborhood hangout in the Shaw/Logan Circle corridor with a fun, social vibe and creative drinks.', 'Shaw / Logan Circle', '#trendy,#new,#cocktailforward,#social', ARRAY['Chill Night','Bar Hop','Happy Hour','Group Night Out','Girls Night','Guys Night','Couples Night','Best Friends Night','Lounge Night','After-Hours Night']::text[], true, now(), 'dc-seed-v1'),
  ('Upstate FTW', 'upstate-ftw', 'dmv', 'Nightlife', 'popular', 'tiktok', 76, 'positive', 'An Eater DC-highlighted new bar bringing New York upstate dive bar energy to Shaw. Cheap beers, strong vibes, and zero pretension — a breath of fresh air in a neighborhood gone upscale.', 'Shaw', '#divebar,#unpretentious,#new,#neighborhood', ARRAY['Chill Night','Bar Hop','Happy Hour','Group Night Out','Girls Night','Guys Night','Couples Night','Best Friends Night']::text[], true, now(), 'dc-seed-v1');

commit;

-- 23 venues seeded.
