-- ============================================================
-- Confetti DMV Happy Hour — Seed Data
-- Migration: 20260528100000
-- ~20 real DMV venues + deals + neighborhoods + templates
-- Data approach: static seed, enrichment handles freshness
-- ============================================================

-- ─── 1. DMV Neighborhoods ──────────────────────────────────

insert into dmv_neighborhoods (id, name, slug, metro_area, zone_label, lat_center, lng_center, walkability, parking_ease, metro_access, metro_lines, peak_days, vibe_summary) values
  ('hood-navy-yard',       'Navy Yard',         'navy-yard',         'DC', 'Capitol Hill & Navy Yard',  38.8752, -77.0036, 5, 2, true,  ARRAY['Green']::text[],              ARRAY['Thu','Fri']::text[], 'Waterfront energy; new restaurants & rooftops; Nationals game-day crowd'),
  ('hood-u-street',        'U Street',          'u-street',          'DC', 'U Street Corridor',         38.9170, -77.0290, 5, 2, true,  ARRAY['Green','Yellow']::text[],      ARRAY['Thu','Fri','Sat']::text[], 'Live music roots; cocktail bars & late-night; young professional crowd'),
  ('hood-dupont',          'Dupont Circle',      'dupont-circle',     'DC', 'Dupont & Logan',            38.9096, -77.0434, 5, 2, true,  ARRAY['Red']::text[],                ARRAY['Wed','Thu','Fri']::text[], 'Embassy row meets dive bars; patio culture; cosmopolitan mix'),
  ('hood-georgetown',      'Georgetown',         'georgetown',        'DC', 'Georgetown & Foggy Bottom', 38.9076, -77.0723, 4, 1, false, '{}'::text[],                         ARRAY['Fri','Sat']::text[], 'Waterfront dining; cobblestone vibes; upscale cocktails; tourist-adjacent'),
  ('hood-shaw',            'Shaw',               'shaw',              'DC', 'Shaw & Howard',             38.9120, -77.0220, 5, 2, true,  ARRAY['Green','Yellow']::text[],      ARRAY['Thu','Fri']::text[], 'Speakeasy culture; craft cocktails; Black-owned gems; Blagden Alley'),
  ('hood-14th-street',     '14th Street',        '14th-street',       'DC', '14th Street NW',            38.9130, -77.0320, 5, 2, true,  ARRAY['Green','Yellow']::text[],      ARRAY['Thu','Fri','Sat']::text[], 'Rooftop row; brunch to late-night; trendy and fast-evolving'),
  ('hood-adams-morgan',    'Adams Morgan',       'adams-morgan',      'DC', 'Adams Morgan',              38.9212, -77.0425, 4, 2, false, '{}'::text[],                         ARRAY['Fri','Sat']::text[], 'Eclectic nightlife; dive bars next to cocktail lounges; 18th St strip'),
  ('hood-wharf',           'The Wharf',          'the-wharf',         'DC', 'Southwest Waterfront',      38.8787, -77.0230, 5, 2, true,  ARRAY['Green']::text[],              ARRAY['Thu','Fri','Sat']::text[], 'Waterfront boardwalk; upscale dining; live music pier; sunset views'),
  ('hood-bethesda',        'Bethesda',           'bethesda',          'MD', 'Bethesda & Chevy Chase',    38.9807, -77.0886, 4, 3, true,  ARRAY['Red']::text[],                ARRAY['Thu','Fri']::text[], 'Suburban polish; after-work professional scene; restaurant row on Woodmont'),
  ('hood-silver-spring',   'Silver Spring',      'silver-spring',     'MD', 'Downtown Silver Spring',    38.9936, -77.0266, 4, 3, true,  ARRAY['Red']::text[],                ARRAY['Thu','Fri']::text[], 'Diverse food scene; affordable; growing nightlife; Metro-accessible'),
  ('hood-national-harbor', 'National Harbor',    'national-harbor',   'MD', 'National Harbor',           38.7815, -77.0178, 3, 4, false, '{}'::text[],                         ARRAY['Fri','Sat']::text[], 'Resort waterfront; casino nightlife; chain + indie mix; weekend destination'),
  ('hood-clarendon',       'Clarendon',          'clarendon',         'VA', 'Clarendon & Courthouse',    38.8867, -77.0946, 4, 3, true,  ARRAY['Orange','Silver']::text[],     ARRAY['Thu','Fri']::text[], 'Arlington''s main drag; sports bars meets craft cocktails; young professional hub'),
  ('hood-old-town',        'Old Town Alexandria','old-town-alexandria','VA', 'Old Town',                  38.8048, -77.0469, 5, 2, true,  ARRAY['Blue','Yellow']::text[],       ARRAY['Thu','Fri','Sat']::text[], 'King Street charm; waterfront patios; historic meets modern cocktail bars'),
  ('hood-ballston',        'Ballston',           'ballston',          'VA', 'Ballston & Virginia Square',38.8816, -77.1117, 4, 3, true,  ARRAY['Orange','Silver']::text[],     ARRAY['Thu','Fri']::text[], 'Quarter development; brewery scene; after-work crowd; growing food hall');

-- ─── 2. Happy Hour Vibe Tags ───────────────────────────────

insert into happy_hour_vibe_tags (tag, display_label, category, emoji, sort_order) values
  ('after-work',      'After Work',       'occasion',    null, 1),
  ('date-happy-hour', 'Date Night HH',    'occasion',    null, 2),
  ('group-hangout',   'Group Hangout',     'occasion',    null, 3),
  ('solo-sipper',     'Solo Sipper',       'occasion',    null, 4),
  ('rooftop',         'Rooftop',           'setting',     null, 5),
  ('patio',           'Patio',             'setting',     null, 6),
  ('speakeasy',       'Speakeasy Vibes',   'setting',     null, 7),
  ('waterfront',      'Waterfront',        'setting',     null, 8),
  ('dive-bar',        'Dive Bar',          'setting',     null, 9),
  ('craft-cocktails', 'Craft Cocktails',   'drink_style', null, 10),
  ('wine-focused',    'Wine Focused',      'drink_style', null, 11),
  ('beer-garden',     'Beer Garden',       'drink_style', null, 12),
  ('oyster-bar',      'Oyster Bar',        'drink_style', null, 13),
  ('bougie',          'Bougie',            'mood',        null, 14),
  ('chill',           'Chill',             'mood',        null, 15),
  ('high-energy',     'High Energy',       'mood',        null, 16),
  ('intimate',        'Intimate',          'mood',        null, 17),
  ('young-professional','Young Professional','crowd',     null, 18),
  ('mixed-crowd',     'Mixed Crowd',       'crowd',       null, 19),
  ('industry-people', 'Industry People',   'crowd',       null, 20);

-- ─── 3. DMV Venues (into existing venues table) ────────────
-- IDs prefixed with 'hh-dmv-' for easy identification

insert into venues (id, name, slug, city, state, neighborhood, address, lat, lng, cuisine, cuisine_tags, vibe_tags, occasion_tags, price, price_level, vibe_notes, source_credit, is_verified) values
  -- DC Venues
  ('hh-dmv-001', 'The Salt Line',       'the-salt-line',       'Washington', 'DC', 'Navy Yard',      79 Potomac Ave SE,           38.8752, -77.0030, 'Seafood',    ARRAY['Seafood']::text[],           ARRAY['waterfront','trendy']::text[],    ARRAY['happy-hour','date-night','group']::text[], '$$',  2, 'Waterfront oyster bar; raw bar HH; rooftop with Nats stadium views', 'Manual 2026', true),
  ('hh-dmv-002', 'All-Purpose Navy Yard','all-purpose-navy-yard','Washington','DC', 'Navy Yard',      79 Potomac Ave SE,           38.8748, -77.0032, 'Italian',    ARRAY['Italian','Pizza']::text[],    ARRAY['trendy','group-friendly']::text[],ARRAY['happy-hour','after-work','group']::text[],  '$$',  2, 'Neapolitan pizza + craft cocktails; industrial-chic space; bustling bar', 'Manual 2026', true),
  ('hh-dmv-003', 'Dauphine''s',         'dauphines',           'Washington', 'DC', 'Shaw',           1100 15th St NW,             38.9052, -77.0345, 'NOLA',       ARRAY['Southern','Cajun']::text[],   ARRAY['speakeasy','intimate']::text[],   ARRAY['happy-hour','date-night']::text[],          '$$$', 3, 'Sultry NOLA-inspired; absinthe bar; jazz undertones; hidden entrance feel', 'Manual 2026', true),
  ('hh-dmv-004', 'Bar Charley',         'bar-charley',         'Washington', 'DC', 'Adams Morgan',   1825 18th St NW,             38.9212, -77.0425, 'Bar',        ARRAY['Cocktails']::text[],         ARRAY['chill','intimate']::text[],       ARRAY['happy-hour','date-night','solo']::text[],   '$',   1, 'Vintage cocktail bar; no-nonsense prices; wallpaper vibes; neighborhood gem', 'Manual 2026', true),
  ('hh-dmv-005', 'Officina',            'officina',            'Washington', 'DC', 'The Wharf',      1120 Maine Ave SW,           38.8787, -77.0230, 'Italian',    ARRAY['Italian']::text[],           ARRAY['waterfront','bougie']::text[],    ARRAY['happy-hour','date-night']::text[],          '$$$', 3, 'Multi-level Italian; rooftop amaro bar; waterfront Wharf location', 'Manual 2026', true),
  ('hh-dmv-006', 'Calico',              'calico',              'Washington', 'DC', 'U Street',       1307 U St NW,                38.9170, -77.0305, 'American',   ARRAY['American','Cocktails']::text[],ARRAY['trendy','craft-cocktails']::text[],ARRAY['happy-hour','after-work','group']::text[],  '$$',  2, 'Modern American + inventive cocktails; buzzy U Street corner; great patio', 'Manual 2026', true),
  ('hh-dmv-007', 'Service Bar',         'service-bar',         'Washington', 'DC', 'U Street',       926 U St NW,                 38.9170, -77.0267, 'Bar',        ARRAY['Cocktails']::text[],         ARRAY['speakeasy','industry-people']::text[],ARRAY['happy-hour','solo','date-night']::text[],  '$$',  2, 'Bartender-owned; no menu, tell them your mood; experimental cocktails', 'Manual 2026', true),
  ('hh-dmv-008', 'The Dignitary',       'the-dignitary',       'Washington', 'DC', 'Dupont Circle',  1601 14th St NW,             38.9096, -77.0343, 'American',   ARRAY['American','Cocktails']::text[],ARRAY['rooftop','bougie']::text[],       ARRAY['happy-hour','date-night']::text[],          '$$$', 3, 'Rooftop bar atop The Ven hotel; panoramic views; upscale cocktails', 'Manual 2026', true),
  ('hh-dmv-009', 'Dan''s Cafe',         'dans-cafe',           'Washington', 'DC', 'Adams Morgan',   2315 18th St NW,             38.9218, -77.0427, 'Dive Bar',   ARRAY['Dive Bar']::text[],          ARRAY['dive-bar','chaotic']::text[],     ARRAY['happy-hour','group']::text[],               '$',   1, 'Legendary DC dive; squeeze-bottle drinks; cash only; a rite of passage', 'Manual 2026', true),
  ('hh-dmv-010', 'Barmini',             'barmini',             'Washington', 'DC', 'Penn Quarter',   501 9th St NW,               38.8951, -77.0236, 'Cocktails',  ARRAY['Cocktails']::text[],         ARRAY['bougie','craft-cocktails']::text[],ARRAY['happy-hour','date-night','solo']::text[],   '$$$$',4, 'Jose Andres'' cocktail lab; molecular mixology; think Drink science experiments', 'Manual 2026', true),
  ('hh-dmv-011', 'Mission',             'mission',             'Washington', 'DC', 'Dupont Circle',  1606 20th St NW,             38.9110, -77.0467, 'Latin',      ARRAY['Latin','Tacos']::text[],     ARRAY['rooftop','high-energy']::text[],  ARRAY['happy-hour','group','after-work']::text[],  '$$',  2, 'Multi-level; rooftop with Navy beans; $5 taco + marg happy hour; packed', 'Manual 2026', true),

  -- Maryland Venues
  ('hh-dmv-012', 'Barrel & Crow',       'barrel-and-crow',     'Bethesda',   'MD', 'Bethesda',       4867 Cordell Ave,            38.9812, -77.0935, 'American',   ARRAY['American','Whiskey']::text[], ARRAY['chill','craft-cocktails']::text[],ARRAY['happy-hour','after-work']::text[],          '$$',  2, 'Whiskey-forward gastropub; 150+ bourbons; dark wood + leather; Bethesda mainstay', 'Manual 2026', true),
  ('hh-dmv-013', 'Gringos & Mariachis', 'gringos-mariachis',   'Bethesda',   'MD', 'Bethesda',       4928 Cordell Ave,            38.9815, -77.0937, 'Mexican',    ARRAY['Mexican']::text[],           ARRAY['high-energy','group-friendly']::text[],ARRAY['happy-hour','group','after-work']::text[],'$$',  2, 'Tequila-soaked fun; massive marg specials; loud and lively; happy hour famous', 'Manual 2026', true),
  ('hh-dmv-014', 'The Eleanor',         'the-eleanor',         'Silver Spring','MD','Silver Spring',  7030 Woodmont Ave,           38.9940, -77.0270, 'Bar',        ARRAY['Arcade','Cocktails']::text[], ARRAY['high-energy','group-friendly']::text[],ARRAY['happy-hour','group']::text[],              '$$',  2, 'Barcade with 70+ vintage games; craft beer + cocktails; Silver Spring HQ', 'Manual 2026', true),
  ('hh-dmv-015', 'Succotash National Harbor','succotash-nh',   'National Harbor','MD','National Harbor',156 Waterfront St,          38.7820, -77.0175, 'Southern',   ARRAY['Southern']::text[],          ARRAY['waterfront','bougie']::text[],    ARRAY['happy-hour','date-night','group']::text[],  '$$$', 3, 'Edward Lee''s Southern; waterfront patio; bourbon flights; upscale comfort', 'Manual 2026', true),

  -- Virginia Venues
  ('hh-dmv-016', 'Don Tito',            'don-tito',            'Arlington',  'VA', 'Clarendon',      3165 Wilson Blvd,            38.8867, -77.0956, 'Mexican',    ARRAY['Mexican']::text[],           ARRAY['high-energy','group-friendly']::text[],ARRAY['happy-hour','group','after-work']::text[],'$$',  2, 'Clarendon institution; frozen margs; patio packed at 5pm; taco specials', 'Manual 2026', true),
  ('hh-dmv-017', 'Green Pig Bistro',    'green-pig-bistro',    'Arlington',  'VA', 'Clarendon',      1025 N Fillmore St,          38.8870, -77.0930, 'American',   ARRAY['American','Farm-to-Table']::text[],ARRAY['intimate','chill']::text[],  ARRAY['happy-hour','date-night']::text[],          '$$',  2, 'Farm-to-table; inventive small plates; serious cocktails; Clarendon hidden gem', 'Manual 2026', true),
  ('hh-dmv-018', 'Virtue Feed & Grain', 'virtue-feed-grain',   'Alexandria', 'VA', 'Old Town Alexandria','106 S Union St,          38.8040, -77.0430, 'American',   ARRAY['American']::text[],          ARRAY['waterfront','trendy']::text[],    ARRAY['happy-hour','date-night','group']::text[],  '$$',  2, 'Converted feed house; soaring ceilings; waterfront patio; Old Town anchor', 'Manual 2026', true),
  ('hh-dmv-019', 'Hops N Shine',        'hops-n-shine',        'Arlington',  'VA', 'Ballston',       3340 Wilson Blvd,            38.8820, -77.1100, 'Bar',        ARRAY['Beer','Burgers']::text[],    ARRAY['dive-bar','chill']::text[],       ARRAY['happy-hour','after-work','group']::text[],  '$',   1, 'Gas station turned beer bar; 20+ taps; burgers + tots; no pretense; Arlington gem', 'Manual 2026', true),
  ('hh-dmv-020', 'Ada''s on the River',  'adas-on-the-river',  'Alexandria', 'VA', 'Old Town Alexandria','3 Pioneer Mill Way,       38.8010, -77.0405, 'American',   ARRAY['American','Seafood']::text[], ARRAY['waterfront','bougie']::text[],    ARRAY['happy-hour','date-night']::text[],          '$$$', 3, 'Stunning Potomac views; rooftop; elevated seafood; Alexandria''s newest gem', 'Manual 2026', true)
on conflict (id) do nothing;

-- ─── 4. Happy Hour Deals ───────────────────────────────────

insert into happy_hour_deals (venue_id, neighborhood_id, deal_name, deal_summary, drink_specials, food_specials, restrictions, days_active, start_time, end_time, avg_savings_pct, price_floor, price_ceiling, two_person_est, vibe_tags, crowd_level, noise_level, best_for, seating_type, is_verified, confidence, data_source) values
  -- DC
  ('hh-dmv-001', 'hood-navy-yard',    'Dollar Oysters & Half-Price Raw Bar',
   'Buck-a-shuck oysters + half-price raw bar at the waterfront',
   '[{"name":"House Wine","price":8,"type":"wine"},{"name":"Draft Beer","price":6,"type":"beer"}]'::jsonb,
   '[{"name":"Oysters","price":1,"type":"raw bar","original_price":3},{"name":"Raw Bar Platter","price":22,"type":"raw bar","original_price":44}]'::jsonb,
   'Bar and patio seating only', ARRAY['Mon','Tue','Wed','Thu','Fri']::text[], '16:00', '18:00',
   45, 1.00, 22.00, 40.00,
   ARRAY['waterfront','after-work']::text[], 4, 3, ARRAY['after-work','date','group']::text[], ARRAY['bar','patio']::text[],
   true, 'high', 'manual'),

  ('hh-dmv-002', 'hood-navy-yard',    '$10 Cocktails & $1 Oysters',
   'Full cocktail menu $10 + buck-a-shuck oysters; Navy Yard pre-game spot',
   '[{"name":"All Cocktails","price":10,"type":"cocktail"},{"name":"House Wine","price":8,"type":"wine"}]'::jsonb,
   '[{"name":"Oysters","price":1,"type":"raw bar"},{"name":"Margherita Pizza","price":10,"type":"pizza"}]'::jsonb,
   null, ARRAY['Mon','Tue','Wed','Thu','Fri']::text[], '16:30', '18:30',
   35, 1.00, 10.00, 35.00,
   ARRAY['after-work','group-hangout']::text[], 4, 4, ARRAY['after-work','group']::text[], ARRAY['bar','communal']::text[],
   true, 'high', 'manual'),

  ('hh-dmv-003', 'hood-shaw',         '$9 Classic Cocktails & Beignets',
   'NOLA classics for $9 + half-price beignets in a speakeasy setting',
   '[{"name":"Sazerac","price":9,"type":"cocktail"},{"name":"French 75","price":9,"type":"cocktail"},{"name":"Absinthe Drip","price":11,"type":"cocktail"}]'::jsonb,
   '[{"name":"Beignets","price":5,"type":"dessert","original_price":10},{"name":"Gumbo","price":8,"type":"soup"}]'::jsonb,
   'First floor bar only', ARRAY['Tue','Wed','Thu','Fri']::text[], '17:00', '19:00',
   30, 5.00, 11.00, 45.00,
   ARRAY['speakeasy','date-happy-hour','intimate']::text[], 3, 2, ARRAY['date','solo']::text[], ARRAY['bar','booth']::text[],
   true, 'high', 'manual'),

  ('hh-dmv-004', 'hood-adams-morgan',  '$8 Vintage Cocktails',
   'Classic cocktails done right for $8; the anti-pretentious happy hour',
   '[{"name":"Old Fashioned","price":8,"type":"cocktail"},{"name":"Gimlet","price":8,"type":"cocktail"},{"name":"Draft Beer","price":5,"type":"beer"}]'::jsonb,
   '[]'::jsonb,
   null, ARRAY['Mon','Tue','Wed','Thu','Fri']::text[], '17:00', '19:00',
   40, 5.00, 8.00, 25.00,
   ARRAY['chill','solo-sipper','intimate']::text[], 2, 2, ARRAY['date','solo','after-work']::text[], ARRAY['bar','booth']::text[],
   true, 'high', 'manual'),

  ('hh-dmv-005', 'hood-wharf',        'Aperitivo Hour — $10 Spritzes & Cicchetti',
   'Italian aperitivo on the Wharf; $10 spritzes + small plates',
   '[{"name":"Aperol Spritz","price":10,"type":"cocktail"},{"name":"Negroni","price":10,"type":"cocktail"},{"name":"Prosecco","price":8,"type":"wine"}]'::jsonb,
   '[{"name":"Cicchetti Plate","price":8,"type":"small plates"},{"name":"Burrata","price":10,"type":"small plates"}]'::jsonb,
   'Bar and terrace', ARRAY['Mon','Tue','Wed','Thu','Fri']::text[], '16:00', '18:00',
   30, 8.00, 10.00, 50.00,
   ARRAY['waterfront','bougie','date-happy-hour']::text[], 3, 3, ARRAY['date','after-work']::text[], ARRAY['bar','patio']::text[],
   true, 'high', 'manual'),

  ('hh-dmv-006', 'hood-u-street',     '$7 Draft + $9 Cocktails on the Patio',
   'U Street patio HH; drafts and cocktails well under $10',
   '[{"name":"Draft Beer","price":7,"type":"beer"},{"name":"Cocktail of the Day","price":9,"type":"cocktail"}]'::jsonb,
   '[{"name":"Crispy Wings","price":8,"type":"appetizer"}]'::jsonb,
   null, ARRAY['Mon','Tue','Wed','Thu','Fri']::text[], '16:00', '18:00',
   35, 7.00, 9.00, 30.00,
   ARRAY['after-work','patio']::text[], 3, 3, ARRAY['after-work','group']::text[], ARRAY['bar','patio']::text[],
   true, 'medium', 'manual'),

  ('hh-dmv-007', 'hood-u-street',     'Tell the Bartender Your Mood — $10',
   'No menu; bartender crafts your drink from a mood description; $10 flat during HH',
   '[{"name":"Custom Cocktail","price":10,"type":"cocktail"}]'::jsonb,
   '[]'::jsonb,
   'Bar seating only; no reservations', ARRAY['Tue','Wed','Thu']::text[], '17:00', '19:00',
   25, 10.00, 10.00, 30.00,
   ARRAY['speakeasy','craft-cocktails','solo-sipper']::text[], 2, 2, ARRAY['solo','date']::text[], ARRAY['bar']::text[],
   true, 'high', 'manual'),

  ('hh-dmv-008', 'hood-dupont',       'Rooftop Sunset: $12 Cocktails & $8 Wines',
   'Panoramic DC rooftop; discounted cocktails & wine as the sun sets',
   '[{"name":"Signature Cocktail","price":12,"type":"cocktail"},{"name":"Wine by Glass","price":8,"type":"wine"}]'::jsonb,
   '[{"name":"Truffle Fries","price":9,"type":"appetizer"}]'::jsonb,
   'Rooftop bar; weather permitting', ARRAY['Mon','Tue','Wed','Thu','Fri']::text[], '16:00', '19:00',
   25, 8.00, 12.00, 50.00,
   ARRAY['rooftop','bougie','date-happy-hour']::text[], 3, 3, ARRAY['date','after-work']::text[], ARRAY['bar','patio']::text[],
   true, 'medium', 'manual'),

  ('hh-dmv-009', 'hood-adams-morgan',  'Squeeze Bottles: All Night, All Cheap',
   'Legendary DC dive; bring your own cup vibes; impossibly cheap pours',
   '[{"name":"Squeeze Bottle Mixed Drink","price":4,"type":"spirit"},{"name":"PBR","price":3,"type":"beer"}]'::jsonb,
   '[]'::jsonb,
   'Cash only; no frills', ARRAY['Mon','Tue','Wed','Thu','Fri','Sat']::text[], '20:00', '02:00',
   60, 3.00, 5.00, 15.00,
   ARRAY['dive-bar','high-energy','group-hangout']::text[], 4, 5, ARRAY['group']::text[], ARRAY['bar']::text[],
   true, 'high', 'manual'),

  ('hh-dmv-010', 'hood-dupont',       '$14 Molecular Cocktails — Lab Happy Hour',
   'Jose Andres'' cocktail lab; discounted molecular mixology experiments',
   '[{"name":"Molecular Cocktail","price":14,"type":"cocktail","original_price":20}]'::jsonb,
   '[]'::jsonb,
   'Limited menu during HH; reservations recommended', ARRAY['Tue','Wed','Thu']::text[], '17:00', '19:00',
   30, 14.00, 14.00, 40.00,
   ARRAY['bougie','craft-cocktails','intimate']::text[], 2, 2, ARRAY['date','solo']::text[], ARRAY['bar']::text[],
   true, 'medium', 'manual'),

  ('hh-dmv-011', 'hood-dupont',       '$5 Tacos & $8 Margs on the Roof',
   'Dupont rooftop; tacos + margaritas; the after-work crowd magnet',
   '[{"name":"Margarita","price":8,"type":"cocktail"},{"name":"Draft Beer","price":6,"type":"beer"}]'::jsonb,
   '[{"name":"Street Tacos","price":5,"type":"taco"},{"name":"Guac & Chips","price":7,"type":"appetizer"}]'::jsonb,
   null, ARRAY['Mon','Tue','Wed','Thu','Fri']::text[], '16:00', '19:00',
   40, 5.00, 8.00, 30.00,
   ARRAY['rooftop','after-work','high-energy']::text[], 5, 4, ARRAY['after-work','group']::text[], ARRAY['bar','patio']::text[],
   true, 'high', 'manual'),

  -- Maryland
  ('hh-dmv-012', 'hood-bethesda',     'Half-Price Bourbon Flights',
   '150+ bourbon menu; flights at half price; the Bethesda whiskey HQ',
   '[{"name":"Bourbon Flight (3)","price":14,"type":"spirit","original_price":28},{"name":"Draft Beer","price":6,"type":"beer"}]'::jsonb,
   '[{"name":"Smoked Wings","price":8,"type":"appetizer"}]'::jsonb,
   null, ARRAY['Mon','Tue','Wed','Thu','Fri']::text[], '16:00', '18:00',
   50, 6.00, 14.00, 40.00,
   ARRAY['chill','craft-cocktails','after-work']::text[], 3, 3, ARRAY['after-work','solo','date']::text[], ARRAY['bar','booth']::text[],
   true, 'high', 'manual'),

  ('hh-dmv-013', 'hood-bethesda',     '$6 Jumbo Margs & $3 Street Tacos',
   'Tequila-soaked Bethesda staple; big pours, bigger energy',
   '[{"name":"Jumbo Margarita","price":6,"type":"cocktail"},{"name":"Tequila Shot","price":5,"type":"spirit"}]'::jsonb,
   '[{"name":"Street Tacos","price":3,"type":"taco"},{"name":"Nachos","price":7,"type":"appetizer"}]'::jsonb,
   null, ARRAY['Mon','Tue','Wed','Thu','Fri']::text[], '15:00', '18:00',
   50, 3.00, 7.00, 25.00,
   ARRAY['high-energy','group-hangout','after-work']::text[], 4, 4, ARRAY['group','after-work']::text[], ARRAY['bar','patio']::text[],
   true, 'high', 'manual'),

  ('hh-dmv-014', 'hood-silver-spring', '$5 Craft Pints + Free Play',
   'Barcade HH: $5 craft pints and free arcade games until 7',
   '[{"name":"Craft Pint","price":5,"type":"beer"},{"name":"Well Cocktail","price":7,"type":"cocktail"}]'::jsonb,
   '[]'::jsonb,
   'Free play on all machines during HH', ARRAY['Mon','Tue','Wed','Thu','Fri']::text[], '16:00', '19:00',
   35, 5.00, 7.00, 25.00,
   ARRAY['high-energy','group-hangout']::text[], 3, 4, ARRAY['group','after-work']::text[], ARRAY['bar','communal']::text[],
   true, 'high', 'manual'),

  ('hh-dmv-015', 'hood-national-harbor','Bourbon Sunset — $10 Flights & $12 Cocktails',
   'Edward Lee''s Southern; waterfront bourbon flights as the sun drops',
   '[{"name":"Bourbon Flight","price":10,"type":"spirit"},{"name":"Seasonal Cocktail","price":12,"type":"cocktail"}]'::jsonb,
   '[{"name":"Fried Chicken Bites","price":9,"type":"appetizer"},{"name":"Pimento Cheese","price":7,"type":"appetizer"}]'::jsonb,
   'Bar and patio', ARRAY['Tue','Wed','Thu','Fri']::text[], '16:00', '18:00',
   25, 7.00, 12.00, 50.00,
   ARRAY['waterfront','bougie','after-work']::text[], 3, 3, ARRAY['date','after-work']::text[], ARRAY['bar','patio']::text[],
   true, 'medium', 'manual'),

  -- Virginia
  ('hh-dmv-016', 'hood-clarendon',    '$5 Frozen Margs & $3 Tacos — Patio Party',
   'Clarendon''s happy hour king; frozen margs + tacos on the packed patio',
   '[{"name":"Frozen Margarita","price":5,"type":"cocktail"},{"name":"Draft Beer","price":4,"type":"beer"}]'::jsonb,
   '[{"name":"Street Tacos","price":3,"type":"taco"},{"name":"Queso","price":5,"type":"appetizer"}]'::jsonb,
   null, ARRAY['Mon','Tue','Wed','Thu','Fri']::text[], '15:00', '19:00',
   50, 3.00, 5.00, 25.00,
   ARRAY['high-energy','after-work','patio']::text[], 5, 4, ARRAY['group','after-work']::text[], ARRAY['bar','patio']::text[],
   true, 'high', 'manual'),

  ('hh-dmv-017', 'hood-clarendon',    '$9 Small Plates & $10 Cocktails',
   'Farm-to-table small plates + serious cocktails; Clarendon''s quieter gem',
   '[{"name":"Seasonal Cocktail","price":10,"type":"cocktail"},{"name":"Natural Wine","price":9,"type":"wine"}]'::jsonb,
   '[{"name":"Roasted Bone Marrow","price":9,"type":"small plate"},{"name":"Cheese Board","price":11,"type":"small plate"}]'::jsonb,
   null, ARRAY['Tue','Wed','Thu','Fri']::text[], '17:00', '19:00',
   25, 9.00, 11.00, 45.00,
   ARRAY['intimate','craft-cocktails','date-happy-hour']::text[], 2, 2, ARRAY['date','solo']::text[], ARRAY['bar','booth']::text[],
   true, 'high', 'manual'),

  ('hh-dmv-018', 'hood-old-town',     '$8 Drafts & $6 Oysters on the Waterfront',
   'Converted feed house; King Street waterfront; solid draft + oyster HH',
   '[{"name":"Draft Beer","price":8,"type":"beer"},{"name":"House Wine","price":9,"type":"wine"}]'::jsonb,
   '[{"name":"Oysters (6)","price":6,"type":"raw bar","original_price":14},{"name":"Deviled Eggs","price":5,"type":"appetizer"}]'::jsonb,
   'Bar and waterfront patio', ARRAY['Mon','Tue','Wed','Thu','Fri']::text[], '15:00', '18:00',
   40, 5.00, 9.00, 35.00,
   ARRAY['waterfront','after-work','group-hangout']::text[], 3, 3, ARRAY['after-work','group','date']::text[], ARRAY['bar','patio']::text[],
   true, 'high', 'manual'),

  ('hh-dmv-019', 'hood-ballston',     '$5 Craft Pints & $7 Smash Burgers',
   'Gas-station-turned-beer-bar; cheapest craft pints in Arlington',
   '[{"name":"Craft Pint","price":5,"type":"beer"},{"name":"Canned Cocktail","price":6,"type":"cocktail"}]'::jsonb,
   '[{"name":"Smash Burger","price":7,"type":"burger"},{"name":"Loaded Tots","price":5,"type":"appetizer"}]'::jsonb,
   null, ARRAY['Mon','Tue','Wed','Thu','Fri']::text[], '15:00', '18:00',
   40, 5.00, 7.00, 25.00,
   ARRAY['dive-bar','chill','after-work']::text[], 3, 3, ARRAY['after-work','group']::text[], ARRAY['bar','patio']::text[],
   true, 'high', 'manual'),

  ('hh-dmv-020', 'hood-old-town',     'Rooftop Spritz Hour — $11 Cocktails & Sunset',
   'Alexandria''s newest rooftop; Potomac sunset views; spritz-forward HH',
   '[{"name":"House Spritz","price":11,"type":"cocktail"},{"name":"Rosé","price":9,"type":"wine"}]'::jsonb,
   '[{"name":"Fried Calamari","price":10,"type":"appetizer"},{"name":"Tuna Tartare","price":12,"type":"appetizer"}]'::jsonb,
   'Rooftop only; weather permitting', ARRAY['Wed','Thu','Fri']::text[], '16:00', '18:00',
   25, 9.00, 12.00, 55.00,
   ARRAY['rooftop','waterfront','bougie','date-happy-hour']::text[], 3, 2, ARRAY['date','after-work']::text[], ARRAY['bar','patio']::text[],
   true, 'medium', 'manual');

-- ─── 5. Itinerary Templates ───────────────────────────────

insert into happy_hour_itinerary_templates (id, name, slug, tagline, description, metro_area, neighborhood_ids, occasion, mood, duration_hours, stop_count, stops, vibe_arc, best_days, budget_range, pro_tip) values
  ('tpl-navy-yard-crawl',
   'Navy Yard Waterfront Crawl',
   'navy-yard-waterfront-crawl',
   'Oysters to Nightcaps on the Water',
   'Start with dollar oysters at The Salt Line, pivot to pizza and cocktails at All-Purpose, then stroll the boardwalk to The Wharf for an Italian nightcap at Officina. All waterfront, all walkable.',
   'DC',
   ARRAY['hood-navy-yard','hood-wharf']::text[],
   'after-work',
   'Waterfront Unwind',
   3.5, 3,
   '[{"venue_id":"hh-dmv-001","order":1,"duration_min":60,"transition_note":"2-min walk along the boardwalk"},{"venue_id":"hh-dmv-002","order":2,"duration_min":50,"transition_note":"Grab a Lyft or walk 15 min along Maine Ave to The Wharf"},{"venue_id":"hh-dmv-005","order":3,"duration_min":60,"transition_note":"End here — Uber home from the Wharf"}]'::jsonb,
   ARRAY['chill-start','energy-build','bougie-nightcap']::text[],
   ARRAY['Thu','Fri']::text[],
   '$40–$70 per person',
   'Hit The Salt Line by 4:15 to snag patio seats before the Nats crowd rolls in.'),

  ('tpl-u-street-speakeasy',
   'U Street Speakeasy Circuit',
   'u-street-speakeasy-circuit',
   'Jazz Age Vibes & Modern Pours',
   'Begin at Service Bar where the bartender reads your mood. Walk to Calico for patio cocktails on the corner. End at Dauphine''s in Shaw for absinthe-laced NOLA vibes. Three stops, zero menus needed.',
   'DC',
   ARRAY['hood-u-street','hood-shaw']::text[],
   'date-night',
   'Speakeasy Discovery',
   3.0, 3,
   '[{"venue_id":"hh-dmv-007","order":1,"duration_min":50,"transition_note":"5-min walk up U Street"},{"venue_id":"hh-dmv-006","order":2,"duration_min":50,"transition_note":"10-min walk to Shaw or quick Lyft"},{"venue_id":"hh-dmv-003","order":3,"duration_min":60,"transition_note":"Night ends in a NOLA haze"}]'::jsonb,
   ARRAY['mysterious-start','energetic-middle','sultry-finish']::text[],
   ARRAY['Thu','Fri']::text[],
   '$45–$75 per person',
   'At Service Bar, say "something smoky with citrus" — trust the bartender.'),

  ('tpl-clarendon-classic',
   'Clarendon Happy Hour Marathon',
   'clarendon-happy-hour-marathon',
   'Arlington''s Happy Hour Highway',
   'Start early at Don Tito with frozen margs and tacos, slide into Green Pig Bistro for something more refined, then close it out at Hops N Shine for $5 craft pints. All within a 10-minute walk on Wilson Blvd.',
   'VA',
   ARRAY['hood-clarendon','hood-ballston']::text[],
   'group-crawl',
   'After-Work Rally',
   3.0, 3,
   '[{"venue_id":"hh-dmv-016","order":1,"duration_min":60,"transition_note":"5-min walk down Wilson Blvd"},{"venue_id":"hh-dmv-017","order":2,"duration_min":50,"transition_note":"10-min walk or 1 Metro stop to Ballston"},{"venue_id":"hh-dmv-019","order":3,"duration_min":50,"transition_note":"Uber home or stumble to the Metro"}]'::jsonb,
   ARRAY['party-start','refined-middle','dive-finish']::text[],
   ARRAY['Thu','Fri']::text[],
   '$25–$50 per person',
   'Don Tito patio fills by 4pm on Fridays — get there at 3:30 or regret it.'),

  ('tpl-old-town-waterfront',
   'Old Town Alexandria Waterfront',
   'old-town-waterfront-evening',
   'King Street to Sunset on the Potomac',
   'Walk King Street down to the water at Virtue Feed & Grain for oysters and drafts, then stroll to Ada''s on the River for rooftop spritzes as the sun sets over the Potomac. Two-stop elegance.',
   'VA',
   ARRAY['hood-old-town']::text[],
   'date-night',
   'Waterfront Romance',
   2.5, 2,
   '[{"venue_id":"hh-dmv-018","order":1,"duration_min":70,"transition_note":"5-min waterfront walk south"},{"venue_id":"hh-dmv-020","order":2,"duration_min":70,"transition_note":"Sunset stroll home along the water"}]'::jsonb,
   ARRAY['relaxed-start','romantic-finish']::text[],
   ARRAY['Wed','Thu','Fri']::text[],
   '$40–$65 per person',
   'Time it so you arrive at Ada''s rooftop 30 minutes before sunset. Golden hour is undefeated.'),

  ('tpl-bethesda-bourbon',
   'Bethesda Bourbon & Bites',
   'bethesda-bourbon-and-bites',
   'Whiskey Trail on Woodmont',
   'Start with half-price bourbon flights at Barrel & Crow, then walk one block to Gringos & Mariachis for jumbo margs and street tacos. Opposite vibes, same great strip. The Bethesda two-fer.',
   'MD',
   ARRAY['hood-bethesda']::text[],
   'after-work',
   'Suburban Sophisticate',
   2.5, 2,
   '[{"venue_id":"hh-dmv-012","order":1,"duration_min":70,"transition_note":"1-block walk on Cordell Ave"},{"venue_id":"hh-dmv-013","order":2,"duration_min":70,"transition_note":"Metro Red Line home or Uber"}]'::jsonb,
   ARRAY['sophisticated-start','party-finish']::text[],
   ARRAY['Thu','Fri']::text[],
   '$30–$55 per person',
   'Barrel & Crow''s back bourbon shelf has rare pours — ask the bartender what just came in.'),

  ('tpl-adams-morgan-contrast',
   'Adams Morgan: Craft to Chaos',
   'adams-morgan-craft-to-chaos',
   'From $8 Old Fashioneds to Squeeze Bottles',
   'Start civilized at Bar Charley with vintage cocktails in a wallpapered den. Then walk one block to Dan''s Cafe and embrace the chaos. The most DC contrast you''ll ever experience in 200 feet.',
   'DC',
   ARRAY['hood-adams-morgan']::text[],
   'group-crawl',
   'Contrast Theory',
   2.5, 2,
   '[{"venue_id":"hh-dmv-004","order":1,"duration_min":70,"transition_note":"1-block walk up 18th Street — enjoy the whiplash"},{"venue_id":"hh-dmv-009","order":2,"duration_min":70,"transition_note":"Cash only. You''ve been warned."}]'::jsonb,
   ARRAY['civilized-start','chaotic-finish']::text[],
   ARRAY['Thu','Fri','Sat']::text[],
   '$15–$30 per person',
   'Bring cash for Dan''s. No card, no exceptions. The squeeze bottle is the experience.');
